### ISSUE TITLE
Some projects that might be useful for inspiration

### ISSUE THREAD

**Issue by Darthagnon** [derrod/legendary#1]
Thank you so much for making this software! The Epic Games Launcher is bad, and your software is good! I look forward to seeing its future!

In my research, I've come across some other Epic Games-related scripts, etc. which I thought might be useful for inspiration/API reference?

[Free Game claimer script (Python)](https://github.com/MasonStooksbury/Free-Games)

[Free Game claimer script (NodeJS)](https://github.com/Revadike/epicgames-freebies-claimer)

[Epic Games client in NodeJS](https://github.com/SzymonLisowiec/node-epicgames-client)

**Comment by derrod** [comment]
Thanks but none of these projects really implement anything that is relevant to legendary. I do not intend to support friends lists etc. And features that might be supportable in the future such as cloud saves are not documented by them.
