### ISSUE TITLE
Point to an existing game installed via Lutris/EGS/etc already?

### ISSUE THREAD

**Issue by mynamewastaken** [derrod/legendary#10]
Tried copying files from an existing install and the amount downloaded didn't seem to change. I also tried to set `--game-folder $path` without success.

**Comment by derrod** [comment]
Importing games isn't supported yet. When importing from EGS in a wine root it could be pretty easy, otherwise I'd probably do something similar to Steam and hash the entire game to verify that it matches the latest version.
