### ISSUE TITLE
Football Manager 2020 doesn't work with legendary, it start when launched with EGS

### ISSUE THREAD

**Issue by fsyy** [derrod/legendary#100]
Football Manager 2020 doesn't start when launched with legendary, it does start when launched by EGS directly.

I double checked prefix, should be identical.

Error i get when launching it:

[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[Core] INFO: Getting ownership token.
Traceback (most recent call last):
  File "/usr/bin/legendary", line 33, in <module>
    sys.exit(load_entry_point('legendary-gl==0.20.1', 'console_scripts', 'legendary')())
  File "/usr/lib/python3.8/site-packages/legendary/cli.py", line 1284, in main
    cli.launch_game(args, extra)
  File "/usr/lib/python3.8/site-packages/legendary/cli.py", line 472, in launch_game
    params, cwd, env = self.core.get_launch_parameters(app_name=app_name, offline=args.offline,
  File "/usr/lib/python3.8/site-packages/legendary/core.py", line 350, in get_launch_parameters
    ovt = self.egs.get_ownership_token(game.asset_info.namespace,
AttributeError: 'NoneType' object has no attribute 'asset_info'

Other games i use work perfectly.

**Comment by fsyy** [comment]
ok, after i run legendary status, it does start.

why this always happens after i posted an issue... :)

**Comment by derrod** [comment]
The problem was likely that legendary's game database wasn't updated since the game had been installed via EGS rather than legendary itself.
