### ISSUE TITLE
Fails to uninstall FasterThanLight

### ISSUE THREAD

**Issue by rogama25** [derrod/legendary#101]
Hello, a few days ago I tried to install Faster Than Light and now I tried to uninstall it and it fails. Haven't tried this with other games. The version I had when installing the game was also 0.20.1. I'm using PopOS 20.04. Here are the logs: (I deleted the folder during the process, between the second and the third command and now it complains about that)
```
rogama@pop-os:~$ legendary uninstall Blowfish
Do you wish to uninstall "Faster Than Light"? [y/N]: y
[cli] WARNING: Removing game failed: AttributeError("'NoneType' object has no attribute 'is_dlc'"), please remove /home/rogama/legendary/FasterThanLight manually.


rogama@pop-os:~$ legendary --version
legendary version "0.20.1", codename "Endgame"


rogama@pop-os:~$ legendary list-installed

Installed games:
 * Faster Than Light (App name: Blowfish | Version: 1.6.12.Windows | 0.27 GiB)
  ! Game does no longer appear to be installed (directory "/home/rogama/legendary/FasterThanLight" missing)!

Total: 1
```
Would be great if you could fix the uninstall error and maybe asking to remove the game from the installed games list if the folder is missing completely.

**Comment by Tithen-Firion** [comment]
I had the same problem on Windows 10 when uninstalling HyperLightDrifter. It fixed itself after running `legendary status`.

**Comment by derrod** [comment]
I'm really not sure how that situation happened, is the game exported to EGL? It might be reimported every time you run `list-installed` but miss some metadata causing issues. Really not sure what happened there.

**Comment by Tithen-Firion** [comment]
In my case:
- the game was installed with legendary 0.19.something (2?), couldn't uninstall with it, couldn't uninstall with 0.20.1 either
- never used EGL option, don't have EGL installed
- `list-installed` didn't help
- HyperLightDrifter wasn't listed among "updated manifest" list when running `legendary status`

What can be done next time this happens? What files to send so you can debug it?

**Comment by derrod** [comment]
I still don't know exactly how you ended up in that situation, but best I can tell loading the metadata fails *for some reason* when trying to check whether or not the game has DLC available and installed. I have a tentative fix for this that will at least show a warning.
