### ISSUE TITLE
Fortnite Install Error

### ISSUE THREAD

**Issue by Jawschamp** [derrod/legendary#102]
I used ``legendary install Fortnite --old-manifest http://epicgames-download1.akamaized.net/Builds/Fortnite/CloudDir/dLIo12SBCCJ13prtkEux9bq75peaaA.manifest`` which is Fortnite Version 12.00

It downloaded but most of it had errors in it any idea why it would fail? For reference I used https://github.com/polynite/fn-releases/blob/master/README.md#season-12

**Comment by derrod** [comment]
`--old-manifest` tells legendary to attempt to patch from that manifest to the latest, it's only really there for testing purposes. You want to use `--manifest`.
