### ISSUE TITLE
Keyboard not working; Arch Linux

### ISSUE THREAD

**Issue by AlexB00T** [derrod/legendary#103]
Launching any game the game will not detect the keyboard when playing any games through legendary provided by the aur, have only managed to get rocket league working by plugging in a spare xbox controller and using that to play

**Comment by derrod** [comment]
Yeah no, I have no idea what would even cause this, but legendary does *nothing* related to keyboards or input or anything. This is just Linux being stupid, try asking some people on a Linux related forum for advice because I don't have any.
