### ISSUE TITLE
Don't remove user comments from config.ini

### ISSUE THREAD

**Issue by murlakatamenka** [derrod/legendary#105]
Use case: if you try various configs and comment lines to temporarily disable things, they get removed:
```ini
; Rocket League
[Sugar]
offline = false
; wrapper = "/path/to/proton" run
; no_wine = true
```
turns into
```ini
[Sugar]
offline = false
```
after launch. It's quite annoying to restore those commented lines back. 

Thanks.

**Comment by CommandMC** [comment]
For that, https://github.com/derrod/legendary/blob/28f0b72f422cc5a4089af623807b9450517c3f19/legendary/lfs/lgndry.py#L30 would have to be changed to `self.config = configparser.ConfigParser(comment_prefixes='/', allow_no_value=True)` (taken from https://stackoverflow.com/questions/21476554/update-ini-file-without-removing-comments)

**Comment by murlakatamenka** [comment]
I forgot something. Thank you @derrod
