### ISSUE TITLE
Borderlands 2 can't start online services on Linux

### ISSUE THREAD

**Issue by Blaster84x** [derrod/legendary#108]
I downloaded Borderlands 2 today, and it only works in offline mode, online throws a message "Epic Games Launcher not installed". Can Legendary emulate it or something? (launched using lutris, wine version lutris-5.7-9-x86-64) Or is it a known issue with no way to resolve?

**Comment by CommandMC** [comment]
Not a legendary issue

I think installing EGL in the wine prefix helps

**Comment by derrod** [comment]
How are you running it? Last time I checked it should work, but maybe they changed something with the EOS SDK update.

**Comment by Blaster84x** [comment]
Lutris using the parameters from `legendary launch --dry-run Dodo`,
executable is Borderlands2.exe because Launcher.exe doesn't start. Also
didn't try the install EGL thing yet, will send back the results.

**Comment by derrod** [comment]
The parameters are only valid for like 3-5 minutes. If you want to play online you have to launch the game through legendary itself.
