### ISSUE TITLE
Change Install Directory of Games

### ISSUE THREAD

**Issue by Beats24-7** [derrod/legendary#109]
Hi there,
is it possible to change the install directory of a game with a "legendary" command? I cannot find it and import-game is not working as it already is installed. I had to move a game to a different folder and now I cannot start it anymore as it is looking for the old folder. Thanks!

**Comment by CommandMC** [comment]
Why don't people just simply read the readme...

**Comment by CommandMC** [comment]
Nevermind, you're asking for a specific game (sorry, didn't get enough sleep today)

As far as I know, the only way to do that is either to "uninstall" it and then import it or to edit the `install_path` inside `installed.json` (inside your config folder)

**Comment by CommandMC** [comment]
Ofc, if you're changing the install folder of all your games, be sure to edit the path inside the config too

**Comment by Beats24-7** [comment]
No worries, I appreciate your quick response! 
I found the installed.json file and changed the directory / install path and it is working, thanks! Too bad you cannot set different paths for different games. It's not possible, right?

**Comment by CommandMC** [comment]
In your legendary config folder (`%userprofile%/.config/legendary/` on Win, `~/.config/legendary/` on Linux, not sure on Mac), there should be a `config.ini` file. In there, you can set the default install path like so:
```ini
[Legendary]
install_dir = /path/to/any/dir
```

I don't see why it wouldn't be possible to set different paths for different games, just edit the key in the json file for only that one game

**Comment by Beats24-7** [comment]
Ok, the config file is empty right now. I can add the install_dir path there, it is working without right now as well though.
Ah, it's because right now I have only one game installed. There will be more entries in the json file when I install more games, right? I get it now.

**Comment by CommandMC** [comment]
Yup, you got it!
Be sure to read the last section of the readme to find out what other stuff you can put into your config
