### ISSUE TITLE
RDR2 doesn't launch

### ISSUE THREAD

**Issue by Lepidos** [derrod/legendary#110]
GTA V doesen't launch for me neither RDR2. After a while Rockstar Games Launcher minimizes and legendary exits.

> [9d2d0eb64d5c44529cece33fe2a46482]
wrapper = "/home/lepidos/.steam/steam/steamapps/common/Proton 5.0/proton" run
start_params = ""
no_wine = true

> [9d2d0eb64d5c44529cece33fe2a46482.env]
WINEPREFIX = /home/lepidos/2tb_ssd_king/SteamLibrary/steamapps/compatdata/271590
WINEDLLOVERRIDES = winedbg.exe=d
STEAM_COMPAT_DATA_PATH = /home/lepidos/2tb_ssd_king/SteamLibrary/steamapps/compatdata/271590

Also tested with _wine_executable_. Same behaviour. Exits with:
> wine: Unhandled page fault on write access to 00000000CA2729E0 at address 00000001412A04FF (thread 0480), starting debugger...

**Comment by CommandMC** [comment]
Technically this is a wine and not a legendary issue

Did you test both games in a clean prefix? GTA works for me (at least it did a couple weeks ago)

**Comment by Lepidos** [comment]
Indeed, yesterday was working... I'm now going to test with a clean prefix

**Comment by Lepidos** [comment]
Tested RDR2 using this **script** to launch official epic games store launcher. And it works. But not on legendary.

> #!/bin/bash
export LD_LIBRARY_PATH="$HOME/.steam/root/compatibilitytools.d/proton-5.0-rdr2-4/dist/lib:$HOME/.steam/root/compatibilitytools.d/proton-5.0-rdr2-4/dist/lib64:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu/sse2:/lib/i386-linux-gnu/i686/sse2:/lib:/lib32:/lib/i386-linux-gnu:/lib/x86_64-linux-gnu:/lib64:/lib64:/usr/lib:/usr/lib64:/usr/lib32:/usr/lib64:/usr/lib/i386-linux-gnu:/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
export VK_ICD_FILENAMES="/etc/vulkan/icd.d/amd_icd32.json:/etc/vulkan/icd.d/amd_icd64.json"
export VKBASALT_CONFIG_FILE="/home/lepidos/Dropbox/Linux/Gaming/VKBasalt_confs/vkBasalt.conf"
export ENABLE_VKBASALT="1"
export RADV_PERFTEST="aco"
export DXVK_HUD="fps"
export DXVK_LOG_LEVEL="none"
export WINEDEBUG="-all"
export WINEESYNC="1"
export WINEUSERNAME="lepidos"
export WINESERVER="$HOME/.steam/root/compatibilitytools.d/proton-5.0-rdr2-4/dist/bin/wineserver"
export WINE="$HOME/.steam/root/compatibilitytools.d/proton-5.0-rdr2-4/dist/bin/wine"
export WINEPREFIX="$HOME/Games/epic-games-store"
export WINEDLLOVERRIDES="dxgi=n,b"
WINE="$HOME/.steam/root/compatibilitytools.d/proton-5.0-rdr2-4/dist/bin/wine"
GAME_EXE="$HOME/Games/epic-games-store/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe" 
"$WINE" "$GAME_EXE" -opengl -SkipBuildPatchPrereq

**legendary config.ini**

> [Legendary]
log_level = debug
max_memory = 1024
install_dir = /home/lepidos/2tb_firecuda/epic
locale = en-US
egl_sync = true
egl_programdata = /home/lepidos/Games/epic-games-store/drive_c/ProgramData/Epic/EpicGamesLauncher/Data/Manifests
[default]
wine_executable = /home/lepidos/.steam/root/compatibilitytools.d/proton_tkg_5.17.r0.stagging.esync.fs_hack/dist/bin/wine64
wine_prefix = /home/lepidos/Games/epic-games-store
offline = false
skip_update_check = false
start_params = -windowed
language = en
[default.env]
WINEPREFIX = /home/lepidos/Games/epic-games-store
DXVK_STATE_CACHE_PATH = /home/lepidos/Dropbox/Linux/Gaming/dxvk-cache/radv/dash
VKBASALT_CONFIG_FILE = /home/lepidos/Dropbox/Linux/Gaming/VKBasalt_confs/vkBasalt.conf
ENABLE_VKBASALT = 1
WINEESYNC = 1
WINEDEBUG = -all
DXVK_HUD = fps
DXVK_ASYNC = 1
DXVK_LOG_LEVEL = none
DXVK_CONFIG_FILE = ""
[Heather]
wine_executable = /home/lepidos/.steam/root/compatibilitytools.d/proton-5.0-rdr2-4/dist/bin/wine64
start_params = -ignorepipelinecache -borderless -vulkan
no_wine = false
[Heather.env]
WINEPREFIX = /home/lepidos/Games/epic-games-store
WINEDLLOVERRIDES = dxgi=n,b

**Comment by Lepidos** [comment]
GTA V is working fine.

**Comment by Lepidos** [comment]
RDR2 is launching allright :+1:
