### ISSUE TITLE
OSError: [WinError 8] Not enough memory resources are available to process this command (windows)

### ISSUE THREAD

**Issue by RawGamingYT** [derrod/legendary#111]
Yeah, I get the OSError: [WinError 8] Not enough memory resources are available to process this command error when I run the install command and after that I confirmed that I want to install the game (Rocket League), oh btw I'm using this because epic games launcher is retarded and downloads at 5 kb/s.

**Comment by derrod** [comment]
See the README. You need 64 bit python.
