### ISSUE TITLE
Windows Epic Games Launcher error

### ISSUE THREAD

**Issue by bhardesh2005** [derrod/legendary#117]
You can't play GTA V.... It says need to launch from epic games launcher

**Comment by derrod** [comment]
How are you launching the game?

**Comment by bhardesh2005** [comment]
> How are you launching the game?

legendary launch 9d2d0eb64d5c44529cece33fe2a46482

**Comment by bhardesh2005** [comment]
Actually I had the game files..... I imported the game....
I was done successfully! But Rockstar Games Launcher threw an error

**Comment by Jawschamp** [comment]
> 
> 
> Actually I had the game files..... I imported the game....
> It was done successfully! But Rockstar Games Launcher threw an error

So it an issue with Legendary?

**Comment by derrod** [comment]
Probably not, nobody else appears to have that problem and there hasn't been an update to GTA V in a month. I'll close this for now until I or somebody else can confirm this.

**Comment by Jawschamp** [comment]
I can test downloading it.

**Comment by Jawschamp** [comment]
Seems to launch correctly. 

> 
> 
> > How are you launching the game?
> 
> legendary launch 9d2d0eb64d5c44529cece33fe2a46482

do you have the updated version of Legendary?

**Comment by bhardesh2005** [comment]
> Seems to launch correctly. 
> 
> > 
> > 
> > > How are you launching the game?
> > 
> > legendary launch 9d2d0eb64d5c44529cece33fe2a46482
> 
> do you have the updated version of Legendary?

I have the latest

**Comment by bhardesh2005** [comment]
> > Seems to launch correctly. 
> > 
> > > 
> > > 
> > > > How are you launching the game?
> > > 
> > > legendary launch 9d2d0eb64d5c44529cece33fe2a46482
> > 
> > do you have the updated version of Legendary?
> 
> I have the latest

But anyways the problem was sorted... It is a one time setup by egl.... After it is done... I play without problems

**Comment by bhardesh2005** [comment]
When I uninstalled Epic Games launcher and tried re-importing the game files... I came Across this error

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\ProgramData\\Epic\\EpicGamesLauncher\\Data\\Manifests'
[7124] Failed to execute script cli

**Comment by bhardesh2005** [comment]
The Game now works perfectly after reauthenticating... Sorry to bother!
