### ISSUE TITLE
Wine gives me a fatal error when trying to launch Hyper Light Drifter

### ISSUE THREAD

**Issue by qwertyuiopleowo** [derrod/legendary#119]
so when I try to run Hyper Light Drifter, Wine gives me a little error window:

___________________________________________
############################################################################################
FATAL ERROR in Vertex Shader compilation
ShaderName: shd_PreMultiplyAlpha

memory:67:22: error: syntax error, unexpected NEW_IDENTIFIER

############################################################################################
--------------------------------------------------------------------------------------------
called from - gml_Script_shader_reset_HLD (line 2)
called from - gml_Script_MaskLoad (line 160)
called from - gml_Script_LevelLoad (line 499)
called from - gml_Object_SCREEN_Other_4 (line 109)

idk what it means

**Comment by derrod** [comment]
Neither do I, but this isn't an issue with legendary, but with WINE/HLD. Maybe google around for issues with wine and HLD.

**Comment by bhardesh2005** [comment]
Maybe try DXVK.... And see if it works

**Comment by CommandMC** [comment]
People using Proton are also getting the same error on Steams Win version, so you're probably out of luck with this game

https://www.protondb.com/app/257850
