### ISSUE TITLE
Support for overriding platform / platform-awareness

### ISSUE THREAD

**Issue by gibbed** [derrod/legendary#12]
A quick test patch to the following code to replace `Windows` with `Mac` was confirmed to work:

https://github.com/derrod/legendary/blob/0031e5908aa53451c5c8858e1d9f78d1f09df788/legendary/api/egs.py#L94-L98

https://github.com/derrod/legendary/blob/0031e5908aa53451c5c8858e1d9f78d1f09df788/legendary/api/egs.py#L100-L103

It appears legendary is currently storing metadata for things without regard of the platform it grabbed things from, so that's a concern as well.

It seems that despite being platform-specific, the manifest for games lists alternate platforms that are available (example from Fortnite):
```json
    "releaseInfo": [
      {
        "appId": "Fortnite",
        "compatibleApps": [],
        "dateAdded": "2014-09-11T00:00:00.000Z",
        "id": "...",
        "platform": [
          "Windows",
          "Mac"
        ]
      }
    ],
```

I'm not sure the best approach here just yet (still reading through legendary's code), but a way to specify a platform override for `legendary download` would be fantastic.

Hopefully this sort of usage is not out of scope for legendary? :relaxed:

**Comment by derrod** [comment]
Since I don't intend to support macOS and the Epic Game Store currently does not support the Linux platform I don't see any reason to change this yet. If they ever decide to deliver native Linux applications this can be updated rather easily.

**Comment by gibbed** [comment]
Fair enough, do you plan to pull platform-appropriate versions of games eventually then (ie Windows/Linux->Windows, Mac->Mac)? Since currently it's hardcoded to Windows.

**Comment by derrod** [comment]
Based on our chat on Discord I'll reopen this, while Legendary itself won't support macOS I will make platforms configuratble in the API for use in third party projects that import legendary components.
