### ISSUE TITLE
Not Working Correctly on My Pop!_OS 20.04 matchine

### ISSUE THREAD

**Issue by Tomoghno** [derrod/legendary#121]
Legendary auth works but after that when i list-games it tells me this and it is stuck.

tomoghno@pop-os:~$ legendary list-games
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Getting game list... (this may take a while)

and i mean for a long time.

**Comment by bhardesh2005** [comment]
try reauthenticating
legendary auth --delete
and then
legendary auth

**Comment by bhardesh2005** [comment]
and there is not reason for it to not work.... I tried it on ubuntu.. and it worked perfectly....
And Pop OS! is Ubuntu modified

**Comment by bhardesh2005** [comment]
Works just fine...
![legendary](https://user-images.githubusercontent.com/62708123/95705658-5cf07680-0c72-11eb-87ba-7890033a641a.png)

**Comment by derrod** [comment]
Try `legendary -v list-games` and see where it gets stuck.
