### ISSUE TITLE
Available games:  Total: 0

### ISSUE THREAD

**Issue by All3xJ** [derrod/legendary#122]
```
$ legendary -v list-games
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Getting game list... (this may take a while)
[Core] DEBUG: Set locale to it-IT

Available games:

Total: 0
```

**Comment by All3xJ** [comment]
> What's the issue here? That just means there don't appear to be any games on your account.

I thought that list-games was to display all the games in the store, my bad.

How could I import a game in my library and then install it?

**Comment by derrod** [comment]
Open the store in your web browser and add a game to your account: https://www.epicgames.com/store/
