### ISSUE TITLE
Borderlands 3 Previous saves not loading

### ISSUE THREAD

**Issue by Hiewxt** [derrod/legendary#123]
I Imported Borderlands 3 with `legendary import-game Catnip /run/media/hiew/"850 EVO"/Games/Borderlands3/`
then verified sucessfully with `legendary verify-game Catnip`
edited the legendary config.ini according to this other user's guide: https://gist.github.com/Wishfulbat/c0b4d49d11be2eb9e63ee6a6680c8ab7

The game launches fine and boots into the menu however it doesn't show my previous high level character I created on Windows.
I've tried using both
`legendary sync-saves Catnip`
`legendary download-saves Catnip`
Which seems to download something but once in game its still asks to create a new character

**Comment by derrod** [comment]
Depending on what you selected in the menu when running `sync-saves` you might have uploaded the Linux save to the cloud, rather than downloading the Windows save. Or possibly not configured the right folder. ´download-saves´ will download all available savegames into a folder called `.saves` in the configured legendary `install_dir` (`~/legendary` by default), in that case you'll have to manually move the save game data to the correct location.

**Comment by Hiewxt** [comment]
That is entirely possible. I'll double check I have the correct saves in the cloud.

**Comment by CommandMC** [comment]
Legendary can't know where to put the saves that EGS gives it. So yes, you're ment to move them wherever they're ment to go, which is different for each game

**Comment by Hiewxt** [comment]
Thanks for the help, and I apologize for my ignorance. I recently just ditched windows and I've been going head first into gaming on Manjaro. I've had quite a bit of success using lutris/steam and found this awesome project and would like to see it grow since the current solution for playing Epic games is jank at best. 
Since having trouble with this I thought it might have something to do with BL3 being on my windows ntfs drive so i copied it over to an ext4 partition, imported using `import-game` and verified again. So here lies the problem, In windows the BL3 save files are under `C:\Users\hiew\Documents\My Games\Borderlands 3\Saved\SaveGames\` 
Now I'm completely baffled as there doesn't seem to be a place for these ones anywhere. I checked inside `install_dir` made sure I have the correct save files in .saves. I've also checked inside 
`~/.wine/drive_c/users/hiew/My Documents/My Games/Borderlands 3/Saved/` which didn't have a `SaveGames/` folder so i created one and placed the save files in there to no avail. I have no idea what I'm missing or where to look.

**Comment by andremeireles** [comment]
@Hiewxt 
Create a new character and see where the file was saved. After that you edit the **installed.jon** file.

`"requires_ot":`
`"save_path": "/home/hiew/path you had discovered/Borderlands 3/Saved/SaveGames/",`
`"title": "Borderlands 3",`
`"version":`

**Comment by derrod** [comment]
While I know that the UX for saves is kinda crap this isn't really an issue with legendary itself (or at least not one I can fix easily). Though the main confusion seems to stem from the same problem as detailed in #41 so I'm going to close this in favor of that one.
