### ISSUE TITLE
Launch Problem

### ISSUE THREAD

**Issue by Deadbeastrs** [derrod/legendary#125]
Installed legendary via the repo, 
when im trying to launch a game i get the folowing error:
Thanks for the help!
---------------

FJsonStructReader - attempting to overwrite object property 'Class' for struct PresetMutators_X.
FJsonStructReader - attempting to overwrite object property 'Class' for struct PresetMutators_X.
FJsonStructReader - attempting to overwrite object property 'Class' for struct PresetMutators_X.
FJsonStructReader - attempting to overwrite object property 'Class' for struct PresetMutators_X.
FJsonStructReader - attempting to overwrite object property 'Class' for struct PresetMutators_X.
FJsonStructReader - attempting to overwrite object property 'Class' for struct PresetMutators_X.
Error, FSaveDataImportTask: '..\..\TAGame\SaveDataEpic\DBE_Production\6b642bf5c319434baea89b0f85151c07.save' no files found
0055:err:d3d:resource_unload Resource 0xa0ba5f0 is being unloaded while mapped.
0055:err:d3d:resource_unload Resource 0xa0ba990 is being unloaded while mapped.
0055:err:d3d:resource_unload Resource 0xa0baa30 is being unloaded while mapped.
0055:err:d3d11:d3d11_immediate_context_ClearDepthStencilView Failed to clear view, hr 0x8876086c.
0055:err:d3d11:d3d11_immediate_context_ClearDepthStencilView Failed to clear view, hr 0x8876086c.
0055:err:d3d11:d3d11_immediate_context_ClearDepthStencilView Failed to clear view, hr 0x8876086c.
0055:err:d3d11:d3d11_immediate_context_ClearDepthStencilView Failed to clear view, hr 0x8876086c.
0055:err:d3d11:d3d11_immediate_context_ClearDepthStencilView Failed to clear view, hr 0x8876086c.
0055:err:d3d11:d3d11_immediate_context_ClearDepthStencilView Failed to clear view, hr 0x8876086c.
0055:err:d3d11:d3d11_immediate_context_ClearDepthStencilView Failed to clear view, hr 0x8876086c.
0055:err:d3d11:d3d11_immediate_context_ClearDepthStencilView Failed to clear view, hr 0x8876086c.
0055:err:d3d11:d3d11_immediate_context_ClearDepthStencilView Failed to clear view, hr 0x8876086c.
0055:err:d3d11:d3d11_immediate_context_ClearDepthStencilView Failed to clear view, hr 0x8876086c.
*** WARNING - PATHS MAY NOT BE VALID ***
ScriptWarning, OnlineStorageSyncManager_TA_0 -------------- SaveObjectClass not valid TAGame.RefreshTokenSave_TA
	OnlineStorageSyncManager_TA Transient.SaveData_TA_1:OnlineStorageSyncManager_TA_0
	Function TAGame.OnlineStorageSyncManager_TA:Construct:009E
Script call stack:
	Function TAGame.OnlineStorageSyncManager_TA:Construct

0055:err:d3d:context_reacquire Acquired context 0xa16abc0 instead of 0xa0b8a60.
0.001518: info: found valid customer public key
AL lib: (EE) ReleaseThreadCtx: Context 0x7c33bc20 current for thread being destroyed, possible leak!

**Comment by derrod** [comment]
That's coming from the game and not legendary, you'll have to look for help with running that game in wine.
