### ISSUE TITLE
Games not launching

### ISSUE THREAD

**Issue by gabrielbelli** [derrod/legendary#131]
Every game I tried to launch on linux have dll errors.

For example:
 002c:fixme:winediag:LdrInitializeThunk wine-staging 5.17 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
003c:fixme:service:scmdatabase_autostart_services Auto-start service L"ClickToRunSvc" failed to start: 2
00e8:err:module:import_dll Loading library dxgi.dll (which is needed by L"Z:\\home\\belli\\legendary\\SUPERHOT\\SUPERHOT.exe") failed (error c000007b).
00e8:err:module:import_dll Loading library d3d9.dll (which is needed by L"Z:\\home\\belli\\legendary\\SUPERHOT\\SUPERHOT.exe") failed (error c000007b).
00e8:err:module:import_dll Loading library d3d11.dll (which is needed by L"Z:\\home\\belli\\legendary\\SUPERHOT\\SUPERHOT.exe") failed (error c000007b).
00e8:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\belli\\legendary\\SUPERHOT\\SUPERHOT.exe" failed, status c0000135

**Comment by CommandMC** [comment]
Not really a Legendary issue.

You probably don't have DXVK installed, right?

**Comment by gabrielbelli** [comment]
Yes, I have.

**Comment by gabrielbelli** [comment]
I don't know if it's a Legendary issue or not, but i'm contacting hoping for some help. And yes I have DXVK, and already play lots of games from other stores.

**Comment by gabrielbelli** [comment]
@CommandMC Do you know something I can do?

**Comment by bipox** [comment]
> @CommandMC Do you know something I can do?

What I had to do to make it work with SUPERHOT

First, [use Proton](https://github.com/derrod/legendary/wiki/Using-Proton)

Now after the first levels, or after after quitting the game for the first time (I don't know which), further launches will start (only launcher works)
You have to force the locale with `LC_ALL=C` if you're playing in english.
I'm playing in french so it's `LC_ALL=fr_FR` in my case.

For some reason the locale fix won't work if launched through Lutris
