### ISSUE TITLE
Paladins failing to open

### ISSUE THREAD

**Issue by redbrain** [derrod/legendary#137]
![image](https://user-images.githubusercontent.com/42494361/99616526-6e543d80-29eb-11eb-87b6-4938615750d6.png)
On launch, Paladins displays a splash screen, tries to begin a fullscreen window and then crashes.
Is this an issue with me/Legendary/Wine/Paladins, and how would I fix it?
Thanks in advance

**Comment by derrod** [comment]
Paladins uses Easy Anti-Cheat and will not run on Linux.
