### ISSUE TITLE
Terrible performance in GTA:V

### ISSUE THREAD

**Issue by Guttles** [derrod/legendary#138]
When I launch GTA from EGS from Lutris, the game runs flawlessly. But when I run it in legendary, using the same wine build and prefix as the EGS, it runs like a slideshow. This is my launch command:
launch 9d2d0eb64d5c44529cece33fe2a46482 --wine /home/user/.local/share/lutris/runners/wine/lutris-5.7-11-x86_64/bin/wine --wine-prefix /home/user/Games/epic-games-store

**Comment by derrod** [comment]
I guess Lutris sets some environment variables to enable additional WINE features, check the Lutris installer script and then adjust the legendary config.

**Comment by Guttles** [comment]
I added the variables in the config.ini, but I can't seem to enable esync, or the other arguments that go alone with running the EGS. What makes me think it's not working is that MangoHud doesn't appear at all, and the colors are all blown out when I get into game.
