### ISSUE TITLE
Terrible performance on Rocket League (but like really)

### ISSUE THREAD

**Issue by AnErrupTion** [derrod/legendary#139]
Hey!

So first, I wanted to let you know that your projet is awesome. I've installed Rocket League on my PC using your launcher, and well, as the title says, I get terrible performance. I can barely achieve 60 FPS at very low settings (I have a Radeon RX 550 2 GB which should perform much better at higher settings). I've updated my drivers and kernel to the latest version (I use Linux Lite 5.2) so I don't think it's that.

**Comment by CommandMC** [comment]
This is a Wine issue. Try running it with Proton, I have the Steam version and it works just fine there

**Comment by AnErrupTion** [comment]
How do I run it with Proton? I just do "legendary launch Sugar"

**Comment by Dummerle** [comment]
Do you installed dxvk for your wine prefix? It improves the performance

**Comment by AnErrupTion** [comment]
No I didn't, I'm not a wine expert so I don't know how to :/

**Comment by CommandMC** [comment]
Hop onto the discord, don't really wanna discuss here since people who follow the Repo get notifications about every comment
