### ISSUE TITLE
"Variables" inside config, but really just better wine management in general

### ISSUE THREAD

**Issue by CommandMC** [derrod/legendary#140]
So I've been using Legendary for a while now, and first off I can just chime in with everyone else: It's awesome. It makes using EGS so much more of an option on Linux, as Lutris isn't really suited for games with a launcher IMO.
Now, there's one thing I don't like thaaat much, and I get that this might just be me, but: I create a different wine prefix for each game I run. Keep em all in one folder, with just the game name as the prefix. Right now, for each new game, I have to edit the config, add the new prefix, maybe even change the wine version (I use proton for most games). And even worse, if I would want to change my "master" prefix location, I'd have to edit each one individually. This could be solved in two ways:
1. Make some sort of variable system where one could define variables inside the config
2. Generally overhaul how Wine is "seen" inside Legendary.

Let me explain what I mean by that 2. option:
While you could just solve this little issue, there's a bigger issue at hand: Right now, Wine is ran but not really "acted upon". It just kinda exists. What would IMO be better would be a full prefix selection system, kinda like how Lutris does it. That would also enable some other niceties, for example:
- Save data management
   - Downloaded save data getting placed in the correct folder
   - Uninstalling a game also uninstalls save data
- At one point maybe a tool like `legendarytricks` could exist which uses legendary to also get the prefix location

Now, this is not just limited to wineprefix integration. Legendary could track the whole process of the game, see if it's still running. Automatic save game synchronization comes to mind, maybe even something wacky like a Discord integration. Possibilitys are endless
And of course, version management. An `EGLdb` could exist, and legendary could automatically pull from that what version is best for what game, or what games just don't run outright

I get that this is probably just a wild dream, and as low priority as it could possibly get. But as a long term goal, this is my "vision" for Legendary. Thank you for creating this awesome program.

**Comment by derrod** [comment]
While I understand where you're coming I think much of this goes far beyond the scope of what I want and can do with this project given my time constraints.

Save file locations should already be correct as long as you supply the correct wine prefix when running the sync command, it's just not entirely automatic, but that's something I wanted to address with the ideas detailed in #41.

What I *do* plan to do is add an option to use Proton more easily, and set it up automatically as well to some extent (environment variables, compat dir, etc.). And possibly also add more options during the install process to automatically create a prefix directory and select a WINE version (if possible). But this will never be anything like Lutris in terms of automatic setup capabilities.

**Comment by derrod** [comment]
I didn't actually mean to close this yet. Whoops.

As far as variables are concerned making them user defined sounds a bit like a nightmare, what I could see being useful though is a few predefined ones such as `%game_dir%` or `%home%` that can be used to specify paths to prefixes more easily. You could define this in the default section as well and they would be resolved to whatever app you're running.

**Comment by CommandMC** [comment]
That sounds good. About the scope of this: I didn't really mean that everything would be covered by legendary itself, more like what having this one feature in the API would enable for other programs that might use it

Btw, might I ask for a `[default.env]` section where default environment variables can be set too? I'd like to have a simple FPS display for games, and DXVK has a good one enabled by setting `DXVK_HUD` to `fps`. Right now I put that into each games `.env` after the proton prefix

**Comment by derrod** [comment]
There is a `default.env` section, see the README.
