### ISSUE TITLE
Fortnite Save the world

### ISSUE THREAD

**Issue by Beat-YT** [derrod/legendary#142]
How can I download fortnite save the world (its an additional content to the game) and how can i get manifest

**Comment by derrod** [comment]
Is it no longer part of the main game? I know its paid now but if they also removed the data and require a separate download then my best guess is that it's essentially DLC.

**Comment by derrod** [comment]
Based on what I can gather, you need to have purchased access to the "Save the World" part of the game, but it is still included with the base game rather than being a DLC or anything.

**Comment by Beat-YT** [comment]
No, Its free to download but when your in the game you need to pay

**Comment by derrod** [comment]
Well then I don't see the problem. Just download Fortnite and assuming you have purchased access to the Save The World mode you should be able to just play it.

**Comment by Beat-YT** [comment]
![image](https://user-images.githubusercontent.com/66485277/99915542-4fe39000-2cd2-11eb-8203-d84847786a32.png)
Its will not work

**Comment by Beat-YT** [comment]
In epic games launcher
![image](https://user-images.githubusercontent.com/66485277/99915617-b36dbd80-2cd2-11eb-9973-b6fb724b6841.png)

**Comment by derrod** [comment]
Legendary doesn't support this selective downloading and will always download everything. If you install Fortnite via legendary it will have the Save the World content installed. If you imported it from the Epic Games Launcher you might have to run a repair. If that still doesn't work then unfortunately I can't help you as I do not have access to the Save the World content.

**Comment by Wryyyong** [comment]
> Legendary doesn't support this selective downloading and will always download everything.

Is this planned to be changed at some point in the future? Because whenever I try using/updating FN via EGL after having repaired it via Legendary (thus downloading STW and the additional languages), EGL seems to delete any non-checked items, meaning I'd have to redownload the files via Legendary again when verifying and repairing. I'd rather not have to go through that.

The only current alternative I can think of at the moment is checking all of items on that list inside EGL so it doesn't delete the items downloaded via Legendary, but I'd rather avoid having to do so if possible as it adds unneeded bloat to my installation, for stuff I don't use (as well as increasing update download filesizes).

**Comment by CommandMC** [comment]
IMO this is a very niche issue that would require quite a bit of work (looking through the metadata for Fortnite, there seems to be nothing that indicates these Install Options, but I might just not see it atm).

Why are you even using EGL after repairing the game with Legendary?

**Comment by Wryyyong** [comment]
> Why are you even using EGL after repairing the game with Legendary?

Maintenance and testing purposes, in case something gets screwed up on either end as a result of the other.

Truth be told, I was confused for a while on why download sizes were larger when using Legendary. Now I know.

**Comment by derrod** [comment]
*Technically* Legendary does support this internally via the `--install-tags` flag, but that's not implemented in a way where the selection would be saved or properly synced to EGL. Unfortunately it also does not seem like the install tags used for Fortnite are provided in an API anywhere and are possibly hardcoded into EGL. Without that it's kinda annoying to implement this, but I'll have to add that later anyway for proper Unreal Engine and Marketplace support. I'll create a separate and more concise issue for that however.
