### ISSUE TITLE
Support install tags

### ISSUE THREAD

**Issue by derrod** [derrod/legendary#143]
Install tags can be used to only install part of a manifest in case only some of its contents are desired. This is used by Fortnite for STW and language pack content as well as for Unreal Engine installations which can exclude parts of the otherwise fairly massive download.

Unfortunately it does not appear that the tags and what they relate to are documented anywhere or part of any API response that the client gets. So those may have to be somehow extracted from the Epic Games Launcher itself and then hardcoded into legendary.

For EGL sync this also can be supported, as the selected install tags are saved to the EGL manifest.

**Comment by derrod** [comment]
Seems like this information is contained in `.v2sdmeta` files that are downloaded as part of the launcher's "content" manifest. Downloading those files itself could be done on first startup + periodic update checks when legendary is run.

*Annoyingly* the way a match between a `SelDlMeta` file and a game is established is not just by id/app name, but also by a custom regex syntax for version checks, for example one the Fortnite ones:

```json
{
  "Namespace": "fn",
  "Item": "4fe75bbc5a674f4f9b356b5c90567da5",
  "Asset": "Fortnite",
  "Version": "Regex(\\+\\+Fortnite\\+Release-(.*)-CL-(\\d+)-.*) && RegexGroupInt64(2) < 4016789 && ((RegexGroupString(1) == \"Prep\" && RegexGroupInt64(2) >= 3779789) || (RegexGroupString(1) == \"Next\" && RegexGroupInt64(2) >= 3779794) || (RegexGroupString(1) == \"Cert\" && RegexGroupInt64(2) >= 3785892) || (RegexGroupInt64(2) >= 3846604))"
}
```

Unfortunately this regex also works in the other fields. For instance with Cyberpunk 2077's sdmeta file:

```json
{
  "Namespace": "77f2b98e2cef40c8a7437518bf420e47",
  "Item": "*",
  "Asset": "Regex(Ginger.*)",
  "Version": "*"
}
```

Implementing that is rather unlikely for me, but from the multiple Fortnite files only one is valid for the current version of the game, so it might be fine to simply hardcode which of those files to use for that game. For other games only one file appears to exist and worst case we can match by namespace and app name and ignore those fields with regex.

**Comment by derrod** [comment]
Mostly implemented now in 7609553b12091d9a40ec880d6e0b8cfa747288ef. Main things missing are:

* EGL Import
* Some testing

Both of those will be done before this feature is shipped with a release.

**Comment by derrod** [comment]
Now nearly done as of 1226cd1b08b76d0e7e4520b29109e873f0a1677e, mostly testing needed and I'd like to improve things so selecting additional tags doesn't require running a repair. But this may be enough for a first release.

**Comment by derrod** [comment]
I'll be honest though, I wish I had finished the planned rewrite of the downloader before this. At this point this is hacks upon hacks to get it to work. A new system for patching is desperately needed.

**Comment by Kein** [comment]
Any info on how can I use tags to download UE 4.25 with Epic Spylauncher?

**Comment by derrod** [comment]
Run the `list-files` command on UE, it'll show you the available install tags. You can then select the ones you want by specifying e.g. `--install-tag tag_1 --install-tag tag_2` etc. Ideally you'd check the `ue425.sdmeta` file that the Epic Games Launcher installs, that will have a proper breakdown of what the different tags are for in it.

Legendary itself is planned to get better Unreal Engine and UE Marketplace support in the future, but currently doesn't have it.

**Comment by Kein** [comment]
Well, I dont have `ue425.sdmeta`, obviously, since I want to avoid using Epic Launcher. If I run `list-files` on `.manifest` for 4.25 I get this list of tags:
`[cli] INFO: Install tags: editor_symbols, engine_source, platform_Android, platform_HoloLens, platform_IOS, platform_Linux, platform_Lumin, platform_TVOS, starter_content, templates`
I'm not seeing Windows here at all. Is tag detection complete?

**Comment by derrod** [comment]
Windows is alsoways included (unless using `--platform Mac`), the other platforms are optional. The reason it's that big is that legendary saves the raw manifest as downloaded from the CDN, whereas the epic games launcher converts it into the newer binary format before writing it to disk.
