### ISSUE TITLE
wine:64-bit application not supported in 32-bit prefix

### ISSUE THREAD

**Issue by tristansca** [derrod/legendary#144]
I installed legendary then i wanted to download Sugar(code named for Rocket League) then when i launched it it gave me this error:0009:err:module:__wine_process_init L"Z:\\home\\oem\\legendary\\rocketleague\\Binaries\\Win64\\RocketLeague.exe" 64-bit application not supported in 32-bit prefix

please help
Tristan

**Comment by derrod** [comment]
You have to use a 64 bit WINE prefix, if you're not familiar with WINE look up some tutorials on how to get started, though to get games running it's probably advisable to use Proton. You can join our Discord if you need further assitance, this issue tracker is not for general wine help.
