### ISSUE TITLE
Unable to read Manifests folder

### ISSUE THREAD

**Issue by galyfray** [derrod/legendary#145]
After running the `legendary egl-sync` command legendary correctly found my lutris egl however the program is not able to read the manifest due to this error : `[Core] ERROR: Unable to resolve path for mapped drive "c:" for WINE prefix at "/mnt"`.
A bit of details about my setup :
My default wine prefix use /mnt/Jeux as drive "c:". 
To unify all the lutris wine directory with my main wine dir I linked all lutris' `drive_c` to `/mnt/Jeux` I did not touch to .wine folders
I've tryed to change the path in `config.ini` file to the shorter version (using directly /mnt/Jeux) but it doesn't work

importing games manually work

**Comment by derrod** [comment]
I don't think this is a sane or safe way of handling WINE C: drives, and I'm not going to support it.

**Comment by galyfray** [comment]
I'm not asking for support wine c drive I'm asking for Legendary to be consistant with himself . Legendary find by it's hown a path to the egs manifest but hé can't use or in practice ! If it could find why he don't want to use ?
