### ISSUE TITLE
ValueError: No saved credentials

### ISSUE THREAD

**Issue by Tamely** [derrod/legendary#147]
Hi! I'm trying to install a manifest (Fortnite 14.30) and I am running into the "ValueError: No saved credentials" error. Is there a fix for this? 

legendary install Fortnite --manifest "https://epicgames-download1.akamaized.net/Builds/Fortnite/CloudDir/vSRBaHxfB_kuksWOEk2_PfUPG22MVw.manifest" --download-only --no-install --game-folder "C:\Users\MYUSER\Desktop\14.30"

**Comment by derrod** [comment]
Yes, login.

**Comment by Tamely** [comment]
I am logged in

**Comment by CommandMC** [comment]
To verify, if you run `legendary auth`, does it say that there are saved credentials or does it open up a browser window to login?
Keep in mind that legendary does not pull login data from your browser or the Epic Games Launcher and requires a separate login

**Comment by Tamely** [comment]
That fixed it! Thank you. I just forgot to enter my sid last time I did auth.
