### ISSUE TITLE
16 is too many workers, slows rest of machine down (Windows)

### ISSUE THREAD

**Issue by wyattscarpenter** [derrod/legendary#148]
First off, great tool, thanks! I'm using Windows 10 on a powerful laptop with a moderate internet connection. Legendary spawns 16 workers by default, as I have 8 logical cores (4 physical). However, this is empirically too many workers, as it causes the other processes on my computer that need internet, like my browser, to slow down, presumably because Windows won't share the internet with them very well.

**Comment by derrod** [comment]
I have absolutely no problem on an 6 year old gaming laptop and a desktop with a 9 year old CPU.

If your PC is too slow, just reduce the number of workes.

**Comment by derrod** [comment]
I will say though that it seems I forgot to make that a configuration file option. So I will do that as well so you don't have to add it manually every time.
