### ISSUE TITLE
Downloading Fortnite Manifests Not working

### ISSUE THREAD

**Issue by ProMasterBoy** [derrod/legendary#152]
When I try downloading older Fortnite versions with manifest I get this error. Not sure if it's just me or not.

![image](https://user-images.githubusercontent.com/36981621/102027532-e8b08b80-3df8-11eb-8d24-60fe7d8b1a9b.png)
![image](https://user-images.githubusercontent.com/36981621/102027551-07af1d80-3df9-11eb-898f-6b3bb23edeaf.png)

**Comment by CommandMC** [comment]
You can't download old manifests anymore. You can only install them if you have them downloaded already.

Btw, I see a lot of people trying to download old fortnite versions. Why's that?

**Comment by ProMasterBoy** [comment]
> You can't download old manifests anymore. You can only install them if you have them downloaded already.
> 
> Btw, I see a lot of people trying to download old fortnite versions. Why's that?

Well Fortnite Modding for older clients is easier they changed how the files worked in 14.40 so it's just easier to make custom skins and stuff.

**Comment by nutterthanos** [comment]
> You can't download old manifests anymore. You can only install them if you have them downloaded already.

well you can still download them its just you need to use download-dynamic.epicgames.com as the domain not download.epicgames.com or epicgames-download1.akamaized.net

**Comment by Aorux01** [comment]
> > Vous ne pouvez plus télécharger d'anciens manifestes. Vous ne pouvez les installer que s'ils sont déjà téléchargés.
> 
> Eh bien, vous pouvez toujours les télécharger, il vous suffit d'utiliser download-dynamic.epicgames.com comme domaine et non download.epicgames.com ou epicgames-download1.akamaized.net

I know this post was posted a long time ago... But now at least it's not working.
