### ISSUE TITLE
False positive on VirusTotal?

### ISSUE THREAD

**Issue by Z0pyrus** [derrod/legendary#159]
By scanning the latest Legendary.exe, VirusTotal says 5/70 are Positive: https://www.virustotal.com/gui/file/0c2957a3a11733ce7f7ed99cba993f05b2b23d4a6de052c40cc80229954690d4/detection

**Comment by CommandMC** [comment]
As far as the descriptions go, I'd guess any PyInstaller exe will get flagged there. It is definitely a false positive

**Comment by derrod** [comment]
Yeah, that's just PyInstaller, none of the trustworthy AV flag anything either.
