### ISSUE TITLE
[FR] Parse --prefix manually to split for multiple prefix entries support

### ISSUE THREAD

**Issue by Kein** [derrod/legendary#163]
`parse_know_args()` cannot process any of the input, even _suggested default_ (`"str1,str2,str3"`) as `List[str]`
The code here https://github.com/derrod/legendary/blob/104b928e3aa5feafc5e9b3e20360a7b62ca60c82/legendary/downloader/manager.py#L169 handles case of multiple prefix entries but due to the fact how args passed (always one `str`) it will match against 1 string.

**Comment by derrod** [comment]
To use multiple prefixes use the prefix flag multiple times, e.g. `--prefix firstprefix --prefix secondprefix`. I don't know where you see that suggested default, the README or help text are not suggesting a comma-separated list.

**Comment by Kein** [comment]
Ah, I see, that's explains why I had issues figuring it out - it was pretty opinionated and unintuitive
