### ISSUE TITLE
Is Epic Launcher required?

### ISSUE THREAD

**Issue by gpioneer90** [derrod/legendary#165]
Can Legendary be used as a complete replacement for Epic Launcher, and being able to uninstall Epic Launcher completely? Or is Epic Launcher being installed still required?

**Comment by CommandMC** [comment]
The EGL is not required, no. Be careful with uninstalling though, as it might uninstall all games with it

**Comment by derrod** [comment]
It's not required. But certain things such as the overlay may be uninstalled with it so inviting/joining friends as well as seeing achievements may not work in some games.

**Comment by gpioneer90** [comment]
That is the issue I ran across - so how to solve? After I uninstall EGL it removes the games, and then running a install command on legendary returns an error such as `legendary launch Morganite
Traceback (most recent call last):
  File "legendary\cli.py", line 1375, in <module>
  File "legendary\cli.py", line 1341, in main
  File "legendary\cli.py", line 435, in launch_game
  File "legendary\core.py", line 287, in get_installed_game
  File "legendary\core.py", line 1172, in egl_sync
  File "legendary\lfs\egl.py", line 46, in read_manifests
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\ProgramData\\Epic\\EpicGamesLauncher\\Data\\Manifests'
[3440] Failed to execute script cli`

**Comment by CommandMC** [comment]
Well you gotta install the games again if EGL removed them

**Comment by gpioneer90** [comment]
How? Through Legendary? It errors out now. If through EGL - then how do I remove EGL while keeping games safe and still working with Legendary only?

**Comment by derrod** [comment]
You'll have to disable the EGL sync.

**Comment by gpioneer90** [comment]
Sorry, so what is the best process if one doesn't want to have EGL and they encounter the above error I posted when attempting to download through Legendary without EGL present any more? Run `legendary egl-sync --unlink`, *then* can uninstall EGL? Or another sequence?
I can't believe uninstalling EGL gets rid of the games without warning! I just lost a save game to a game that didn't support cloud saving 👎 Epic sucks

**Comment by derrod** [comment]
Running the unlink command and then manually deleting all files in `C:\ProgramData\Epic\EpicGamesLauncher\Data\Manifests` should work fine.

Your save games are probably fine, they're usually not saved within the game's installation directory and are also not deleted when uninstalling.

**Comment by gpioneer90** [comment]
Cheers. Not completely sure why last time uninstalling EGL got rid of the games and this time it didn't (after I ran the unlink command and eleted the Manifests folder).
And save game is indeed lost :( it *was* saved in the game's folder. Thanks Epic. I wanted to get rid of Epic because it's raising my CPU temps 10c just running in the background, and causes the CPU fans to speed up while running....

well, at least thanks to you this bad software is off my computer and I can enjoy the games without the negative performance and thermal impact EGL provides! Thanks for this nice piece of software!
