### ISSUE TITLE
[Feature Request] macOS support?

### ISSUE THREAD

**Issue by UInt2048** [derrod/legendary#169]
It's possible to get and install a 64-bit version of Wine on macOS using the command `brew install wine-devel`, and it's ran using `wine64`.

Is there a specific reason that Legendary won't support macOS (cf. #12 and #28), even if just to run things that are 64-bit and Windows (a free example being [Rocket League](https://www.epicgames.com/store/en-US/product/rocket-league/home))? Is there anything I could do to help?

Edit: Sorry if this should have been in Discussions - I forgot that was a thing now.

**Comment by derrod** [comment]
I have no Mac and no interest in supporting macOS. I'd imagine legendary might work as-is anyway since macOS is reasonably similarly structured to Linux? But I certainly don't want to deal with maintenancy, issues, and testing on macOS.
