### ISSUE TITLE
Download seems to be stuck.

### ISSUE THREAD

**Issue by Nik7413** [derrod/legendary#170]
I was downloading a game called 'Inside'. After download like 90% of files, the download is just stuck. So, i pressed ctrl+c to stop it redownload the remaining files (436M to be exact). But after downloading like 430M, the download stops and doesnt moves again. Have retried multiple times but no success. Any ideas?

**Comment by derrod** [comment]
Try running the download with `legendary -v install --dlm-debug <rest of your command line>`

**Comment by hackermondev** [comment]
@derrod https://pastebin.com/m9wnk3nR

**Comment by derrod** [comment]
This is a two year old closed issue, please post that as a new issue including all the information requested in the form to make sure it doesn't get lost.
