### ISSUE TITLE
Question: Open Launcher.manifest

### ISSUE THREAD

**Issue by kaaax0815** [derrod/legendary#171]
I searched the whole Internet, but only found that you open the Launcher.manifest.
If I open it I only see garbage. Maybe you know how to open this file.
I am searching for a way how to easily change the account in epicgames launcher.
Maybe you can "invent" such thing

**Comment by derrod** [comment]
The EGS account you're logged into is saved in `GameUserSettings.ini`, nothing to do with the manifest or legendary.

**Comment by kaaax0815** [comment]
Im sorry, but the `GameUserSettings.ini` in `%localappdata%` doesnt contain any login information.
Either if its in the `Launcher.manifest` or not, how do I properly open it?

**Comment by derrod** [comment]
I don't know what manifest you're talking about, but that sounds like just the install manifest for the launcher. The `GameUserSettings.ini` *does* contain the login data, it's in the `RememberMe` section.

**Comment by kaaax0815** [comment]
I am talking about the manifest at `%programdata%\Epic\EpicGamesLauncher\Data`
