### ISSUE TITLE
Fetch game meta resources?

### ISSUE THREAD

**Issue by Kein** [derrod/legendary#174]
A somewhat sister request to the https://github.com/derrod/legendary/issues/5

Is it possible to add functionality fetch some meta-resources like game logo and thumbnails launcher also fetches and save them in some default structured format (logo_size.jpg, thumbail_120x240.jpg, etc) into game folder, for example, so any external tool can use them for something like new Win10 Start Menu Layout Icons (they allow arbitrary shaped big thumbnails).

**Comment by derrod** [comment]
External tools can read the metadata (in `~/.config/legendary/meta`) and go from there. Until a GUI necessitates downloading assets that will not be a part of this program.

**Comment by Kein** [comment]
That is a weak argument. This shouldnt be done by external tools, it is not the functionality they should offer, they only should wrap around what works with Epic data - legendary
If you start to delegate part of these responsibilities to external tools then might as well just write custom client instead of using this.
