### ISSUE TITLE
Fails to resume download. Legendary version 0.20.6

### ISSUE THREAD

**Issue by Galcian79** [derrod/legendary#178]
Yesterday i was downloading a game, it downloaded till 70%
Then i had to shutdown, so i closed it with CTR+C. It thrown out this message: `multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown`
So i did a `cleanup`, just in case. 
Today, when i resumed the download, it started from the beginning. Maybe i did something i shouldn't or it is a bug or EGS is failing in some ways?

**Comment by derrod** [comment]
Depends on the game, if the game has one large file containing all assets (e.g. Unreal. Engine's `.pak` files) then resuming can appear to not work correctly as it cannot resume in the middle of a file, but only skip files that have already been completely written.

**Comment by Galcian79** [comment]
> Depends on the game, if the game has one large file containing all assets (e.g. Unreal. Engine's `.pak` files) then resuming can appear to not work correctly as it cannot resume in the middle of a file, but only skip files that have already been completely written.

I think a .pak file of more than 15GB is unlikely to be though.

**Comment by derrod** [comment]
You should specify what game it is.

**Comment by Galcian79** [comment]
> You should specify what game it is.

It is Batman Arkham City.

**Comment by derrod** [comment]
I tested the game with multiple aborts and it seems fine. Maybe check if there's a file called `Egret.resume` in `~/.config/legendary/tmp`.

Also note that a download always starts at 0%, it's just 0% of the remaining 30% if that makes sense.

**Comment by Galcian79** [comment]
Ok for now seems running fine for me too. I just wanted to be sure i wasn't doing mistakes.
