### ISSUE TITLE
Issue when launching with wine64 on MacOS (Big Sur)

### ISSUE THREAD

**Issue by amaurosc** [derrod/legendary#179]
Hi, I'm getting a wine-related error when using `legendary launch 8e425d507bd6473dbb927f0fea8ef4f6 --wine wine64`:
```zsh
001f:err:display:macdrv_ChangeDisplaySettingsEx No matching mode found 1680x1050x32 @60!
0009:err:module:__wine_process_init L"Z:\\Users\\user\\legendary\\Torchlight2\\ModLauncher.exe" not supported on this system
```
I didn't find a solution on google so I was wondering if perhaps there was something I could do to fix this?
Thanks!

**Comment by derrod** [comment]
Torchlight 2 is a 32 bit only game, so you'd probably have to run it in a 32 bit wine prefix, but I can't help you further than that. Aside from macOS not being supported that's a WINE question so you'd be better be off asking that someplace dedicated to WINE support.
