### ISSUE TITLE
Consider supporting GOG Galaxy integrations

### ISSUE THREAD

**Issue by StefanLobbenmeier** [derrod/legendary#184]
I was wondering if you ever considered adding support to more platforms / other launchers. To be clear, I am not talking about supporting games bought in Epic Games that require another launcher (like #69) but also games bought in other launchers.

Alternatively, if anyone knows something like Legendary for other launchers, it would be nice if these launchers would feature legendary and legendary would feature them so you can easily find all the open source launcher projects.

**Comment by StefanLobbenmeier** [comment]
Potential list of other clients: https://github.com/Mixaill/awesome-gog-galaxy/blob/b38c189ec8976b4a2e337d030e9c763a81b9828f/README.md

**Comment by StefanLobbenmeier** [comment]
I guess what I am saying is that ideally this should be able to load the existing interface for GOG galaxy integrations. Changed title accordingly.

**Comment by StefanLobbenmeier** [comment]
This might actually be also a good solution for #129 when https://github.com/sharkwouter/minigalaxy can be used as the UI for this project

**Comment by derrod** [comment]
No, that goes way beyond the scope of an already hard to manage (time wise) project.

**Comment by StefanLobbenmeier** [comment]
Actually also just noticed this was a duplicate of #176, sorry
