### ISSUE TITLE
updating doesnt work

### ISSUE THREAD

**Issue by user4302** [derrod/legendary#187]
i updated fortnite. 
it was  a ~4 gb update. 
epic games wanted to re download the entire game(27 gb).
i updated the 4gb using LEGENDARY and tried to launch it but it said an update was required. opening epic games, it attempted to download the entire game again

**Comment by derrod** [comment]
There was no recent update for Fortnite so I don't know what to tell you. Switching between EGL and Legendary when EGL had already staged but not completed an update might cause problems. Run a repair (`legendary repair Fortnite --repair-and-update`) and see what happens.

**Comment by user4302** [comment]
its actually an old update from months ago :(.
no i waited till it finished before switching to EGL, egl was closed iirc.
i shall  try that command.
anyway im guessing its an issue on my end, since no one else has faced this issue in the issue list.

**Comment by derrod** [comment]
I assume this is a problem where both clients went out of sync. What you can try is after updating the game via legendary, remove the `.manifest` files in `C:\ProgramData\Epic\EpicGamesLauncher\Data\Manifests` that corresponds with Fortnite and clear the `Pending` directory as well, and then remove the `.egstore` folder in the Fortnite directory and try re-running `egl-sync`.

**Comment by user4302** [comment]
ill try that,
i tried running `legendary repair Fortnite --repair-and-update` like you asked
it resulted in wanting to download 33 gb :(.
anyway thank you, this solved the problem i think, i might have had a corrupted download.
