### ISSUE TITLE
Add --quiet/--silent and --noconfirm flags to download command

### ISSUE THREAD

**Issue by samedamci** [derrod/legendary#19]
Add flags for download without output (`--quite` or `--silent`) and confirmation (`--noconfirm`). This is good option for shell scripting with this client.

**Comment by derrod** [comment]
There already is the `-y` option that skips confirmation dialogs. I'll add a `-q`/`--quiet` option that sets the loglevel to `warning` later.

**Comment by samedamci** [comment]
Sorry, I'm blind and I don't seen `-y` option in newest version. Thanks.
