### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by lilcsz** [derrod/legendary#190]
![image](https://user-images.githubusercontent.com/43272857/103868729-555a3580-50da-11eb-96c86b.png)
![image](https://user-images.githubusercontent.com/43272857/103868770-62772480-50da-11eb-8e3a-413a2a1c1cdf.png)

**Comment by lilcsz** [comment]
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' static-assets-prod.epicgames.com static-assets-prod.unrealengine.com". Either the 'unsafe-inline' keyword, a hash ('sha256-4Su6mBWzEIFnH4pAGMOuaeBrstwJN4Z3pq/s1Kn4/KQ='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by derrod** [comment]
Try again, the

**Comment by lilcsz** [comment]
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' static-assets-prod.epicgames.com static-assets-prod.unrealengine.com". Either the 'unsafe-inline' keyword, a hash ('sha256-4Su6mBWzEIFnH4pAGM33ewawde213123123e12isitsafetosendmysha256key?wqsxwqdqweqweqwewqdBrstwJN4Z33n4/KQ='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by derrod** [comment]
What you're seeing there is the console output from Chromium which is - for some reason - being routed to your terminal. It has nothing to do with legendary. Just try again with your browser already running. But just pasting the SID into the terminal should also still work.

**Comment by CommandMC** [comment]
The browser log being printed into the terminal is normal, just paste in the sid and it'll still work (regardless of the browser being open or not)

**Comment by lilcsz** [comment]
> The browser log being printed into the terminal is normal, just paste in the sid and it'll still work (regardless of the browser being open or not)

Thanks.
