### ISSUE TITLE
[Suggestion] Use Proton-Caller instead system Wine

### ISSUE THREAD

**Issue by benjamimgois** [derrod/legendary#192]
[Proton-Caller](https://github.com/caverym/Proton-Caller) allows to run any windows program through steam-proton. Since proton has lots of features not avaiable in vanilla wine and is constantly developed and improved by valve, it would be interesting if legendary could make use it.

**Comment by derrod** [comment]
You can use whatever you want via the config. See how to use proton directly in the README. The steps are mostly the same for proton caller, you just have to set it as a wrapper and disable wine.
