### ISSUE TITLE
[Feature Request] Proton

### ISSUE THREAD

**Issue by Angell1993** [derrod/legendary#198]
Wine in itself is decent, but proton has quite a few special fixes that will boost fps and compatibility..

So please add proton in the same way you can use wine with legendary..

STEAM_COMPAT_DATA_PATH="[Proton Prefix]" "[Steam Folder]/steamapps/common/Proton 5.13/proton" run "[App path]"

Remember [Proton Prefix] & [Wine Prefix] are not compatible..
You can use a [Proton Prefix] from Wine but not the other way around..

This should give you an idea of how Proton is used..

**Comment by CommandMC** [comment]
See the Wiki on how to use Proton inside Legendary

**Comment by Angell1993** [comment]
Which wiki??

**Comment by Angell1993** [comment]
Found it.. And it looks quite easy..

**Comment by Angell1993** [comment]
Only issue I got is..
How do I set this variable in legendary config??
I can't figure out how to set this 'STEAM_COMPAT_DATA_PATH' variable in Legendary any ideas??


[Terminal Output]
Proton: No compat data path?

**Comment by CommandMC** [comment]
You can use the `[AppName.env]` section in the config file to set environment variables (of course replacing AppName with whatever game you're trying to run)

**Comment by Angell1993** [comment]
That worked, thank you..
