### ISSUE TITLE
Allow multiple --prefix/--exclude/--install-tag options

### ISSUE THREAD

**Issue by derrod** [derrod/legendary#20]
Currently only one can be specified, meaning that not all files can be included/excluded/selected in one command.

**Comment by EsdrasTarsis** [comment]
Legendary could create a wine prefix for each game installation with the app name.

**Comment by derrod** [comment]
This issue is about the download filters, not for WINE stuff.

**Comment by EsdrasTarsis** [comment]
Forgive me, I can create another Issue about that
