### ISSUE TITLE
Add macOS Support

### ISSUE THREAD

**Issue by iMonZ** [derrod/legendary#201]
The EpicGames Store games have native macOS support so why shouldn't port the Legendary launcher for macOS?

**Comment by derrod** [comment]
I don't have a mac, I have no interest in having a mac, and I have no interest in supporting macOS. So no.

**Comment by LukeVader-IV** [comment]
apparently the code mostly already works on MacOS, I think it would be worth it to leave this open and add the help wanted label, maybe also mentioning in the README that it mostly works on MacOS but is not actively supported.

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/246

**Comment by iMonZ** [comment]
> @derrod apparently the code mostly already works on MacOS, I think it would be worth it to leave this open and add the help wanted label, maybe also mentioning in the README that it mostly works on MacOS but is not actively supported.
> 
> [Heroic-Games-Launcher/HeroicGamesLauncher#246](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/246)

@derrod sounds like a good idea

**Comment by derrod** [comment]
With https://github.com/derrod/legendary/commit/1dfc5aabe71743d6b024646a0af9c62664cb56eb pretty much everything I want to support on macOS should be supported. Now it's just a matter of testing and bugfixing.
