### ISSUE TITLE
Origin linking/launching is not supported (Battlefront 2 not in games list)

### ISSUE THREAD

**Issue by legendofmiracles** [derrod/legendary#202]
So i just got star wars battlefront from the epic games store (the free version, on the store it's being displayed a owned) but when i run `legendary list-games` it isn't being shown.

Any ideas?

**Comment by CommandMC** [comment]
Same issue here. Strange

**Comment by Rajalolxd** [comment]
same

**Comment by Dummerle** [comment]
I have the same problem. It is not available in the official Launcher too, so I think it is a problem of Epic Games

**Comment by legendofmiracles** [comment]
@Dummerle my friend who uses the official one saw it

**Comment by Rajalolxd** [comment]
@Dummerle it shows up for me with the official Launcher with Wine, but I cant install origin

**Comment by CommandMC** [comment]
I think I found something: When looking at the store data with https://github.com/SD4RK/epicstore_api/, in the key `customAttributes`, there's an empty `com.epicgames.app.blacklist` key, which is not present on any other game I fetch with that API. I've only found this key on one other game: The Sinking City, which also is hidden on the epic games store after issues between the devs and publishers.

**Comment by CommandMC** [comment]
Now that's just speculation ofc, as it seems to appear fine on anything other than legendary. But maybe that's what's causing it to be hidden here?

**Comment by derrod** [comment]
Star Wars Battlefront is not downloadable or installable via the Epic Games Store. It doesn't have an asset and is therefore not listed in legendary. If you try to install it it launches the "EALink" executable from Origin with the following parameters:
`
"C:\Program Files (x86)\Origin\EALink.exe" "link2ea://launchgame/MtMassive?AUTH_PASSWORD=<exchange_code>&AUTH_TYPE=exchangecode&epicusername=<epic user name>&epicuserid=<epic user id>&epiclocale=en&theme=sws&platform=epic&Hotfix=go" "" "" "" "" "" "" "" ""
`
So after installing Origin via Lutris for example you might be able to use the `--dry-run` command for any installed game, then use the output of that to fill out the blanks here.

No idea if that'll work or if you can even launch the game after that, I don't know how Origin/Epic have implemented this.

**Comment by CourteousGeek** [comment]
I was able to install battlefront 2 with epic games launcher just fine.

**Comment by Rajalolxd** [comment]
@CourteousGeek wine or windows?

**Comment by CourteousGeek** [comment]
> @CourteousGeek wine or windows?

Windows

**Comment by CommandMC** [comment]
Welp, I don't have a GPU at the time that supports running just about anything (waiting for 3070s to get back in stock, stuck on a GT 730 at the time), so seems like others will get to try this one

**Comment by derrod** [comment]
So as an update; launching the game has to be done through the epic launcher, and it cannot be directly launched via Origin. Now there is no actual check for the Epic launcher to be running, so all you need to do is get an exchange code (via `--dry-run`) and then run:
`explorer "link2ea://launchgame/MtMassive?AUTH_PASSWORD=<exchange code>&AUTH_TYPE=exchangecode&epicusername=&epicuserid=&epiclocale=en&theme=sws&platform=epic&Hotfix=go"`
From a cmd within your Origin wine prefix (or just in your cmd/"Run" dialog on Windows) and the game will launch fine.

I don't have enough space to install this game on my Linux system (90 GB ugh) so if anybody can test that that would be great. Implementing a workaround for this doesn't seem too hard, it'll just require some manual steps (installing Origin, specifying the wine prefix etc.). Certainly less of a hassle than the UPlay linking...

**Comment by derrod** [comment]
Here's a quick guide that should help you link the account and get the game running on Linux and Windows: https://gist.github.com/derrod/333fb5218002347435b7f31d532cbd01

**Comment by stevel024** [comment]
> No idea if that'll work or if you can even launch the game after that, I don't know how Origin/Epic have implemented this. Buying an EA game via Steam for example will require both Origin and Steam to be running. I don't have enough free space right now to test if Star Wars will run without the Epic Store.

I can confirm that the game will not run without the Epic Launcher since it is tied to your Epic Games library. It tries to launch a com.epicgames.launcher link.

**Comment by Curve** [comment]
> Here's a quick guide that should help you link the account and get the game running on Linux and Windows: https://gist.github.com/derrod/333fb5218002347435b7f31d532cbd01

(Im on Linux)
After doing this the game (Battlefront II) shows up in origin and seems to be linked, but when pressing play nothing happens.
Has anyone else experienced this and knows how to fix it?

**Comment by Curve** [comment]
I followed the guide of the gist that was posted, it worked to some extent, the game started but left me with this:
![image](https://user-images.githubusercontent.com/37805707/105069534-62840680-5a82-11eb-9ec3-166969ea5a71.png)
Any ideas what causes this?

**Comment by legendofmiracles** [comment]
You should add the gist to the wiki - under game workarounds.

**Comment by derrod** [comment]
Done.

**Comment by legendofmiracles** [comment]
Feel free too close the issue, if anyone will have issues starting the game, they can comment under the gist.

**Comment by derrod** [comment]
It's still a valid issue. And I do have some ideas for how to build a more reasonable way of doing account linking (at least for Origin, Ubisoft is a different can of worms).

**Comment by legendofmiracles** [comment]
Great to hear. I'm struggeling a bit with setting it up.

**Comment by tiagogrunge** [comment]
I notice that GOG has the ability to read the star wars battlefront 2 as an epic game. Anyone know if their code is open? 
![image](https://user-images.githubusercontent.com/17025144/106983652-050bdd00-6745-11eb-9348-19c868fbe9e8.png)

**Comment by legendofmiracles** [comment]
Any update on this?

**Comment by derrod** [comment]
With 0.20.10 a new launch command option was introduced to allow for activating and launching Origin games, this will be improved further for the next Release, but I consider this issue closed for now.
