### ISSUE TITLE
GTAV bad performance

### ISSUE THREAD

**Issue by RobinSchapendonk** [derrod/legendary#208]
OS: Arch Linux

```
[GTAV_ID]
wrapper = "/home/robin/.steam/steam/steamapps/common/Proton 5.13/proton" run
no_wine = true

[GTAV_ID.env]
STEAM_COMPAT_DATA_PATH = /home/robin/Ganes/GTAV
```

GTA graphics settings: all lowest (https://www.noobs2pro.com/gta-v-settings/)
I have a laptop, but on windows, I can run GTAV fine on the lowest settings.

The walking arround is fine, but for example, when opening doors, etc.. I get a lot of lag.
Is there a way to fix this?

**Comment by derrod** [comment]
Not a legendary issue. For help with WINE configuration visit our Discord or other Linux gaming communities.

**Comment by CommandMC** [comment]
If your laptop has an integrated graphics and a dGPU, read up on https://wiki.archlinux.org/index.php/NVIDIA_Optimus to see how to switch between them. A thing to note though: I've heard plenty of stories where this will not work, as it's just not always supported

**Comment by RobinSchapendonk** [comment]
I always use optimus-manager to use my nvidia gpu

**Comment by rafamadriz** [comment]
> Not a legendary issue. For help with WINE configuration visit our Discord or other Linux gaming communities.

where's the discord link ? I can't find it anywhere.

**Comment by CommandMC** [comment]
https://discord.gg/UJKBwPw
It's, for example, right after the logo in the Readme
