### ISSUE TITLE
Borderlands 2 refuses to launch.

### ISSUE THREAD

**Issue by TheGreatHalva** [derrod/legendary#218]
When I launch BL2, it just outright refuses to do anything. 

Output on launching it:
```
xolagix@xolagix-X555LB:~$ legendary launch Dodo
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Dodo...
xolagix@xolagix-X555LB:~$ 
```

Config file:
```ini
[Legendary]

[Dodo]
wrapper = "/home/xolagix/.steam/root/compatibilitytools.d/Proton-5.9-GE-8-ST/proton" run
no_wine = true

[Dodo.env]
STEAM_COMPAT_DATA_PATH = /home/xolagix/ProtonPrefixes/Borderlands2
```
Running Linux 5.10.9 on ElementaryOS Hera. GPU is Nvidia 940m with propietary blob.

**Comment by derrod** [comment]
I believe the Borderlands game have some launcher that gets launched before the actual game that has been problematic with Wine. And the easiest fix is to rename the game's real .exe to the name of the launcher to skip that.

**Comment by TheGreatHalva** [comment]
Nope, not working. In fact, did this before opening this issue. If I don't do this - it throws a bunch of errors into the terminal.

**Comment by CommandMC** [comment]
You're running a somewhat outdated version of Proton-GE here, the latest one is 6.0 (the latest 5.x version being 5.22).

I own the game myself (must've been free at some point), so if I get the time I'll test it out

**Comment by TheGreatHalva** [comment]
Using 6.0 gives me this error:

```
xolagix@xolagix-X555LB:~$ legendary launch Dodo
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Dodo...
xolagix@xolagix-X555LB:~$ wine: could not load ntdll.so: /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/xolagix/.steam/root/compatibilitytools.d/Proton-6.0-GE-1/dist/lib//wine/ntdll.so)
```

Seems that Elementary OS Hera doesn't use glibc high enough to boot Proton 6.0, but that's up to Valve or Wine team.

**Comment by CommandMC** [comment]
All I can tell you is that Borderlands 2 works great for me. I've used the `-NoLauncher` flag to skip the launcher (didn't rename any .EXEs) and default Proton 5.13
