### ISSUE TITLE
not launching fornite giveing a error

### ISSUE THREAD

**Issue by BigBoiRossy** [derrod/legendary#225]
it doesnt laucnh fortnite for no apparent reason

## Platform
pc

Operating system and version:
Legendary version (`legendary -V`):
0.20.6
## Expected Behavior
it should launch fortnite normally 

## Current Behavior
it doesnt launch and gives a error

C:\Users\Neat>legendary launch Fortnite
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Fortnite...
Traceback (most recent call last):
  File "legendary\cli.py", line 1375, in <module>
  File "legendary\cli.py", line 1341, in main
  File "legendary\cli.py", line 512, in launch_game
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1307, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
[3472] Failed to execute script cli

## Steps to Reproduce
type this in CMD: legendary auth --delete
then AGAIN type: legendary auth
 and paste the SID without the quations 

1.
2.
3.
4.

**Comment by derrod** [comment]
It would appear that the executable is missing, possible your install path is incorrect. Check what `legendary.exe list-installed --show-dirs` says and what you get when running `legendary -v launch Fortnite`.

**Comment by imzerotwog** [comment]
![Screenshot_224](https://user-images.githubusercontent.com/78386113/106521897-b13b9280-64bd-11eb-8c0b-eb0be2e2e4c5.png)
![Screenshot_225](https://user-images.githubusercontent.com/78386113/106521987-cdd7ca80-64bd-11eb-918a-734298eb0f4d.png)

**Comment by imzerotwog** [comment]
help me my game is last updated

**Comment by BigBoiRossy** [comment]
> help me my game is last updated

Verify ur game on epic games laucher then do it again

**Comment by RealAceOfSpadesYT** [comment]
delete Legendary.exe and .config folder to fix issue

**Comment by RealAceOfSpadesYT** [comment]
then try again
