### ISSUE TITLE
Cities Skylines not launching

### ISSUE THREAD

**Issue by sadpanda2** [derrod/legendary#242]
## Platform
installed legendary using "git clone https://github.com/derrod/legendary.git"

Distributor ID: Linuxmint
Description:    Linux Mint 20.1
Release:        20.1
Codename:       ulyssa

legendary version "0.20.6", codename "A Red Letter Day"

## Expected Behavior
game should start

## Current Behavior
user@user:~/legendary$ legendary launch bcbc03d8812a44c18f41cf7d5f849265
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching bcbc03d8812a44c18f41cf7d5f849265...
user@user:~/legendary$ 002c:fixme:winediag:LdrInitializeThunk wine-staging 6.0 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0068:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0068:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0070:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0070:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0060:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0060:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
*******************************************************************************
* WARNING: Unknown option RADV_PERFTEST='aco'. ACO is enabled by default now. *
*******************************************************************************
*******************************************************************************
* WARNING: Unknown option RADV_PERFTEST='aco'. ACO is enabled by default now. *
*******************************************************************************
0104:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0104:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
010c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
010c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0104:fixme:process:SetProcessPriorityBoost (FFFFFFFFFFFFFFFF,1): stub
0124:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0124:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
012c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
012c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0134:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0134:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0104:fixme:server:invoke_system_apc syscall frame changed in APC function, frame (nil), saved_frame 0x31f708.

## Steps to Reproduce
I am trying to start the game with "user@user:~/legendary$ legendary launch bcbc03d8812a44c18f41cf7d5f849265"

## Additional information
The game starts without issues using wine (without legendary), but the DLCs are not recognized.

**Comment by CommandMC** [comment]
Try using Proton (guide on how to use it is in the [Wiki](https://github.com/derrod/legendary/wiki/Using-Proton)). If that doesn't help, it would be best to get onto the Discord server, we tend to solve Wine-related issues there and not here (as it isn't a Legendary issue)
