### ISSUE TITLE
PSO2 Support

### ISSUE THREAD

**Issue by ImportTaste** [derrod/legendary#243]
Phantasy Star Online 2 hit EGS today. SEGA included some very funky code that works in tandem with the EGS Launcher; so, it seems that it doesn't properly work when launched from legendary.

**Comment by Aida-Enna** [comment]
It does work with Legendary. It's being used as part of the PSO2 Tweaker.

**Comment by ImportTaste** [comment]
I must be doing something wrong, my mistake.

**Comment by derrod** [comment]
The game requires admin permissions to launch, so you'll have to run legendary from a cmd with admin permissions.

**Comment by soulpower11** [comment]
I ran Legendary with admin permissions and it doesnt seem to wanna launch the game

**Comment by Aida-Enna** [comment]
What is it doing, specifically?

**Comment by soulpower11** [comment]
Well, the legendary cmd open for a sec and close by itself when I enable run this program as admin, if not it just says that the game is not installed 

I check it with "legendary list-installed --check-updates" and it says that it is installed.
![explorer_2021-03-06_19-11-55](https://user-images.githubusercontent.com/5299979/110204780-e1f15c00-7eaf-11eb-9766-9a059ebae784.png)

**Comment by Aida-Enna** [comment]
Does the PSO2 logo show up along with a box in the top left corner? If so, it's PSO2's fault and not legendary's. If that's the case, head over to the PSO2 discord (http://discord.gg/PSO2) and drop your GameGuard files (pso2_bin/GameGuard/npgm.erl and pso2_bin/GameGuard/npgl.erl) into the #en-tech-support channel and the bot will parse it and tell you why it won't open.

**Comment by soulpower11** [comment]
Nope PSO2 doesnt show up

**Comment by soulpower11** [comment]
So I have been using the wrong app name, but after figuring out what the app name was and using that the game still doesnt start when I ran legendary as admin and 

this is what it show when it is not in admin 
![cmd_2021-03-06_23-21-12](https://user-images.githubusercontent.com/5299979/110211704-ca779a80-7ed2-11eb-9d4a-284b26e8192b.png)

**Comment by soulpower11** [comment]
I fixed the issue by repairing the installation through legendary and it works now
