### ISSUE TITLE
[Bug] Error downloading games

### ISSUE THREAD

**Issue by mobilegmYT** [derrod/legendary#244]
## Platform

Operating system and version: Raspbian Buster on Raspberry Pi
Legendary version (`legendary -V`): 0.20.6

## Expected Behavior

The app successfully downloads.

## Current Behavior

It exits with this error:
![image](https://user-images.githubusercontent.com/44128563/109258468-948e3400-77b7-11eb-9366-83fa7b9b1d9e.png)

## Steps to Reproduce

1. Compile/Install Python 3.8.5 on a Raspberry Pi
2. Remove /usr/bin/lsb_release so pip works
3. Install, then try downloading a game with legendary

**Comment by derrod** [comment]
Try decreasing the maximum amount of shared memory e.g. with `--max-shared-memory 512`. You're probably running 32 bit python and that really isn't supported.

**Comment by mobilegmYT** [comment]
I did that, and it's been stuck here for a while:
![image](https://user-images.githubusercontent.com/44128563/109330705-342fde80-7819-11eb-85e2-ed62972aa35b.png)
Is it supposed to be stuck here for 10 or 20 minutes?

**Comment by derrod** [comment]
No, but I couldn't tell you why that is. Maybe there are some other problems with python on ARM.

**Comment by mobilegmYT** [comment]
I canceled it, and seemed to be some more memory related issues. Could be because of either python 3.8 isn't supported on the RPI yet, or that I'm not running a 64-bit OS. I'll try both and see if it fixes anything.

**Comment by mobilegmYT** [comment]
Oh hey! Looks like it is just the newer python version being needed to fix the issues. I used a 64-bit container and did some apt switching to download the newer version of python in the bullseye repo. Games download fine now. I guess just either use the bullseye repo's python version or wait for it to be added to the repos.

**Comment by mobilegmYT** [comment]
After some tinkering, I managed to use `virturalenv` to make a python enviroment with a compiled 3.9 binary and legendary works flawlessly!

**Comment by VoQspu** [comment]
For anybody who finds this thread I ran into the same issue, if you don't want to tinker with different python versions, using `--max-shared-memory 256` doesn't stall on "starting download workers" and properly downloads the game (Python 3.8.10 on 32-bit Ubuntu Server ARM).
