### ISSUE TITLE
DOWNLOADING GAMES

### ISSUE THREAD

**Issue by lightningzword** [derrod/legendary#247]
I found this app on GitHub and loved it... since I dont like the heavy resource utilisation of Epic Games Launcher.... I read the whole GitHub page of yours to begin with and I tried installing Fortnite. Unfortunately I couldn't... it is showing "THE PAGING FILE IS TOO SMALL" Please help me as I am a beginner at coding and stuff.

**Comment by derrod** [comment]
Please fill out the issue template.
