### ISSUE TITLE
[Bug] Data folder not found

### ISSUE THREAD

**Issue by marc0l92** [derrod/legendary#248]
## Platform

Operating system and version: Kubuntu 20.10
Legendary version (`legendary -V`): legendary version "0.20.6", codename "A Red Letter Day"

## Expected Behavior

The command to launch a game:
`legendary launch Anemone`
starts the game.

## Current Behavior

The game starts with an error saying that is not able to find the game data.

I have this error for all games. Here some examples:
![legendary](https://user-images.githubusercontent.com/12623073/109432766-16c36600-7a0d-11eb-8c0f-0f51509f4262.png)

Apparently this is a default unity error that is generated when the data folder is not next to the executable, but also the games that are not developed with unity are not able to find the game files.

In the game folder there are all the games files but at game lunch they are not detected.

## Steps to Reproduce

1. `legendary auth`
2. `legendary install Anemone`
3. `legendary launch Anemone`

**Comment by derrod** [comment]
Cannot reproduce, it seems that for some reason the working directory is not getting set? That does not really appear to be a bug with legendary itself but maybe some other interference?
