### ISSUE TITLE
Change download location

### ISSUE THREAD

**Issue by kumarUjjawal** [derrod/legendary#249]
How can I change the download location?

**Comment by TheDcoder** [comment]
@derrod Any reason why it was closed with no explanation? I searched for a way to change the download location but it looks like that is not configurable at the moment.

This is a problem for big games as I don't have enough space on my root partition (it's a small SSD), I prefer downloading games to my larger hard disk which has plenty of space.

**Comment by derrod** [comment]
It is configurable. Read the README:

https://github.com/derrod/legendary#config-file

**Comment by TheDcoder** [comment]
@derrod Are you referring to `install_dir`? I already change it, perhaps the free space check function doesn't understand that the path is on a different partition :thinking:

**Comment by TheDcoder** [comment]
I just confirmed my theory, the game does get downloaded to `install_dir` but the free space warning is still present due to buggy detection.
