### ISSUE TITLE
small typo when importing games

### ISSUE THREAD

**Issue by hackaholic5069** [derrod/legendary#250]
E:\EpicLibrary\Legendary>legendary import-game bcbc03d8812a44c18f41cf7d5f849265 ./../CitiesSkylines
[Core] INFO: Trying to re-use existing login session...
[Core] INFO: Found EGL install metadata, verifying...
[cli] INFO: Game install appears to be complete.
[cli] INFO: Installation had Epic Games Launcher metadata for version "1.13.2-f1-e14", verification will not be requried.
"requried" should be "required"

**Comment by LukeVader-IV** [comment]
seems like you're on an outdated version as it was fixed in January

https://github.com/derrod/legendary/pull/175/commits/2630c169be9379332e6b71b573b37f2e8a6b874c

**Comment by derrod** [comment]
https://github.com/derrod/legendary/commit/2630c169be9379332e6b71b573b37f2e8a6b874c

**Comment by hackaholic5069** [comment]
@derrod, i used the last release from the releases page- which was put up on the 20th of december
