### ISSUE TITLE
-silent flag to allow for shortcuts that don't open a cmd window while it launches

### ISSUE THREAD

**Issue by hackaholic5069** [derrod/legendary#251]
if i make a shortcut to launch a game through Legendary, it will open a terminal window and print some things while it opens. i would like the ability to "silence" legendary through a flag to keep this window from popping up

**Comment by CommandMC** [comment]
The terminal window will pop up regardless of there being a flag or not. To have it minimized, open the Shortcut Properties and change the "Run" option to "Minimized"

**Comment by hackaholic5069** [comment]
thanks for letting me know i can do that, wasn't aware that i could control how the cmd window opened
