### ISSUE TITLE
Cant choose folder for installation

### ISSUE THREAD

**Issue by gituser823** [derrod/legendary#252]
## Platform

Operating system and version: Linux Mint 20 Ulyana
Legendary version (`legendary -V`): legendary version "0.20.6", codename "A Red Letter Day"

## Expected Behavior
When I choose a Installation path it should let me do so.

## Current Behavior
I choose a folder and it enters that folder and then wont let me choose it. (Is it maybe expecting a file?)

## Steps to Reproduce
1. Try to install a game
2. It open the folderselectiontool
![legendary](https://user-images.githubusercontent.com/32219087/110223830-eda44900-7ed6-11eb-860d-b37613fd2545.gif)

3. No folder can be selected in the end.

## Additional information
Using Cinnamon Desktop.

**Comment by CommandMC** [comment]
That's a Heroic issue, ask them for help: https://github.com/flavioislima/HeroicGamesLauncher
