### ISSUE TITLE
[Feature request] Display if a game is 32-bit or 64-bit when list-games is run

### ISSUE THREAD

**Issue by mobilegmYT** [derrod/legendary#253]
**Is your feature request related to a problem? Please describe.**
I recently got legendary working on ARM thanks to some *container magic*. Issue is that only 32-bit games run with box86 currently, and with a ton of games in my library (100 or so) it's hard to know which ones have the possibility of working and which ones will just fail since it's 64-bit after spending half an hour installing it.

**Describe the solution you'd like**
A little extra thing that shows up when list-games is run beside each game that says x86 or x86_64

**Describe alternatives you've considered**
There aren't really alternatives to this request.

**Comment by derrod** [comment]
There's no real way of doing that, Epic technically provides the "Win32" platform separate from the default "Windows" one for 32 bit only apps, but whether developers actually use that I don't know (you can use `--platform Win32` with `list-games`/`download`).

Either way 32 bit OSes or weird niche use cases like running games in x86 emulation is not something legendary will support.

**Comment by mobilegmYT** [comment]
> There's no real way of doing that, Epic technically provides the "Win32" platform separate from the default "Windows" one for 32 bit only apps, but whether developers actually use that I don't know (you can use `--platform Win32` with `list-games`/`download`).
> 
> Either way 32 bit OSes or weird niche use cases like running games in x86 emulation is not something legendary will support.

Ah ok, tried out the flag and it seemed to work. In that case, would it be possible for you to maybe add an extra flag to config.ini to configure all commands to only search for a specific arch of game, like for example configure it to only list and install Win32 or Linux 32 and so on.
