### ISSUE TITLE
[Feature request] Add a flag to install all the DLCs without prompt

### ISSUE THREAD

**Issue by mirucon** [derrod/legendary#257]
**Is your feature request related to a problem? Please describe.**
it's a little bit frustrating I need to enter "y" every time I want to install the DLCs since I never chose not to install the DLCs.

**Describe the solution you'd like**
Add a flag like `--with-dlcs` to the `install` command so I don't have to hit "y" and enter every time.

**Comment by MagicMark88** [comment]
[INSTALL_0000_0dc1a1ce-5dfb-4784-b34b-4af6501eb05a.txt](https://github.com/derrod/legendary/files/6236758/INSTALL_0000_0dc1a1ce-5dfb-4784-b34b-4af6501eb05a.txt)

**Comment by nutterthanos** [comment]
maybe do it like with the selective downloads with fortnite

**Comment by FarDust** [comment]
maybe do it like in choco, and add an option to say yes to `all` using `A`

**Comment by ZerominerBR** [comment]
I think it would be great if you were asked at the beginning of the game download itself, if you want to download all the DLCs.

**Comment by derrod** [comment]
Closed in ff29b949cb1c132b1cb2ae7c819a0da3eea3ddda
