### ISSUE TITLE
Legendary can access to game list but reports none installed

### ISSUE THREAD

**Issue by djey47** [derrod/legendary#268]
## Platform
Operating system and version: Windows 10 20H2, build 19042.928
Legendary version (`legendary -V`): `legendary version "0.20.6", codename "A Red Letter Day"`
Commands issued by either MSYSGIT or Powershell, same results

## Expected Behavior
`list-installed` command should display list of installed titles

## Current Behavior
`list-installed` command outputs the following;

```
Installed games:

Total: 0
```

## Steps to Reproduce
1. Authenticate (first time)
2. Execute command `legendary list-installed`

## Additional information
`list-games` command provides exhaustive list of all items in my epic account

```
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Getting game list... (this may take a while)

Available games:
 * Absolute Drift (App name: 19927295d6e3467887d4e830d8c85963 | Version: Win_202103040957)
 * Blair Witch (App name: 247a0f0f5803429eb3be2c06f3ea77ff | Version: BLAIR_WIN_SRC_20191209_1642)
 * Crayta (App name: a0a49d82e3f64c1b81873397a6e92f09 | Version: 0.6.158.101395)
 * Dungeons 3 (App name: 351fe5b32e22412d8fa41f4c7395fed1 | Version: v1.7 build13 @c33954b v11)
 * Elite Dangerous (App name: 9c203b6ed35846e8a4a9ff1e314f6593 | Version: 3.7.11.254828 (0.4.6699.0))
 * Galactic Civilizations III (App name: 5f1c66366b2c4a6496d535d88c56e6cf | Version: 4.1.23147)
 * Galactic Civilizations III (Test branch) (App name: 8931f79300d04c5889799bffc8ef70bd | Version: 4.1.23147)
 * Ghostbusters The Video Game Remastered (App name: Mint | Version: retail10)
 * Grand Theft Auto V (App name: 9d2d0eb64d5c44529cece33fe2a46482 | Version: 1.0.2245.0)
```

`launch` command reports the game is not installed, although it is and runs well via Epic UI.

```
[cli] ERROR: Game 9d2d0eb64d5c44529cece33fe2a46482 is not currently installed!
```

**Comment by CommandMC** [comment]
No games were installed by Legendary yet. To import games from the Epic Games Launcher, run `legendary egl-sync` or, if you're not planning on using the Epic Games Launcher again, use `legendary import` to import the games directly

**Comment by djey47** [comment]
Works like a charm thanks! Sorry for the false bug !
