### ISSUE TITLE
Permissions not working

### ISSUE THREAD

**Issue by Voidwalker60** [derrod/legendary#274]
I followed This guide [https://github.com/derrod/legendary/issues/76](url) to launch elite dangerous and it throws the error "permission denied" even though the proton folders are set for everyone to edit

Terminal log:
`[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching 9c203b6ed35846e8a4a9ff1e314f6593...
Traceback (most recent call last):
  File "/usr/bin/legendary", line 33, in <module>
    sys.exit(load_entry_point('legendary-gl==0.20.6', 'console_scripts', 'legendary')())
  File "/usr/lib/python3.9/site-packages/legendary/cli.py", line 1340, in main
    cli.launch_game(args, extra)
  File "/usr/lib/python3.9/site-packages/legendary/cli.py", line 511, in launch_game
    subprocess.Popen(params, cwd=cwd, env=env)
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/Voidwalker604/.local/share/Steam/steamapps/common/Proton 6.3/'
`

Config file
`[Legendary]

[9c203b6ed35846e8a4a9ff1e314f6593]
wrapper = "/home/Voidwalker604/.local/share/Steam/steamapps/common/Proton 6.3/" run
no_wine = true

[9c203b6ed35846e8a4a9ff1e314f6593.env]
STEAM_COMPAT_DATA_PATH = "/home/Voidwalker604/Desktop"
`

**Comment by CommandMC** [comment]
You're missing a `proton`after the wrapper path, it should be
`"/home/Voidwalker604/.local/share/Steam/steamapps/common/Proton 6.3/proton" run`

**Comment by Voidwalker60** [comment]
Thanks
