### ISSUE TITLE
Systemwide performance drop when launching game via Legendary without having EGS launched via Lutris beforehand

### ISSUE THREAD

**Issue by fridge-art** [derrod/legendary#277]
## Platform
Operating system and version: 5.10.36-2-MANJARO
Legendary version: 0.20.6

## Expected Behavior
Launch and play game without systemwide performance drop

## Current Behavior
If i perform a clean system boot, and Launch Football Manager 2020 via Legendary, it does start the game as expected but with heavy performance issues. FPS maybe 5-10. At this stage it is systemwide, in and outside of the game. Moving the cursor is like dragging it through syrup. In web browser and OS browsing. If i exit the game, the system returns back to normal performance. Cpu usage 90+% from fm.exe.

If i first launch Lutris, then launch EGS and then launch Football Manager 2020 via Legendary, the issue is nowhere to be seen and performance is good in and outside of the game.

## Steps to Reproduce
1. Boot computer
2. Launch Football Manager 2020
3. Systemwide performance drop
4. Exit the game
5. Launch Lutris
6. Launch EGS via Lutris
7. Launch Football Manager 2020 via Legendary
8. No performance drop

Open to provide any logs on request. I see no obvious error in terminal. First filed this bug report on HGL because i first discovered it there but since its reproducable via Legendary i was advised to post here

**Comment by derrod** [comment]
Yeah no idea, that's some stupid Linux shit. If anybody has a solution feel free to add it, but this isn't an issue with legendary itself.

**Comment by CommandMC** [comment]
Legendary's not the cause at all here. @fridge-art is probably using their default Wine prefix & version with Legendary while using a custom prefix / version, probably with DXVK installed, when using Lutris

**Comment by CommandMC** [comment]
I'll take a look at Football Manager 2020 myself and see if it needs anything specific installed

**Comment by adityaruplaha** [comment]
Original issue: Heroic-Games-Launcher/HeroicGamesLauncher#377.

**Comment by CommandMC** [comment]
To confirm, what install script did you use when installing the game using Lutris? Just the general [Epic Games one](https://lutris.net/games/epic-games-store/)? Because I can't find one specifically for FM 2020

**Comment by fridge-art** [comment]
I used the standard for installing EGS in Lutris, and i installed FM2020 in HGL with standard there too. I dont have the game installed in EGS

**Comment by CommandMC** [comment]
Installing DXVK is definitely recommended here, otherwise the 3D scenes will not work.

But still, works fine for me, both with and without DXVK installed (CPU usage at ~5%, ~1 GB more RAM used). Seems to crash at startup sometimes, but once you're in the game it works fine as far as I can tell (opened up the "Career" option and pressed some random buttons, don't know anything about the game)

**Comment by CommandMC** [comment]
Actually, the crashes can be circumvented by running `winetricks nocrashdialog`. Seems like it's just some background process that's crashing or something
