### ISSUE TITLE
legendary says download size is higher than what it downloads.

### ISSUE THREAD

**Issue by nutterthanos** [derrod/legendary#278]
this file proves this don't worry about most of the file just look at download size and near the bottom of the file where it says downloaded and i'll put in a pic for the file.
[version8.50toversion8.51_delta.txt](https://github.com/derrod/legendary/files/6529083/version8.50toversion8.51_delta.txt)
![image](https://user-images.githubusercontent.com/50470661/119280016-6c0abe80-bc6e-11eb-906f-cf57e3a17804.png)
![image](https://user-images.githubusercontent.com/50470661/119280023-79c04400-bc6e-11eb-8fc5-7140f3c455e8.png)

**Comment by derrod** [comment]
Probably a side-effect of the manifest merge not checking if a chunk is already in the original manifest, resulting in chunks being counted more than once and thus resulting in a larger download size than what it actually is.

If you can provide me with the manifests used here, I can check that.

**Comment by nutterthanos** [comment]
> Probably a side-effect of the manifest merge not checking if a chunk is already in the original manifest, resulting in chunks being counted more than once and thus resulting in a larger download size than what it actually is.
> 
> If you can provide me with the manifests used here, I can check that.

which ones?

**Comment by derrod** [comment]
All three.

**Comment by nutterthanos** [comment]
would it matter if i provide an older manifest?

**Comment by nutterthanos** [comment]
also github is playing up can't upload here

**Comment by nutterthanos** [comment]
https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/BJqXmVW32yHN2EDJlkiwUn0CyZDm1g.manifest
https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/wcfjh9c-okLtEOiDMkG8VzIC1p-ENg.manifest
https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/5-0v4B3kpK4XpRczak2Pc7dtlqah1A.manifest

**Comment by nutterthanos** [comment]
or the whole lot https://github.com/VastBlast/FortniteManifestArchive

**Comment by nutterthanos** [comment]
> All three.
this
https://github.com/derrod/legendary/issues/278#issuecomment-846955825
