### ISSUE TITLE
Close/Save config file before starting download

### ISSUE THREAD

**Issue by CommandMC** [derrod/legendary#279]
**Is your feature request related to a problem? Please describe.**

Kinda. When installing a game, I let the download process run in the background. While doing that, I'm already setting up a new Wine prefix, adding environment variables to the config, stuff like that. Once the game finishes downloading, all these values I set are overwritten, since the "old" config gets written out once the install_game function finishes (by the `self.core.exit()` at the end of cli's `main()`).

**Describe the solution you'd like**

The cleanest way I could think about is adding an `exitted` bool to the config and calling `core.exit` before starting the download (~ line 669 in the cli), but I haven't read through all of the code yet so I don't know if this would introduce other problems.

**Describe alternatives you've considered**

Alternatively, one could read the config in again after the download is finished, to make it essentially save over itself. I don't think that would introduce too many issues, as the whole CLI exits right after finishing the download anyways, but it's more disk usage for essentially no reason.

**Comment by derrod** [comment]
One of the changes on the ToDo list is to only write the config when it has actually been changed, and to possibly also check if it was modified externally before saving and showing the user a warning.
