### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by m0rphtail** [derrod/legendary#282]
## Platform

Operating system and version: Arch Linux
Legendary version (`legendary -V`): 0.20.6

## Expected Behavior
It should login

## Current Behavior
Does not login after entering the SID
![image](https://user-images.githubusercontent.com/47940274/121031797-4f22cf00-c7c8-11eb-8328-476a6566871a.png)

## Steps to Reproduce

1. Enter `legendary auth` in the terminal
2. Copy the SID from the browser
3. Paste the SID

## Additional information 

Python version 3.9.5

**Comment by adityaruplaha** [comment]
I think you double pressed enter by mistake, it doesn't seem to be blocking on input.

**Comment by nutterthanos** [comment]
Have you tried --verbose ig legendary --verbose auth? @m0rphtail

**Comment by lokillo999** [comment]
![image](https://user-images.githubusercontent.com/19214569/125186828-c4c7f380-e1e9-11eb-993d-057f34359265.png)
this is what appears to me

**Comment by m0rphtail** [comment]
> Have you tried --verbose ig legendary --verbose auth?
> So we can obtain more info on why this is happening
> @m0rphtail

didn't try that, 
actually I installed epic games from lutris last week

**Comment by nutterthanos** [comment]
> ![image](https://user-images.githubusercontent.com/19214569/125186828-c4c7f380-e1e9-11eb-993d-057f34359265.png)
> this is what appears to me

Looks like proxy is stopping legendary from working by the looks of things I have had this error before with an proxy so yeah
