### ISSUE TITLE
[Feature request] Portable mode

### ISSUE THREAD

**Issue by Hypnoticbat9555** [derrod/legendary#287]
Could you maybe add a portable mode to the launcher. So that it saves the config files in the folder the executable is located in. I would find it very useful for games that can't be run offline.

**Comment by derrod** [comment]
You can override the location used for the configuration directory with the `XDG_CONFIG_HOME` environmental variable. You can set it via a script before running legendary.

I probably won't add any portable mode otherwise.

**Comment by dragonDScript** [comment]
This is only for Linux. And that is great, most legendary users use linux. But some use Windows, and this variable is not available on Windows.

(We use legendary on Heroic for Windows, for example).

**Comment by CommandMC** [comment]
Legendary uses `os.environ.get` to get that variable. This also works on Windows, where you can set the variable like this:
```bat
set XDG_CONFIG_HOME=X:\path\to\config\dir
legendary
```

**Comment by dragonDScript** [comment]
> Legendary uses `os.environ.get` to get that variable. This also works on Windows, where you can set the variable like this:
> 
> ```batchfile
> set XDG_CONFIG_HOME=X:\path\to\config\dir
> legendary
> ```

Oh, I thought that it was a Linux or X11 thing. Thank you, that will work.
