### ISSUE TITLE
game launches now launches in window, not full screen

### ISSUE THREAD

**Issue by jarss** [derrod/legendary#288]
Hi, 

I used legendary to install and run a game, Phoenix Point. 
On first install and run, the game launched to full screen and I was able to play. I hit Esc for a break. When I returned, the game was not responding and the system was unstable. I tried to shut down specifically the application (Phoenix Point) but no success. OK, I hard booted the machine... 

When I logged back in and tried to launch the game again, it launched into a window instead of full screen. I couldn't maximize. I noticed I couldn't press any keys (for example, to skip the intro), the game doesn't seem to respond to keys and mouse. 

It looks like something got screwed up in the hard-boot. I deleted the game library and uninstalled from Legendary, but it doesn't help, reinstalling the game still launches it to window. 

Is there a location with configs that are saved and are stuck somewhere? Is there a way to fully reset legendary perhaps, for this game? I think that might fix the issue.

**Comment by CommandMC** [comment]
Please fill out the issue template! We really can't help you much if you don't

Other than that:
Legendary doesn't store any game settings, it's up to the game to do that (and there's no way for Legendary to know where a game stores its settings).

If you're on Linux, Wine's "Virtual Desktop" feature might help with this particular issue

**Comment by derrod** [comment]
Legendary's config is in `.config/legendary`, if you do not know where that is you probably haven't modified it in any way that would be relevant here.

This bug tracker is also specifically not for issues with games and WINE that are unrelated to legendary itself.

**Comment by jarss** [comment]
@derrod I did play with the config, but only for the install location: 
[Legendary]
install_dir = /path/to/game/dir

There's another config for "ed93b18355a84230938c705121c63661" which I assume is a specific game, but I'm not sure (don't remember) which one is that, and it tells it to run a specific wine_executable. The Phoenix point game is "Iris" so it's not that one. 

@CommandMC I mostly use Lutris, which allows me to play with the virtual desktop feature you mention... I'll see if I can do it here. Otherwise I'm not sure how to use it with wine, bull I'll read and find the command. 

thanks for the help :)
