### ISSUE TITLE
'Game is out of date' for Hitman 3 on Windows / can't update 

### ISSUE THREAD

**Issue by kettenbruch** [derrod/legendary#291]
## Platform

Operating system and version: `Windows 10 21h1 x64`
Legendary version (`legendary -V`): `"0.20.6", codename "A Red Letter Day"`

## Expected Behavior
```
 .\legendary.exe launch Eider 
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Eider...
```
## Current Behavior
```
PS C:\Users\user\.config\legendary> .\legendary.exe launch Eider
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[cli] ERROR: Game is out of date, please update or launch with update check skipping!
```
When trying to update:
```
PS> .\legendary.exe update Eider
[cli] INFO: Game needs to be verified before updating, switching to repair mode...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Game has not been verified yet.
Verify "Eider" now ("no" will abort repair)? [Y/n]: Y
[cli] INFO: Loading installed manifest for "Eider"
[cli] INFO: Verifying "HITMAN 3" version "4763566"
Verification progress: 118/118 (100.0%)
[cli] INFO: Verification finished successfully.
[cli] INFO: Preparing download...
[Core] INFO: Parsing game manifest...
[Core] INFO: Install path: X:\games\HITMAN3
[DLM] INFO: Found previously interrupted download. Download will be resumed if possible.
[DLM] INFO: Skipping 118 files based on resume data.
[cli] INFO: Download size is 0, the game is either already up to date or has not changed. Exiting...
```
Repeats behavior when trying to launch after "updating"
 
## Steps to Reproduce

1. .\legendary.exe update Eider
2. .\legendary.exe launch Eider

## Additional information

Tried it on heroic on a linux machine, (heroic uses the legendary backend), no notification about updates on linux 

in C:\Users\user\.config\legendary\manifests there are two manifests for Eider: `Eider_4763566.manifest` and `Eider_4879673.manifest`. 
Why doesn't it update from 4763566 to 4879673 if there is a manifest ? 
In-game authentication succeeds but recent content is broken ('content not found') which indicates that legendary is unable to update the game.

**Comment by derrod** [comment]
Seems like there's a scenario where updating can get stuck in repair mode. Try running the command with the `--repair-and-update` flag.

**Comment by kettenbruch** [comment]
`--repair-and-update` worked, thanks a lot !
