### ISSUE TITLE
manifests generated by legendary arent showing games as installed by epic anymore

### ISSUE THREAD

**Issue by hackaholic5069** [derrod/legendary#296]
## Platform

Operating system and version:
Legendary version (`legendary -V`):

## Steps to Reproduce

1.
2.
3.
4.

**Comment by derrod** [comment]
Please fill out the issue template. As of now this is in invalid issue and will be closed. Should you update it with a valid description and the issue is confirmed I will reopen.

**Comment by hackaholic5069** [comment]
sorry, hit enter while typing out the title on accident

**Comment by derrod** [comment]
Can't reproduce. Have you restarted the Epic launcher? Make sure you completely exited it (i.e. it's not running in the background/minimised).

**Comment by hackaholic5069** [comment]
yep, have been experiencing this issue for the last month or so. i could upload one of the manifests made by legendary if you want

**Comment by hackaholic5069** [comment]
edit: i looked at one and i think i know what the issue was. i was using relative paths when installing, so epic looks at "..\\HellisOtherDemons", decides it doesnt exist, and doesnt list it

**Comment by derrod** [comment]
Yes the epic launcher does not list games if the path does not exist. Legendary doesn't support relative paths (it just doesn't check for that either) so that won't work.

**Comment by hackaholic5069** [comment]
it sort of works- if legendary has a specific working directory relative paths work fine

**Comment by hackaholic5069** [comment]
i'll make a note to not use relative paths though, is there a convenient way to change the existing paths of games, or am i just going to have to "uninstall" all of my games and readd them

**Comment by derrod** [comment]
Edit the `installed.json` file in the config directory and replace the relative paths with absolute ones. However you will have to re-export them which may require you to manually delete the manifests in the Epic Launcher folder so it recreates them with the correct paths.

**Comment by hackaholic5069** [comment]
alr
question unrelated to this issue, how hard would it be to make a python script that piggybacks on your code? considering making a crappy program to make launching/managing games through the command line more convenient, and im hoping i dont need to deal with regex

**Comment by derrod** [comment]
Look at `cli.py` for most of that.
