### ISSUE TITLE
[Feature request] Language setting for launching games

### ISSUE THREAD

**Issue by EisigesEis** [derrod/legendary#302]
Games like Dauntless do not have an intern language setting. They adopt the language that is set in the Epic Games Launcher. I have my Epic Games Launcher set to English however once I launch Dauntless with legendary it will launch a German version.

I would like a language setting similar to how it is in the Epic Games Launcher which games like Dauntless will adopt when launching.

This is not as big of an issue as German is my mother language though the translations in the game can become confusing when communicating with English speaking players which is why I usually like to run Dauntless on English.

**Comment by derrod** [comment]
There is the `locale` [config option](https://github.com/derrod/legendary#config-file) or `--language` launch parameter.

**Comment by EisigesEis** [comment]
I see. Thank you very much for your quick answer!
