### ISSUE TITLE
Play time is not sync

### ISSUE THREAD

**Issue by phammanhhiep** [derrod/legendary#309]
I played borderlands 2, and the play time was not recorded. After legendary was synced with the official Epic game launcher, the play time is still the time I played using the official Epic Game launcher.

Operating system and version: Windows 10
Legendary version: master

**Comment by Flonky** [comment]
Currently only save games get synced and not the playtime time.

**Comment by phammanhhiep** [comment]
@Flonky Is it the current limitation of legendary or Epic Game API?

**Comment by Flonky** [comment]
Im not sure.
Im sure @derrod can tell you more^^

**Comment by nutterthanos** [comment]
> @Flonky Is it the current limitation of legendary or Epic Game API?

play time is done by request to xmpp

**Comment by JFMugen** [comment]
> play time is done by request to xmpp
> but to grab current play time for game request is sent to library-service

What does that mean :D

**Comment by nutterthanos** [comment]
> > play time is done by request to xmpp
> > but to grab current play time for game request is sent to library-service
> 
> What does that mean :D

uh idk

**Comment by derrod** [comment]
Play time syncing likely won't be supported until an official GUI is avialable that will continue running even if the game is launched. RIght now it's simply not possible to track this.

**Comment by JFMugen** [comment]
> Play time syncing likely won't be supported until an official GUI is avialable that will continue running even if the game is launched. RIght now it's simply not possible to track this.

I don't know how hard to implement it, but maybe it can be added for not official ones like Heroic? Some kind of collab for testing etc?

**Comment by derrod** [comment]
Maybe, I don't know the necessary APIs. Heroic could implement them directly and get the auth token from legendary. I'll have to investigate.

**Comment by JFMugen** [comment]
> Maybe, I don't know the necessary APIs. Heroic could implement them directly and get the auth token from legendary. I'll have to investigate.

I remember talking about it (on discord if I am right) and if I didn't understand wrong, Heroic is basically GUI of Legendary so the app can't do anything that legendary can't. Overall I have no idea about technical side of things tho, so I am just talking about what I know here :D

**Comment by nutterthanos** [comment]
EGL3 could do it
