### ISSUE TITLE
Portable configuration

### ISSUE THREAD

**Issue by dragonDScript** [derrod/legendary#310]
**Is your feature request related to a problem? Please describe.**
We are using legendary for our app. Our app is portable, but legendary isn't.

**Describe the solution you'd like**
It would be great to implement a portable configuration, e.g. with a flag when calling legendary.

**Describe alternatives you've considered**
None

**Additional context**
See https://portableapps.com/

**Comment by CommandMC** [comment]
Duplicate of #287
