### ISSUE TITLE
Uninstall a game from official epic game launcher, but Legendary still says the game is install 

### ISSUE THREAD

**Issue by phammanhhiep** [derrod/legendary#311]
I uninstalled a game from epic game launcher, but `legendary egl-sync` still requested to export the game to epic game launcher. `legendary list-installed` also showed the game. 

Operating system and version: Windows 10
Legendary version: master

**Comment by nutterthanos** [comment]
isn't legendary supposed to check if said game is even installed with the manifests stored in %programdata%?

**Comment by woctezuma** [comment]
It is possible that the official launcher and legendary do not share the same folder for game installations.

That is why there is an `import-game` command, so that you can import games without downloading them again.

**Comment by derrod** [comment]
Legendary generally doesn't do destructive operations without user input. There is no really good way of knowing that EGL uninstalled the game, it could just be on a disk that is currently missing. Therefore manually uninstalling is still required (and is now fixed).
