### ISSUE TITLE
Legendary fails to launch games

### ISSUE THREAD

**Issue by IamRel** [derrod/legendary#312]
When I run Into The Breach with legendary, it shows the error, 

`i965: Failed to submit batchbuffer: Invalid argument` 

I'm not sure if it happens with any other games, I haven't tried, but I'm not sure what about my graphics could be causing this, I have hardware acceleration on and opengl is on version 3.0. I am running this inside of crouton on a chromebook, but that doesn't prevent hardware acceleration from what I know.

**Comment by derrod** [comment]
This is an error occuring after legendary has terminated, likely due to the intel iGPU not supporting some feature. It is not a legendary issue.
