### ISSUE TITLE
[BUG] Legendary includes entire game size in disk space for update

### ISSUE THREAD

**Issue by wiryfuture** [derrod/legendary#317]
Legendary uses the total game disk space for disk space requires when updating a game, making it impossible to update a game without having double the necessary disk space or passing ``--ignore-free-space``

## Platform
Operating system and version: Fedora 34, afaik also present in windows 10 and 11. 
Legendary version: all recent ver?

## Expected Behavior
When you want to update a game, it the disk space required should be the total that will be used in addition to the current space. Ex: A patch is 100MB, so disk space required should be 100MB, as that is how much in needed. This much is available so it should update (as below but without ``--ignore-free-space``).
![Screenshot_20210819_223043](https://user-images.githubusercontent.com/50517631/130146983-0714994c-4af3-4a0c-aa41-8b79019b275c.png)

## Current Behavior
Legendary included the whole game in the install size for patches/updates. This is unoticeable until you have less than double the size of a game and you need to update it. This means that it is impossible to update without passing command line argument, which is especially bad when using a GUI that tries to use legendary.
![Screenshot_20210819_221233](https://user-images.githubusercontent.com/50517631/130146878-1cceaaba-f583-4c1f-84fa-3e83418840f2.png)

## Steps to Reproduce
1. Have a large game which is not the most recent version, example, GTAV, on a disk which doesn't have enough capacity to install it twice.
2. Try to update the game using ``legendary update``
3. Get denied the update by legendary because you don't have enough space?

**Comment by derrod** [comment]
Fixed in bb3d6f9348f17a14677fd45319e5c07bde89ab2b
