### ISSUE TITLE
Better UX - App names

### ISSUE THREAD

**Issue by YellowOnion** [derrod/legendary#319]
**Is your feature request related to a problem? Please describe.**

Most if not all the games in my library have "App names" as unmemorable strings of base64, probably sha hashes.

**Describe the solution you'd like**

Some way to launch a game off the _actual_ name, i.e. automatically (i.e. search for strings and if it's unique then use that game)

```
legendary import-game "Grand Theft Auto V" ~/dir
````

**Describe alternatives you've considered**

some way to manually alias names.

**Additional context**

**Comment by derrod** [comment]
I believe addresses this  0d8b74a9e07e805b973920c8cd91957fc0ca1ee7 this sufficiently, plus 0.20.11 already features manual aliasing.
