### ISSUE TITLE
Add a protocol for legendary

### ISSUE THREAD

**Issue by aitor-gomila** [derrod/legendary#323]
**Is your feature request related to a problem? Please describe.**
Not a problem, but a good addition :)

This way, legendary could be triggered from an app easily or even from a browser!

**Describe the solution you'd like**
A protocol, e.g. legendary://launch/X, legendary://install/Y

**Describe alternatives you've considered**
None

**Comment by derrod** [comment]
One of the problems with this is that it requires legendary to be installed in a pretty much static location. When installing via pip this isn't really an issue, but if any of the portable binaries are used (primarily on Windows) this could cause issues, especially if the invalid links are not removed.

**Comment by dragonDScript** [comment]
> One of the problems with this is that it requires legendary to be installed in a pretty much static location. When installing via pip this isn't really an issue, but if any of the portable binaries are used (primarily on Windows) this could cause issues, especially if the invalid links are not removed.

An NSIS installer on windows could fix this. On linux, wget | ./script.sh
