### ISSUE TITLE
FileNotFoundError: 

### ISSUE THREAD

**Issue by CodeRed-tech** [derrod/legendary#325]
[Errno 2] No such file or directory: '/home/shamit/.config/legendary/config.ini'
I am getting this error on commands like : " legendary auth ", " legendary list-games "
Pls help me...

**Comment by tastytea** [comment]
Workaround: execute `touch '/home/shamit/.config/legendary/config.ini'` in a terminal to create the file.

**Comment by derrod** [comment]
Fixed by 0.20.8
