### ISSUE TITLE
`legendary auth` errors out with missing `country` parameter

### ISSUE THREAD

**Issue by CommandMC** [derrod/legendary#329]
## Platform
Operating system and version: Platform-independent, but I'm on Linux (EndeavourOS)
Legendary version (`legendary -V`): 0.20.8, but issue also happens with .7 and .6

## Expected Behavior
Well, the login should succeed.

## Current Behavior
After typing in the session ID, legendary fails with  
`ERROR: Getting exchange code failed: {'errorCode': 'errors.com.epicgames.accountportal.parameter_required', 'message': 'Parameter "country" is required', 'correlationId': '728e9c60-0cb7-11ec-992d-7fcd80ac346a'}`

## Steps to Reproduce
1. Depending on the situation, run `legendary auth --delete` to delete saved credentials
2. Run `legendary auth`
3. Paste in the SID

**Comment by volttics** [comment]
after i did the steps the error still happens

**Comment by CommandMC** [comment]
Yes, this is a bug report. The Steps to Reproduce are the steps it takes to get to that bug, not the steps to fix it. If I knew how to fix it, I'd do that myself.

Right now, we'll have to wait for Rodney to see this. I might also look into this after I'm done with what I'm currently doing

**Comment by BeaconOnAChairMC** [comment]
does installing a previous version fix the issue?

**Comment by derrod** [comment]
Fixed in d3026672d1d210de49f2b757f927d74eba651106, hotfix coming soon.
