### ISSUE TITLE
GTAV

### ISSUE THREAD

**Issue by fuzunspm** [derrod/legendary#33]
This is not an issue but I couldn't figure out how to launch GTAV. My wine 5.8 setup throws error after installing DirectX with a message of:

```
Unable to launch game, please verify your game data
```

**Comment by CommandMC** [comment]
1. This is a wine issue and not a Legendary issue
2. Change your wine version to proton or lutris, it'll work then. To login to Rockstar Game Launcher, change it to lutris. For best performance in-game, change it to Proton

**Comment by fuzunspm** [comment]
ok i managed to install rockstar games launcher but it then fails because of epic store login, how do i transfer my login from legendary to lutris/proton setup?
