### ISSUE TITLE
Cannot Auth at present due to missing "country" parameter server error

### ISSUE THREAD

**Issue by Bob837217** [derrod/legendary#335]
## Platform
Operating system and version: Windows 7
Legendary version (`legendary -V`): legendary version "0.20.8", codename "Water Hazard"

## Expected Behavior
command line: legendary auth
This should and does launch a URL with a SID coming back.
I paste this into legendary at the prompt.
This should be the end of it, but it currently is not.

## Current Behavior
At present, after I paste in a SID value, this is the remainder of the legendary output:
[Core] ERROR: Getting exchange code failed: {'errorCode': 'errors.com.epicgames.accountportal.parameter_required', 'message': 'Parameter "country" is required', 'correlationId': '70c3af10-0d75-11ec-9ab6-0d8900161afb'}
[cli] CRITICAL: No exchange token, cannot login.

## Steps to Reproduce
1.  Start command line with: cmd.exe
2.  Enter the login command: legendary auth
3.  Once the launched URL finishes, copy the "sid" value into legendary prompt and press enter
4.  Observe the server error reported by legendary

**Comment by CommandMC** [comment]
You're not on the latest version, which fixed exactly this issue. Update to [0.20.9](https://github.com/derrod/legendary/releases/tag/0.20.9)

**Comment by Bob837217** [comment]
Ah! Thanks for the hotfix - I will switch to it.

**Comment by Bob837217** [comment]
Yes, much better.  Issue resolved
