### ISSUE TITLE
I have an error while installing Fortnite from Legendary Launcher, it says: FileNotFoundErorr: [WinError 3] The system cannot find the path specified   [7192] Failed to execute script cli

### ISSUE THREAD

**Issue by yessir12345** [derrod/legendary#337]

**Comment by CommandMC** [comment]
Alright, mate, let's make this simple:
You see this thing when creating an issue: 
![image](https://user-images.githubusercontent.com/34034631/132104369-bb538ade-c3ed-4b75-90a0-4ddc685d84de.png)
**Don't delete that, fill it out!** We can't help you when you give us no info
