### ISSUE TITLE
Cannot find .exe

### ISSUE THREAD

**Issue by gnouts** [derrod/legendary#34]
I use Manjaro, so I installed legendary through AUR. Auth and installed the game went fine.

Launch failed with : `wine: cannot find '~/Games/legendary/GTAV/PlayGTAV.exe'`

And indeed the file does not exist.

**Comment by derrod** [comment]
Are there any files in that folder? You can try downloading just the executable by running `legendary download <GTA appname> --prefix PlayGTAV.exe`

**Comment by gnouts** [comment]
Yes folder is 89Go. It contains 23 files *.rpf, x64/audio, x64/data, update/x64/dlcpacks, ...

I tried your command but file is still absent. Here is the output :
```
> legendary download <GTA appid> --prefix PlayGTAV.exe
[cli] INFO: The "download" command will be changed to set the --no-install command by default in the future, please adjust install scripts etc. to use "install" instead.
[Core] INFO: Logging in...
[cli] INFO: Preparing download...
[Core] INFO: Parsing game manifest...
[Core] INFO: Install path: /home/nouts/Games/legendary/GTAV
[DLM] INFO: Found 344 files to skip based on include prefix(es)
[DLM] INFO: Remaining files after filtering: 0
[cli] INFO: Download size is 0, the game is either already up to date or has not changed. Exiting...
```

**Comment by derrod** [comment]
I forgot; you'll also have to add `--force` to force it to download the file (otherwise it belives the file exists since it is in the installed manifest.)

**Comment by gnouts** [comment]
Thanks it worked. I have others issue with wine lib not found. I'll search and open other issues if necessary.
Thanks for you quick answers :)
