### ISSUE TITLE
API for developers

### ISSUE THREAD

**Issue by emrecpp** [derrod/legendary#348]
Hello,
Do you intend to API for developers? If you think is there any progress?
Thanks!

**Comment by emrecpp** [comment]
> What do you mean exactly? This seems like a duplicate of #129

I mean there is a Wrapper class for easy to install/update/sync/uninstall.
Example;

```
def Install(appid, args, outProgressQueue):
#args like: force, update-only, ignore-free-space etc.
**#outProgressQueue: for the developer to find out the percentage.**
```
Thanks

**Comment by Dummerle** [comment]
You can use LegendaryCore as an api. I use it in https://github.com/Dummerle/Rare

It works good. Only the download function is hard, because you can't get download progress
