### ISSUE TITLE
Legendary failes to update/create Proton prefix

### ISSUE THREAD

**Issue by NinjaCheetah** [derrod/legendary#350]
## Platform

Operating system and version:
Linux Mint 20.2 "Uma"
Legendary 0.20.13 "Sandtraps"

## Expected Behavior
Legendary will update Proton in the prefix or install it if it's empty, then launch the same.

## Current Behavior
The prefix fails to update. This happens for any game I try to launch. I've been using this prefix since I originally installed Legendary and it's been able to update correctly in the past. It says it's currently None because I tried deleting it to see if that would help. I also reinstall Proton through Steam in case it was actually Proton preventing it from updating.
Log:
```
Proton: Upgrading prefix from None to 6.3-3 (/home/ninjacheetah/.proton/legendary/)
Traceback (most recent call last):
  File "/home/ninjacheetah/.steam/steam/steamapps/common/Proton 6.3/proton", line 1262, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/ninjacheetah/.steam/steam/steamapps/common/Proton 6.3/proton", line 1076, in init_session
    g_compatdata.setup_prefix()
  File "/home/ninjacheetah/.steam/steam/steamapps/common/Proton 6.3/proton", line 652, in setup_prefix
    steamdir = os.environ["STEAM_COMPAT_CLIENT_INSTALL_PATH"]
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'STEAM_COMPAT_CLIENT_INSTALL_PATH'
```

## Steps to Reproduce

1. Install any game
2. Configure Legendary to use any Proton prefix, new or old
3. Try to launch that game

**Comment by flavioislima** [comment]
> Ah ok. It's a shame that it no longer works, it made compatibility a lot better (for me at least).

You need to create the folder yourself.
So you create the folder and pass it with the right proton variables. That works for me.

**Comment by CommandMC** [comment]
The variable it's referring to has to be set to the Steam installation path (usually `~/.steam/steam`). Proton pulls some DLLs from there to create a prefix

Still, running Proton outside of Steam is not supported. I've not seen a game that requires it (although I'm still going through my 150+ free games that accumulated over the months), for workarounds to the games that I have covered, see [the EpicLinux wiki](https://github.com/CommandMC/EpicLinux/wiki)
