### ISSUE TITLE
Error when trying to install legendary[webview] on Kubuntu 21.04

### ISSUE THREAD

**Issue by Ahmed-E-86** [derrod/legendary#353]
I get these errors when trying to install legendary[webview] on Kubuntu 21.04
```
ERROR: Could not find a version that satisfies the requirement legendary[webview]
ERROR: No matching distribution found for legendary[webview]
```

**Comment by derrod** [comment]
Yes my bad, I got the package name incorrect. It should be `legendary-gl[webview]`. Will fix the README momentarily.
