### ISSUE TITLE
Legendary fails to create any new file or directory

### ISSUE THREAD

**Issue by AnErrupTion** [derrod/legendary#354]
## Platform

Operating system and version: Arch Linux
Legendary version (`legendary -V`): `legendary version "0.20.14", codename "Nova Prospekt"`

## Expected Behavior

Games should install properly and I should not have to create the `~/legendary` folder.

## Current Behavior

When trying to install a game (here Rocket League, but should apply to any game), I first get an error telling me that the `legendary` folder in my home directory is not present. I find it weird that legendary didn't create it itself, so I did it. After that, when I try again, the game downloads, but the FileWorker always gives me errors that the files of the game can't be written to disk.
Here is an example message:
```
[DLManager] INFO: = Progress: 38.98% (8181/20990), Running for 00:01:17, ETA: 00:02:00
[DLManager] INFO:  - Downloaded: 3245.47 MiB, Written: 4529.71 MiB
[DLManager] INFO:  - Cache usage: 72.0 MiB, active tasks: 16
[DLManager] INFO:  + Download	- 40.49 MiB/s (raw) / 45.95 MiB/s (decompressed)
[DLManager] INFO:  + Disk	- 15.47 MiB/s (write) / 3.00 MiB/s (read)
[DLManager] CRITICAL: Writing for TAGame/CookedPCConsole/Skin_MuscleCar_FCB_Esports_SF.upk.tmp failed!
[DLManager] CRITICAL: Writing for TAGame/CookedPCConsole/Skin_MuscleCar_FCB_Esports_SF.upk failed!
[FileWorker] ERROR: Removing file failed: FileNotFoundError(2, 'No such file or directory')
[FileWorker] WARNING: Something in writing a file failed: FileNotFoundError(2, 'No such file or directory')
[FileWorker] ERROR: Removing file failed: FileNotFoundError(2, 'No such file or directory')
```

## Steps to Reproduce

1. Install a game, for example `legendary install Sugar`

## Additional information

My SSD is fine, I can write files and directories to it, and this issue never happened before.

**Comment by AnErrupTion** [comment]
Deleting the config folder `~/.config/legendary` did solve the problem.

**Comment by derrod** [comment]
With commit 74bc2fecc0dba9349b5dfe1f598914a129c3c169 attempting to start an installation if the conditions causing this issue are present (game folder deleted, but not uninstalled) will show an error and abort.
