### ISSUE TITLE
The CMD window closes as soon as legendary.exe is opened :Windows 10

### ISSUE THREAD

**Issue by nroomy** [derrod/legendary#36]
Hey, Idk if im doing anything wrong and sorry if this is stupid. 

I downloaded the legendary.exe file and ran it on Windows. The CMD window opens, and then suddenly closes without any warnings. 

What am I doing wrong?

**Comment by CommandMC** [comment]
You have to open a command line/powershell in the directory the .exe is and then type in "legendary.exe".

**Comment by derrod** [comment]
You have to run it in a cmd/powershell terminal just like any other CLI app.
