### ISSUE TITLE
Add some info about game genre, description, system requirements

### ISSUE THREAD

**Issue by kaz-us** [derrod/legendary#363]
**Is your feature request related to a problem? Please describe.**
Nope! Just improve game list presentation.

**Describe the solution you'd like**
Add two more requests, storage system, and output this info. ;)

**Describe alternatives you've considered**
Parse this info from EGS site (=

**Additional context**
Hi.
There is no grouping of games in EGS and it's hard for me to search for something in a large list. I would like to see additional information about the games in the form of a list - genre, system requirements.
This information is not in the meta returned by the info or list-games request. I don’t know where you get the url of requests, I didn’t find them in the API documentation. But I looked at how this is done in [HeroicGamesLauncher](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher). I can do it myself too.
It will be necessary to implement 2 additional requests - to get the slug and the store-content:
[Slug request](https://www.epicgames.com/graphql?query=%7BCatalog%7BcatalogOffers(%20namespace:%225c0d568c71174cff8026db2606771d96%22)%7Belements%20%7BproductSlug%7D%7D%7D%7D)
[Content request](https://store-content.ak.epicgames.com/api/de/content/products/into-the-breach)
These requests will increase the processing time of the list-games command, so we need to make them using a separate key in the command or a separate command. And it is not yet very clear in what form to display information.
And there is also the problem of storing this data. I think all this information needs to be stored in a separate folder like metadata. But not in the same place. For example "content". And the slug store in meta.

Since this feature introduces significant changes to the program, I would like to receive your approval or comments about it.
If there are no comments from you and this idea corresponds to the way of the program's development, then I can proceed to implementation. But it will take a long time, since I don't know very well the architecture of your application yet ;)

**Comment by derrod** [comment]
With the current simple CLI based user interface I do not believe it makes sense or is in fact possible to properly present this kind of data. In the future that may change but for now this is not something I think makes sense to add.
