### ISSUE TITLE
A python error of auth

### ISSUE THREAD

**Issue by zerosherd** [derrod/legendary#365]
## Platform
running in win11 the latest experience packages platform with python 3.9.2 and go through with legendary 0.20.18

## Expected Behavior
i am going to auth epic account

## Current Behavior
alert with a error
![image](https://user-images.githubusercontent.com/45382820/140542863-fdbc9c12-036d-4ece-bac8-970c5b1207fb.png)

## Steps to Reproduce
1.open a terminal with shift and right button click
2.input ".\legendary auth"
3.return
4.error comes out

**Comment by derrod** [comment]
Seems like you have a proxy set on your system. This may be due to shitty Anti-Virus that attempts to intercept your traffic (and is failing to do so). Check your proxy settings and fix them.

**Comment by zerosherd** [comment]
it definitly help, but after i turn off thr proxy, i successfully go on but could not login due to the CHINA GFW.

**Comment by derrod** [comment]
Unfortunately I don't really know what to do there. You could maybe try manually specifying the proxy via environment variables: https://2.python-requests.org/en/latest/user/advanced/#proxies
