### ISSUE TITLE
Making installation guide more clear

### ISSUE THREAD

**Issue by Rushmore75** [derrod/legendary#372]
When installing Legendary for a new time wine user it was confusing how i needed wine AND wine mono (and winbind), neither of which is said in the installation guide. It's some what reasonable to assume wine is installed but you should make sure the install guide covers all the dependencies required. Thus for clearing up some new user headaches I had so others don't run into them.

**Comment by derrod** [comment]
Those dependencies are game-specific and legendary itself doesn't require them. The quickstart guide cannot cover game specific dependency requirements.

Unfortunately wine and the environment around it aren't really user friendly (proton aside).

There's a wiki here that covers some games: https://github.com/CommandMC/EpicLinux/wiki
