### ISSUE TITLE
Allow legendary to understand thazt I want it to install games to the "C:/program files/Epic Games" location

### ISSUE THREAD

**Issue by ParanormalBanana** [derrod/legendary#375]
**Is your feature request related to a problem? Please describe.**

When I specified this location, games were installed to a new folder called C:/Program. 
When I tried %programfiles%, games were installed in the locallow folder of Heroic in a new folder called %programfiles%
When I tried c:\PROGRA~1, or "C:/program files/epic games/" with quotes, nothing happened but Legendary and Heroic still believed the game was installed.
**Describe the solution you'd like**

Being able to specify this folder without hiccups. 
**Describe alternatives you've considered**

**Additional context**

Since I'm using heroic GUI, it is still a GUI and I have not tried to use legendary from the command line, so I don't really know if it's not a heroic issue, sorry if I'm mistaken

**Comment by CommandMC** [comment]
The Program Files directory requires administrative privileges to create folders. You're better off using *some* other directory

Although, this seems to be a general issue for paths with spaces. I don't have a Windows PC to test on, but they work fine on Linux:
```sh
$ legendary install Celeste --base-path "/home/commandmc/Temp/Folder with spaces/"
[...]
[Core] INFO: Install path: /home/commandmc/Temp/Folder with spaces/Celeste
[...]
```

**Comment by ParanormalBanana** [comment]
I've noticed that the folder with spaces thing is working when it is NOT C:/program files/...

Example (still using heroic GUI): 

I specified : %programfiles%/Epic Games/gamename/

hoping it would catch the handle without having to use the hardcoded location

game installed in 

C:/Users/appdata/locallow/Heroic/%programfiles%/Epic Games/gamename/ 

So maybe it's a heroic problem?

**Comment by ParanormalBanana** [comment]
Other solution I'd like to try but maybe impossible would be trying to specify the folder using some kind of other way to write spaces. 
eg (doesn't work): %20

**Comment by derrod** [comment]
Writing to program files requires administrative permissions, which legendary doesn't have normally, so that won't work (the console should be full of errors saying as much).

Environment variables in the path work in the command line, but not in the config or inside Heroic. But that's not really a legendary issue.
