### ISSUE TITLE
Failed to execute script 'cli' due to unhandled exception!

### ISSUE THREAD

**Issue by zerosherd** [derrod/legendary#376]
## Platform

Operating system and version: win11 latest stabe version
Legendary version (`legendary -V`): latest

## Expected Behavior

it should run a game

## Current Behavior

but it appear some error and stop this process

## Steps to Reproduce

1.launch a game
2.
3.
4.

## Additional information

this is the CMD screenshot, hope can help you guys locate the error.
![image](https://user-images.githubusercontent.com/45382820/145667952-3dad827f-5fa3-4f34-97c5-51fd4ca5fe91.png)

**Comment by Macify** [comment]
Same issue for me :(

**Comment by derrod** [comment]
You need to specify the game's folder, not the folder that that folder is in.
