### ISSUE TITLE
how do i use origin?

### ISSUE THREAD

**Issue by ChevinThames** [derrod/legendary#377]
the new hotfix is pretty pog but I am still an idiot and don't understand how do I use --origin. it says there are 0 games to redeem but why does it say that? I can't auth to log into an origins account and there doesn't seem to be any other commands that gives me that ability, maybe there is I'm just super confused, and hope one of you can explain it to me with would help a lot

**Comment by derrod** [comment]
The `--origin` option is striclty for activating Origin titles on your Epic account on the Origin client. If there are none of those titles on your account nothing will happen. Account linking is not required for this.
