### ISSUE TITLE
fail to launch game after adding a launch parameter.

### ISSUE THREAD

**Issue by freejool** [derrod/legendary#379]
## Platform

Operating system and version: Windows 10 Pro for Workstations
Legendary version (`legendary -V`): Legendary v0.20.21 - "Anticitizen One (hotfix #2)"

## Expected Behavior

launching the game
## Current Behavior

PS D:\EXE> sudo .\legendary.exe launch --wrapper culture=zh-Hans-CN-culture=zh-Hant-TW borderlands3
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[Core] INFO: Getting ownership token.
[cli] INFO: Launching Catnip...
Traceback (most recent call last):
  File "legendary\cli.py", line 2305, in <module>
  File "legendary\cli.py", line 2234, in main
  File "legendary\cli.py", line 646, in launch_game
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1311, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
[2508] Failed to execute script 'cli' due to unhandled exception!
## Steps to Reproduce

1. launch the game without parameter (ok)
2. sudo .\legendary.exe launch --wrapper culture=zh-Hans-CN-culture=zh-Hant-TW borderlands3 
3. then the errors came up

## Additional information

I don't know if I correctly added the param. I thought of -culture=zh-Hans-CN-culture=zh-Hant-TW, but it returned error "expected one argument".

**Comment by derrod** [comment]
`--wrapper` is to specify a different program that is supposed to launch the game (e.g. gamemode on Linux). To pass additional parameters just add them after the game name.
