### ISSUE TITLE
Cannot Save games to custom path

### ISSUE THREAD

**Issue by omegahack0** [derrod/legendary#38]
I tried to use legendary to install GTA5 to an external drive but instead it looks like it was installed to the default location. 
The command that I used was:
legendary install "9d2d0eb64d5c44529cece33fe2a46482" --save-path /home/m/NotDeadYet/GTA5
Instead of saving the files to: /home/m/NotDeadYet/GTA5
The game files were saved to: /home/m/legendary

**Comment by derrod** [comment]
See the help, `--save-path` is to specify the path where the save games will be (mostly useful for third party integrations that will specify the wine prefix with it), what you want is `--base-path`.
