### ISSUE TITLE
CPU and Ram usage at 100% when downloading a game (Among Us)

### ISSUE THREAD

**Issue by Withoutruless** [derrod/legendary#382]
## Platform
Operating system and version:
OS: Windows 10 Build 19043
Legendary version: 0.20.22 Anticitizen One (hotfix #3) 

## Expected Behavior
Download a game normally without 100% cpu usage and without 100% ram usage 

## Current Behavior
When pressing download the legendary.exe service starts and produces more and more powershell processes with it, causing my ram to go up to 100% usage and freezes my computer unless i stop the process from task manager

## Steps to Reproduce
Try Downloading Among Us (the issue occurs i have on that game, i havent checked others)

1. https://ibb.co/YXCYhnD
2. https://ibb.co/HYPqkcC
3. https://ibb.co/qMK8qYP
^^^^^^^^^^^^^^^^^
the ram usage increases over time, the cpu stays at 100%

## Additional information
CPU: AMD E2-9010 Dual Core 2.2GhZ
RAM: 1x4GB

0.20.22 Anticitizen One (hotfix #2) which is included when installing heroic game launcher does the same thing, just switched it out for 0.20.22 Anticitizen One (hotfix #3) hoping it would fix the issue.

(Im sorry if the report is badly written, this is my first time ever reporting an issue on github)

**Comment by derrod** [comment]
Legendary itself doesn't use powershell, that's a heroic thing, maybe check with them.

If you just use legendary itself to download the game it should work normally.

**Comment by Withoutruless** [comment]
I'll try replacing Legendary.exe with the old version of it and see i'll report back if it gets fixed by that.

**Comment by Withoutruless** [comment]
okay! ill write a report on their github page, im gonna be honest i mistakenly wrote this here and its kinda embarrassing but thanks for the help
(replacing legendary.exe with an older version didnt work so the issue is probably on their side)
