### ISSUE TITLE
When launched, the files are not detected

### ISSUE THREAD

**Issue by Lastxuan203954** [derrod/legendary#384]
## Platform

Operating system and version:windows10 19042.1348
Legendary version (`legendary -V`):0.20.22

## Expected Behavior
After detecting that the game has been installed, it should start normally.

## Current Behavior
It does not start normally, showing that the file cannot be found.

## Steps to Reproduce

1.D:\>legendary import-game Heather "D:\Epic Games\RedDeadRedemption2"
2.[cli] ERROR: Game is already installed!
3.D:\>legendary launch Heather "D:\Epic Games\RedDeadRedemption2"
4.[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Heather...
Traceback (most recent call last):
  File "legendary\cli.py", line 2317, in <module>
  File "legendary\cli.py", line 2244, in main
  File "legendary\cli.py", line 646, in launch_game
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
[12204] Failed to execute script 'cli' due to unhandled exception!

## Additional information

When importing a local epic game (RDR2), it shows that the game is already installed, but when launching it shows that the file is not found, and when testing it, it finds that Legendary does not recognise any of the files in RDR2, so it cannot launch.
![$CN@NLB3_U4Z2~6~972L3~L](https://user-images.githubusercontent.com/96333553/147202797-87f56c4b-fb78-4095-82e7-bcb88a4c3719.png)
![ID 9GPZ4AN7QJI51N~X}5(M](https://user-images.githubusercontent.com/96333553/147202806-2d9f806e-efb8-43de-ac0d-e515c191e329.png)
![L~`C)BAJYU867H})~ TV~D9](https://user-images.githubusercontent.com/96333553/147202812-3b69bf42-d27d-4e9e-ac27-1a98bf324e2b.png)

**Comment by derrod** [comment]
Is the game actually installed in that folder?

**Comment by Lastxuan203954** [comment]
![image](https://user-images.githubusercontent.com/96333553/147210369-07353baa-ccc0-479c-bdcd-e24eea86c7a2.png)

**Comment by derrod** [comment]
What does `legendary list-installed --show-dirs` say?

**Comment by Lastxuan203954** [comment]
![image](https://user-images.githubusercontent.com/96333553/147241071-ef2096b0-3c1c-4124-8d0a-5e66d5c7eee2.png)
like this, what can I do :(

**Comment by Lastxuan203954** [comment]
![image](https://user-images.githubusercontent.com/96333553/147243210-a36fc2a2-4eeb-4f46-aedd-e3c6a6ff0fb8.png)

**Comment by derrod** [comment]
First of all run `legendary list-games` to update the local metadata, then run the command exactly as I posted above: `legendary list-installed --show-dirs`

**Comment by Lastxuan203954** [comment]
![Uploading image.png…]()
Sry. Been asking you questions but I really don't know much about this, thanks a lot for your help, it's still not good :(

**Comment by Lastxuan203954** [comment]
![image](https://user-images.githubusercontent.com/96333553/147246684-47d333fb-f35a-4f11-ba8c-527648c959ee.png)

**Comment by derrod** [comment]
Yeah you used the wrong path when importing. Use `legendary uninstall Heather --keep-files` and then re-import with `legendary import-game Heather "D:\Epic Games\RedDeadRedemption2`. The latest version should've prevented you from importing with an invalid path with an error.

**Comment by Lastxuan203954** [comment]
thanks!!!!!!!!!!!!!!!!!!!!!!!!!
