### ISSUE TITLE
Unable to import multiple games

### ISSUE THREAD

**Issue by tokenspins** [derrod/legendary#391]
## Platform

Operating system and version: Windows 11 Build 22523.1000
Legendary version (`legendary -V`): 0.20.22 and latest master

## Expected Behavior
Import multiple games without deleting themselves using the same random(?) GUID Generator as EGL.

## Current Behavior

Importing a Game with EGL Sync enabled always uses the platform as EGL GUID which results in that the same manifest file is overwritten again and again.

## Steps to Reproduce

1. Enable EGL Sync
2. Import a Game that is not installed
3. Look at the installed.json at egl_guid and/or at the Manifest Path from EGL or the .egstore folder from the game.
4. Try to import another game that is not installed.
5. Look at paths or files at 3. again.

**Comment by derrod** [comment]
Oh that's quite an oversight, but thankfully an easy fix.
