### ISSUE TITLE
Stability question - game exit sometimes forces an update

### ISSUE THREAD

**Issue by Ryder17z** [derrod/legendary#393]
## Platform
Operating system and version:
Legendary version (`legendary -V`): N/A
Heroic Launcher 1.10.3 
Manjaro Linux 21.2.1
Kernel 5.10.89-1

## Expected Behavior
Normal Game Exit.
Start the game again at some point and there is no difference

## Current Behavior
(This assumes running Heroic Launcher)
Normal Game Exit.
Try to start the game again at some point and there is a dialog that says "Update required".
Clicking [No] just means the game wont run anymore
Clicking [Yes] might force an actual update to be downloaded and that causes a game of roulette if your playing a game where client and server versions has to match.

## Steps to Reproduce

0.    Install Heroic Launcher, from there proceed.
1.    Install Satisfactory (experimental version recommended)
2.    Connect to a server on same version as your game
3.    Exit game
4.    Re-launch the game.
5.    "Game needs an update" message shows up in heroic.
6.    Clicking "No" does not correctly launch the game, but instead it will just show game logo, then a blank screen for a couple of seconds and then the process is closed.
7.    Clicking 'yes' does an update which could cause a mismatch between the game version and the server version.

## Additional information
Originally posted on the Heroic repo but reposted here because "Heroic just checks legendary info about an update, that comes from epic, and shows the message."
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/757

Does this seem sensible?

I have not tested this recently as I don't know of a game server running the experimental version currently but it took the fun out of the game previously.

It  is not an issue with slowly updated game variants (i.e. Satisfactory Early Access)

**Comment by derrod** [comment]
This probably is an issue with Heroic losing command line arguments when adding the `--skip-version-check` flag here: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/00f7c29127de4e2d3b8ce355e522ecb764ed95fc/src/helpers/library.ts#L226

**Comment by flavioislima** [comment]
> This probably is an issue with Heroic losing command line arguments when adding the `--skip-version-check` flag here: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/00f7c29127de4e2d3b8ce355e522ecb764ed95fc/src/helpers/library.ts#L226

Nope, is being called correctly, check the output of Hades, that for me is asking to update:
```DXVK_HUD=fps   WINEFSYNC=1     STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/flavio/.steam/steam STEAM_COMPAT_DATA_PATH='/home/flavio/.proton-exp' /usr/bin/gamemoderun  /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Min   --no-wine --wrapper "'/home/flavio/.steam/steam/steamapps/common/Proton - Experimental/proton' run"  --skip-version-check```

My guess is that not all games allow playing without updating.

**Comment by derrod** [comment]
I see, I'm not too familiar with the Heroic code (or Typescript) so that just seemed like a possibility to me. Either way the only difference between launching an out-of-date game or an up-to-date one is a warning in the console. If the outdated version doesn't work, it's probably due to something else.

**Comment by flavioislima** [comment]
I wonder if this game has this issue because it's an online game.
I tested here another online game that has an update available: Magic the Gathering, and it also doesn't want to work outdated.
after updating it works just fine.

**Comment by Ryder17z** [comment]
> @Ryder17z You can launch heroic from the terminal to check the whole game command that Heroic sends to Legendary or click on Latest Log under Tools on Game Page.

Like mentioned above:
> I have not tested this recently as I don't know of a game server running the experimental version currently but it took the fun out of the game previously.

**Comment by Ryder17z** [comment]
> I wonder if this game has this issue because it's an online game. I tested here another online game that has an update available: Magic the Gathering, and it also doesn't want to work outdated. after updating it works just fine.

I don't know about that since it is not always an issue. Sometimes it would be possible to relaunch multiple times without forcing an update.
