### ISSUE TITLE
For Honor doesn't get activated on UPlay

### ISSUE THREAD

**Issue by games647** [derrod/legendary#394]
The command `legendary activate --uplay` fails to activate the game `For Honor`. It worked for other games. 

## Platform

Operating system and version: `Linux` `5.15.12`
Legendary version (`legendary -V`): `legendary version "0.20.24", codename "Follow Freeman!"`

## Expected Behavior

All codes are activated

## Current Behavior

The command runs and all codes are activated except `For Honor`. On the next invocation it still lists the game applicable to activate. Other games were activated.

>[cli] INFO: Found 1 game(s) to redeem:
[cli] INFO:  - For Honor
Do you want to redeem these games? [Y/n]: Y
[cli] INFO: Redeemed all outstanding Uplay codes.

## Steps to Reproduce

0. Confirm that the game is in the Epic account
1. `legendary activate -U`
2. Confirm with yes
3. Re-Run command
4. Still lists the game and UPlay doesn't show it in the my games account section

## Additional information

Maybe related that the game doesn't run on Wine, because of AntiCheat?

**Comment by derrod** [comment]
Could you try with this build and see what the debug output says? [legendary_uplay_debug.zip](https://github.com/derrod/legendary/files/7838841/legendary_uplay_debug.zip)

**Comment by games647** [comment]
<details>
{'errors': [{'message': 'PartnerIntegrationMutation/claimUplayCode: Request failed with status code 400', 'locations': [{'line': 4, 'column': 5}], 'correlationId': '4075bba0-7215-11ec-89cf-fd8786b3bbb6', 'serviceResponse': '{"errorCode":"errors.com.epicgames.partnerintegration.game_already_claimed","errorMessage":"A code has already been claimed for game 91808802f644410d8b5b58b2e0ca36cf and account 497bb0117b41499cb50b833efdff7055","messageVars":["91808802f644410d8b5b58b2e0ca36cf","497bb0117b41499cb50b833efdff7055"],"numericErrorCode":101000,"originatingService":"partnerintegration","intent":"prod","errorStatus":400}', 'stack': None, 'path': ['PartnerIntegration', 'claimUplayCode']}], 'data': {'PartnerIntegration': {'claimUplayCode': None}}, 'extensions': {}}
{'errors': [{'message': 'PartnerIntegrationMutation/redeemAllPendingCodes: Request failed with status code 400', 'locations': [{'line': 4, 'column': 5}], 'correlationId': '40896ab0-7215-11ec-967c-4d350ae2078c', 'serviceResponse': '{"errorCode":"errors.com.epicgames.partnerintegration.failed_to_redeem_code.invalid_country","errorMessage":"Failed to redeem code - code is for a different region","messageVars":[],"numericErrorCode":102008,"originatingService":"partnerintegration","intent":"prod","errorStatus":400}', 'stack': None, 'path': ['PartnerIntegration', 'redeemAllPendingCodes']}], 'data': {'PartnerIntegration': {'redeemAllPendingCodes': None}}, 'extensions': {}}
</details>

Interestingly it reports that it was already activated. However, nothing is in the UPlay launcher (neither games library or under account information).

`legendary info Sundrop`
```
Game Information:
- App name: Sundrop
- Title: For Honor
- Latest version: 1902
- All versions:
 +  Windows : 1902
- Cloud saves supported: False
- Cloud save folder (Windows): (None)
- Cloud save folder (Mac): (None)
- Is DLC: False
- Activates on external platform: ubisoft
- Extra launch options: (None)
- Owned DLC: (None)
```

**Comment by derrod** [comment]
Well the issue here is that while claiming a code worked, activating that code on your accounts fails with the following error:

```json
{
  "errorCode": "errors.com.epicgames.partnerintegration.failed_to_redeem_code.invalid_country",
  "errorMessage": "Failed to redeem code - code is for a different region",
  "messageVars": [],
  "numericErrorCode": 102008,
  "originatingService": "partnerintegration",
  "intent": "prod",
  "errorStatus": 400
}
```

I don't know why the code would be for a differnt region, did you maybe use a VPN or something while running legendary or have your Uplay account registered to a different country? The API requests never specify a region so this can't really be anything that legendary did.

**Comment by games647** [comment]
Oh missed that one. That could be the reason. In fact my Epic Games Store Country is currently different to where I'm currently living. I'll check if changing it, fixes it.

**Comment by derrod** [comment]
FWIW this is their help page on the specific error you're seeing (102008): https://www.epicgames.com/help/en-US/epic-games-store-c73/error-codes-c100/piubi01-a3582
