### ISSUE TITLE
Allow user to clean up games

### ISSUE THREAD

**Issue by MyBlueHorizon** [derrod/legendary#397]
**Is your feature request related to a problem? Please describe.**
Sometime, the game will can‘t work because some files be added(mods，community patch...).

**Describe the solution you'd like**
Allow user to clean up games to repair.

**Describe alternatives you've considered**
Although I can reinstall to solve the problem, but the internet is too slow for me and I have a full game just have some files more.

**Comment by derrod** [comment]
I feel that this is somewhat out of scope, and would also lead to issues with games that store their savegame in the installation folder.

The best thing you can do is use `list-files` to get a list of all files that *should* be in the game folder and then clean up based on that. Then run a `repair` to reset files that have been altered.

**Comment by MyBlueHorizon** [comment]
I write a script to do it(copy 18721 files to another place) and re-import them to Legendary.
It is sure that the function is not very useful in the most time, but it is useful if your game can't work and in slow internet
