### ISSUE TITLE
Launching Fortnite Requires Admin

### ISSUE THREAD

**Issue by TheSiker** [derrod/legendary#400]
I have a problem, whenever i try to launch Fortnite, it will ask for admin. Can you fix that?

Steps to recreate:
Use Windows 10
run `.\legendary install Fortnite`, then `.\legendary launch Fortnite`

**Comment by derrod** [comment]
That's because of the anticheat, I can't fix that.

**Comment by TheSiker** [comment]
If you cannot fix it, is there a workaround to avoid admin prompt?

**Comment by Fancy2209** [comment]
> If you cannot fix it, is there a workaround to avoid admin prompt?

Yes, use a Admin Command Propmt to use Legendary
