### ISSUE TITLE
sync-saves got remote 0 saves 

### ISSUE THREAD

**Issue by baraa272** [derrod/legendary#401]
## Platform

Operating system and version: windows 10
Legendary version (`legendary -V`):  0.20.25

i picked legendry recently since its an epic launcher without an epic launcher and i'm amazed how this works 100% except a small problem 
i installed daemonXmachina recently and launched the game played a bit and (legendry authenticated it with my epic account no problem) 
after quitting the game i used sync-saves command in general but it tells it got 0 remote saves 

legendary.exe sync-saves DaemonxMachina
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Got 0 remote save game(s)

am i doing something wrong and if so what should i do to get my save uploaded to cloud ?

**Comment by derrod** [comment]
The game doesn't support cloud saves. (See `legendary info dxm`)

**Comment by baraa272** [comment]
thanks for the answer
