### ISSUE TITLE
Compatibility for Sid Meier's Civilization VI

### ISSUE THREAD

**Issue by MyBlueHorizon** [derrod/legendary#402]
## Platform
Operating system and version:Windows 10 21H2
Legendary version:0.20.25

## Expected Behavior
The game can be recognized and started normally.
The Epic will not be launch.

## Current Behavior
I started the game through Legendary, and the 2K launcher ran successfully, but it was reported that the game was not installed.

## Steps to Reproduce
1.run "legendary launch Kinglet".
2.the 2K launcher ran successfully.
3.it report the game is not installed.

## Additional information
Earlier, 2K launcher reported game was installed, but clicking the start button will start the Epic at the same time.

**Comment by derrod** [comment]
Just run the launcher again, it should then say the game is installed. If it doesn't you can also just bypass the launcher using the `override_exe` config option like so:

```ini
[Kinglet]
override_exe = Base/Binaries/Win64EOS/CivilizationVI.exe
```
