### ISSUE TITLE
[question] automatic sid and custom import account epic games

### ISSUE THREAD

**Issue by Soi9x** [derrod/legendary#405]
Hello! I use Legendary through a C# wrapper in my code
Process Legendary = new Process();
Legendary.startinfo.filename = "Legendary.exe";
Legendary.startinfo.createnowindow = true;
Legendary.useshellexecutable = false;
Legendary.startinfo.arguments = "download brill";
  , but I need Legendary to update to add optional account entry in control panel : myaccount@gmail.com , mypassword , automatically , and I find the manual copy sid function in the browser bar very inconvenient for me How can devs get the sid code automatically instead of copying it on the browser and then pasting it into the console

**Comment by CommandMC** [comment]
Epic does a lot of things to prevent bots from logging in + they recently added captchas (which seem to only show up sometimes). Both of those things make it very hard if not impossible to automate a "direct" login  

It seems like the functionality was planned, but never implemented (the lines were added in the very first commit to this repo):
https://github.com/derrod/legendary/blob/d7360eef3e2ed5816da5549d71d5bce57e129df3/legendary/core.py#L97-L105
