### ISSUE TITLE
Unable to download/install/update games when running legendary install cmd

### ISSUE THREAD

**Issue by 1jp2003** [derrod/legendary#409]
## Platform

Operating system and version: Windows 10
Legendary version (`legendary -V`): 0.20.25

## Expected Behavior

Games should download/install/update.

## Current Behavior

(not sure where a log file is but have attached a [picture]) 
Legendary attempts to download/install/update the specified game but exits out due to a "paging file is too small for this operation to complete".

## Steps to Reproduce

[picture] 
(after login and getting list)
1. `legendary install _{gameTitle}_` 
2. `y/Enter` on prompt 
3. error is created and exits the download

## Additional information

Not sure if it matters specifically, but I ran the commands all through Command Prompt. I also was able to import some of the games I had originally from Epic Games, but was unable to "install"/update them (under the same reason). I also have not done EGL sync, if that matters for any reason.

[Picture]: https://i.uwu.bz/RDncmM4Kdf.png?key=FbywUdPyDdCvNz

**Comment by nutterthanos** [comment]
Um how much memory does your computer have and what setting is you system page file set on?

**Comment by 1jp2003** [comment]
My page file is set to 4192, and i have 16Gb of ram.

**Comment by nutterthanos** [comment]
Um weird
@derrod

**Comment by nutterthanos** [comment]
maybe try reducing the number of workers by adding --max-workers 8 or something

**Comment by 1jp2003** [comment]
I increased my max page size to around double and added the --max-workers 8 when installing
After doing those things, it seems to work now.

Thanks!
