### ISSUE TITLE
Computed save path wrong on linux

### ISSUE THREAD

**Issue by tastytea** [derrod/legendary#41]
The computed save path for “Untitled Goose Game” (Flour) is `%APPDATA%/../locallow/House House/Untitled Goose Game/`. I guess `%APPDATA%` should be translated to `${WINEPREFIX}/drive_c/users/${USER}/Application Data/`?

**Comment by derrod** [comment]
Yes, it's currently not done automatically since there's no way to know which wine prefix is used for that game (if you use more than one) unless it's set in the config. In the future third party integrations and changes to how legendary itself handles wine should make that easier.

**Comment by derrod** [comment]
Now that I know a little more about how WINE handles things related to `%APPDATA%` I think I can move forward with some changes that should make this a little easier. For instance by keeping track of the last wine prefix used to launch a game, and searching that or the one specified in the config to see if anx save game exists. Of course it'd still ask for confirmation, I also don't intend to make it work with the `-y` flag to avoid accidental misconfiguration.

**Comment by xxcodianxx** [comment]
Any progress on this change? 
This is still an issue on the current version.

**Comment by derrod** [comment]
Keeping track of the last wine prefix used is something I might come back to later (and with `--set-defaults` you can already achieve that). For now having working resolution at all is enough for me.
