### ISSUE TITLE
Minor Error in Error message for moving between different drives

### ISSUE THREAD

**Issue by kopilo** [derrod/legendary#416]
[cli] INFO: Moving "GTAV" from "C:/Legendary" to "S:\GTAV"
[cli] ERROR: Moving to a different drive is not supported. Move the folder manually to "S:\GTAV\GTAV" and then run "**legendary 9d2d0eb64d5c44529cece33fe2a46482 "S:\GTAV" --skip-move**"
Command in message should be:
legendary **move** 9d2d0eb64d5c44529cece33fe2a46482 "S:\GTAV" --skip-move

## Platform
Operating system and version:
Windows 10 Home
legendary version "0.20.25", codename "Our Benefactors"

**Comment by woctezuma** [comment]
This happened here:
https://github.com/derrod/legendary/blob/3d1042e27e91c9ec6d0d5c787a50c45b1c1944bb/legendary/cli.py#L2468-L2477
