### ISSUE TITLE
Download without authentication

### ISSUE THREAD

**Issue by Beat-YT** [derrod/legendary#418]
**Is your feature request related to a problem? Please describe.**
Hey uh I really want to have an option to download without authentication (like if I already have the manifest on my pc.)

**Describe the solution you'd like**
Just download iwthout auth.

**Describe alternatives you've considered**
Yes it is possible. EpicManifestParser and Splash does it.

**Comment by derrod** [comment]
Possible yes, but not really useful outside of certain niches, and not something I wish to support.

**Comment by nutterthanos** [comment]
you mean use the manifest to install an older version of a game that you have already on your computer?
@Beat-YT

**Comment by shakeyourbunny** [comment]
My guess is he wants to pirate Epic Games.

**Comment by shakeyourbunny** [comment]
.. with the help of https://github.com/VastBlast/EpicManifestDownloader/blob/main/lib/index.js

**Comment by shakeyourbunny** [comment]
... or is banned on Epic somehow.

**Comment by Beat-YT** [comment]
No, it's because downloading chunks doesn't require any authentication so if I have the manifest locally, there is no need to have authentication

**Comment by nutterthanos** [comment]
i mean if you have the manifest you could in theory use legendary install random appid you own but use a manifest for a different game and you could still install that different game but i guess there would be authenication if you try to run said game you don't own or just can't run said game online
