### ISSUE TITLE
Create .egstore folder inside game directory

### ISSUE THREAD

**Issue by JJTech0130** [derrod/legendary#420]
**Is your feature request related to a problem? Please describe.**

I play Subnautica modded with the open-source [Nitrox mod](https://github.com/SubnauticaNitrox/Nitrox/). In order to make it correctly determine the platform as "Epic Games", I have to manually add the `.egstore` folder and place [at least two files](https://github.com/SubnauticaNitrox/Nitrox/blob/4be9fd2f4ff65fe1ad11425a36ccc0be8437d949/NitroxModel/Platforms/Store/EpicGames.cs#L22) in it.

**Describe the solution you'd like**

It would be nice if legendary automatically created the `.egstore` folder and placed some (possibly bogus) files in it, so that I don't have to do it manually. This would mimic the behavior of the actual Epic Games launcher.

**Describe alternatives you've considered**

I've filed an [issue](https://github.com/SubnauticaNitrox/Nitrox/issues/1770) in their repository, to see if it might be possible to fix on their end.

**Additional context**

See the [issue](https://github.com/SubnauticaNitrox/Nitrox/issues/1770).
[Relevant code](https://github.com/SubnauticaNitrox/Nitrox/blob/4be9fd2f4ff65fe1ad11425a36ccc0be8437d949/NitroxModel/Platforms/Store/EpicGames.cs#L22) in their repository.

**Comment by derrod** [comment]
When enabling EGL sync those folders will be created, otherwise there's little point to it. But it might be worth documenting this issue + workaround in the wiki (which will be shown to users upon installation, and I'm planning more ways to surface this information).
