### ISSUE TITLE
Args (--tsv) encoding problem cuz of the game title

### ISSUE THREAD

**Issue by 0wn3dg0d** [derrod/legendary#424]
Hello.

I'm using Window 11 and the latest 0.20.25, codename "Our Benefactors" version of Legendary.

Looks like there is still some sort of windows unicode issue.
You tried to fix everything back in 2021 for 0.20.11, but looks like there's something left in args (--tsv). 

I tried to use "**legendary list-games --tsv  > Data.txt**" to export the list of games and get this:
```
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\Scripts\legendary.exe\__main__.py", line 7, in <module>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\legendary\cli.py", line 2915, in main
    cli.list_games(args)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\legendary\cli.py", line 221, in list_games
    writer.writerow((game.app_name, game.app_title, game.app_version(args.platform), False))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xe1' in position 35: character maps to <undefined>
```
(Cuz my system uses Windows-1251 [Cyrillic script])

The latest string in the exported Data.txt is: 
![image](https://user-images.githubusercontent.com/104977271/166894503-01c0baae-e821-4e33-911d-ea5ed16f4eeb.png)

**legendary list-games** is works just fine, so I can see a cause of the problem:
![image](https://user-images.githubusercontent.com/104977271/166894974-e750c2f1-3702-4666-9a8e-ae6c00c3f7e7.png)

So, it's cuz of "**á**".

I guess, I should add something like encoding='utf-8' somewhere to force utf-8 in args, but I don't have enough knowledge to figure it out. xD

**Comment by woctezuma** [comment]
The error happens here:

https://github.com/derrod/legendary/blob/ec91f69adc0fab6ee4d3d5e7864237b53fb66df2/legendary/cli.py#L217-L223

**Comment by 0wn3dg0d** [comment]
> It may be as simple as changing line 218 from:

Unfortunately, the result will be:
`'encoding' is an invalid keyword argument for this function`

I don't know much about python, but seems like usually it works like this:
```
with open('output_file_name', 'w', newline='', encoding='utf-8') as csv_file:
    writer = csv.writer(csv_file, delimiter=';')
    writer.writerow('my_utf8_string')
```

So, forced encoding='utf-8' is should be somewhere 'outside', like between list-games and args in terms of structure, probably.

**Comment by derrod** [comment]
Unfortunately Windows is stupid and hasn't arrived in Unicode land yet. I think you can manually switch the codepage of your terminal to UTF-8 and then it should (hopefully) work. Otherwise I don't know if there's a good solution.

**Comment by 0wn3dg0d** [comment]
> you can manually switch the codepage of your terminal to UTF-8

Unfortunately, it doesn't work. 

But your answer just reminded me about an article, that Windows builds (starting 1903) have 
**Beta: Use Unicode UTF-8 for worldwide language support** checkmark.

So, I headed to 
`All Settings -> Time & Language -> Language -> "Administrative Language Settings"`
![image](https://user-images.githubusercontent.com/104977271/166987717-8489b2b9-833c-49ea-9525-d9be8750f334.png)
activated this checkmark and rebooted my PC.

And now it's running like clockwork. 
![image](https://user-images.githubusercontent.com/104977271/166988537-6df28b83-3731-466b-a659-76bb6c49c9d8.png)

So, thanks anyway! I hope this solution will help someone else.
