### ISSUE TITLE
Syncing saves for "Tiny Tina's Wonderlands" does not work due to 1) bad expected path 2) apostrophe in name/path

### ISSUE THREAD

**Issue by pmarreck** [derrod/legendary#425]
Please see related bug: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1175

## Platform

Operating system and version: Linux Pop_OS very latest
Legendary version (`legendary -V`): Whichever the latest Heroic launcher beta uses

## Expected Behavior

Game saves/profile should sync properly

## Current Behavior

No saves nor profile are synced.
Errors in log (I will attach when I am next booted into Linux)

## Steps to Reproduce

1. Save a game in Wonderlands in Windows.
2. Fire up Wonderlands via the Heroic launcher, which uses Legendary to sync saves, using the same Epic credentials.
3. Observe that no saved states are available.
4. Sadface.

## Additional information

If you see the linked/related issue above, there's both a pathing issue ("My Documents" instead of "Documents") and a single quote omission issue, which combine destructively to create an invalid path. It may be possible to symlink the expected path to the badly-computed one as a workaround (hopefully Legendary follows symlinks!).

**Comment by derrod** [comment]
Heroic does its own save path resolution and will override Legendary's own. I don't think I added a way to remove the save path, so you'll have to edit `~/.config/legendary/installed.json` manually and remove `save_path` from the entry for that game. Then run `legendary sync-saves <app name>` and see what it says. I'm fairly confident that Legendary's own resolver works correctly.

**Comment by flavioislima** [comment]
Would be good to test using legendary only to see if its not an heroic issue.
Check the command line in heroic and test the same command using legendary only. Maybe without the save path.
