### ISSUE TITLE
DLC not detected with Outer Wilds

### ISSUE THREAD

**Issue by nickjwhite** [derrod/legendary#426]
I don't know if this is an issue with my Epic account, or legendary, but it could be legendary, and hopefully someone here can at least help me figure it out.

I have Outer Wilds installed with legendary, which worked great, but recently I bought the DLC for it ("Echos of the Eye"), but it doesn't show up in legendary's list, and I can't install it (I tried a --force --with-dlcs install, and it just reinstalled the base Outer Wilds). Running 'legendary list --json' shows Outer Wilds, with a `"dlcs": []` section. This is the only DLC I've bought with Epic Games, so I don't know if there's some sort of activation procedure or something I'm supposed to do, but I assume not. I checked in the source code of the game page for the DLC, and it's definitely marked as DLC for Starfish (Outer Wilds), not a separate game or anything.

Any tips of where to look and how to debug this would be very much appreciated!

**Comment by derrod** [comment]
See what `legendary info Starfish` says.

**Comment by nickjwhite** [comment]
Thanks so much for your generous comment, @derrod.

Indeed, I hadn't used legendary to launch the game before, I'd just used it as an installer. Using "legendary launch starfish" indeed does enable the DLC correctly. Very annoyingly, it appears to be disabled again when I try to start it in offline mode, as nothing appears to be saved in the profile to mark "has bought DLC". But that's not your fault, legendary is living up to its name once again. Thanks very much for your help, and the tool.
