### ISSUE TITLE
Failed to execute script 'cli' due to unhandled exception!

### ISSUE THREAD

**Issue by marshmel0l** [derrod/legendary#427]
![image](https://user-images.githubusercontent.com/67599352/167313669-348dbcc0-bdcf-4ca6-904b-f8f3b7464cdd.png)

every command works except verifying

if i redownloaded i can verify one time and will give me there is 4 files missing but they are exist and didn't changed for anything when i skip that and download them again with additional tags now the errors on the image comes when trying to download another tags

anyway i'm trying to get the file names of every tag

u can fix my problem and tell me how to get every tag file names

thanks

**Comment by derrod** [comment]
This was fixed in 3d1042e27e91c9ec6d0d5c787a50c45b1c1944bb but a new release has not yet been made. You can download a nightly windows build here: https://github.com/derrod/legendary/suites/6299220490/artifacts/225780400

**Comment by marshmel0l** [comment]
i don't have knowledge with python
nightly build will work without the python file edit?

and my second q is can i list tags files names?

**Comment by derrod** [comment]
The nightly build is just an exe you use instead of the one you currently use.

You can list the files for a specific tag with `legendary list-files <app name> --install-tag <tag>`
