### ISSUE TITLE
legendary auth only tests present login data

### ISSUE THREAD

**Issue by Almtesh** [derrod/legendary#428]
## Platform
Operating system and version: Windows 7 on Wine 5.0.3 on Debian 11
Legendary version (`legendary -V`): legendary version "0.20.25", codename "Our Benefactors"

## Expected Behavior
Legendary, with action `auth`, opens the web browser, or give a URL to open, to the Epic login page and expect a token.

## Current Behavior
Here's the log:
```plain
C:\windows>legendary auth
[cli] INFO: Testing existing login data if present...

C:\windows>legendary list
[cli] INFO: Logging in...
Traceback (most recent call last):
  File "legendary\cli.py", line 3004, in <module>
  File "legendary\cli.py", line 2915, in main
  File "legendary\cli.py", line 189, in list_games
  File "legendary\core.py", line 188, in login
ValueError: No saved credentials
[57] Failed to execute script 'cli' due to unhandled exception!
```

## Steps to Reproduce
1. Create a new wine prefix
1. Put the legendary executable in C:\Windows directory
1. Open cmd
1. Execute `legendary auth`

## Additional information
The problem is quite recent, I updated and played a game with Legendary two weeks ago.

**Comment by derrod** [comment]
Running Legendary within WINE is not supported, don't do that. Use the native Linux version.
