### ISSUE TITLE
Requests multilingual support for game listings such as Chinese

### ISSUE THREAD

**Issue by oncebeloved** [derrod/legendary#429]
Requests multilingual support for game listings such as Chinese。This will improve the reading experience of the service with the command line，谢谢 thinkyou much!

**Comment by derrod** [comment]
Legendary automatically tries to use your system locale, if it doesn't work correctly, you can override it with
`locale = zh-CN` in the config file.

However, after testing this it seems that most titles simply do not have a chinese title.

If you're referring to the CLI itself then I'll have to decline, as translating the entire app would be a massive undertaking (and pain in the ass). A future GUI may provide translated versions, as that is much easier.
