### ISSUE TITLE
Unattended option when installing/downloading (no y/n prompts for use in scripting). [ISSUE CLOSED] SORRY!

### ISSUE THREAD

**Issue by IBINT** [derrod/legendary#431]
Hi!
I'm working on CI of tools for Epic games and this beautiful piece of work could be very handy if I could access the Unreal Engine section with it instead of purely the game library.

I'm sure you guys know how to access that part of the Epic Store through code, and having this would allow me to run tests without manually uploading the sample games to an AWS repository... If it's not too much work, it would be a huge deal for me.

I found a bunch of old stuff working on nodejs and tried to adapt it to no avail. This is beyond me and I need help!
Much respect for doing this stuff, making these tools... It's great!
Thanks!

**Comment by CommandMC** [comment]
`legendary list` has a `--include-ue` flag, is that what you're looking for?

**Comment by IBINT** [comment]
I'm an idiot. This is an amazing tool I will be having a lot of fun with. Thank you.

**Comment by CommandMC** [comment]
`legendary -h` is your friend

In this case, you can add `-y` to default to Yes for all prompts. If you also need to skip selective downloads and/or DLCs (not sure if UE has anything like that), look into the respective flags for that as well (`legendary install -h` for help on that)

**Comment by IBINT** [comment]
What?? I swear I looked through the -h command! I must be out of it today. Thank you so much for answering, I was just gonna send y+enter through commands but this feels so much cleaner. I'm kinda embarrassed at my unintentional laziness. Thanks again man.

**Comment by LoganDark** [comment]
> `legendary list` has a `--include-ue` flag, is that what you're looking for?

This seems to only show UE4 versions, how can I download UE5?

```
.\legendary.exe list --include-ue
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Getting game list... (this may take a while)

Available games:
 * 4.27-Chaos (App name: UE_4.27Chaos | Version: 4.27.2-18386882+++UE4+Release-4.27-Chaos-2023.1-Windows)
 * Unreal Engine (App name: UE_4.0 | Version: 4.0.2-2034640+++depot+UE4-Releases+4.0-Windows)
 * Unreal Engine (App name: UE_4.1 | Version: 4.1.2-2109544+++depot+UE4-Releases+4.1-Windows)
 * Unreal Engine (App name: UE_4.10 | Version: 4.10.4-2872498+++depot+UE4-Releases+4.10-2023.1-Windows)
 * Unreal Engine (App name: UE_4.11 | Version: 4.11.2-2946394+++UE4+Release-4.11-2023.1-Windows)
 * Unreal Engine (App name: UE_4.12 | Version: 4.12.5-3039270+++UE4+Release-4.12-2023.1-Windows)
 * Unreal Engine (App name: UE_4.13 | Version: 4.13.2-3172292+++UE4+Release-4.13-2023.1-Windows)
 * Unreal Engine (App name: UE_4.14 | Version: 4.14.3-3249277+++UE4+Release-4.14-2023.1-Windows)
 * Unreal Engine (App name: UE_4.15 | Version: 4.15.3-3450819+++UE4+Release-4.15-2023.1-Windows)
 * Unreal Engine (App name: UE_4.16 | Version: 4.16.3-3561208+++UE4+Release-4.16-2023.1-Windows)
 * Unreal Engine (App name: UE_4.17 | Version: 4.17.2-3658906+++UE4+Release-4.17-2023.1-Windows)
 * Unreal Engine (App name: UE_4.18 | Version: 4.18.3-3832480+++UE4+Release-4.18-2023.1-Windows)
 * Unreal Engine (App name: UE_4.19 | Version: 4.19.2-4033788+++UE4+Release-4.19-2023.1-Windows)
 * Unreal Engine (App name: UE_4.2 | Version: 4.2.1-2101290+++depot+UE4-Releases+4.2-Windows)
 * Unreal Engine (App name: UE_4.20 | Version: 4.20.3-4369336+++UE4+Release-4.20-2023.1-Windows)
 * Unreal Engine (App name: UE_4.21 | Version: 4.21.2-4753647+++UE4+Release-4.21-2023.1-Windows)
 * Unreal Engine (App name: UE_4.22 | Version: 4.22.3-7053642+++UE4+Release-4.22-2023.1-Windows)
 * Unreal Engine (App name: UE_4.23 | Version: 4.23.1-9631420+++UE4+Release-4.23-2023.1-Windows)
 * Unreal Engine (App name: UE_4.24 | Version: 4.24.3-11590370+++UE4+Release-4.24-2023.1-Windows)
 * Unreal Engine (App name: UE_4.25 | Version: 4.25.4-14469661+++UE4+Release-4.25-2023.1-Windows)
 * Unreal Engine (App name: UE_4.26 | Version: 4.26.2-15973114+++UE4+Release-4.26-2023.1-Windows)
 * Unreal Engine (App name: UE_4.27 | Version: 4.27.2-18319896+++UE4+Release-4.27-2023.1-Windows)
 * Unreal Engine (App name: UE_4.3 | Version: 4.3.1-2226335+++depot+UE4-Releases+4.3-2023.1-Windows)
 * Unreal Engine (App name: UE_4.4 | Version: 4.4.3-2296771+++depot+UE4-Releases+4.4-2023.1-Windows)
 * Unreal Engine (App name: UE_4.5 | Version: 4.5.1-2336687+++depot+UE4-Releases+4.5-2023.1-Windows)
 * Unreal Engine (App name: UE_4.6 | Version: 4.6.1-2386410+++depot+UE4-Releases+4.6-2023.1-Windows)
 * Unreal Engine (App name: UE_4.7 | Version: 4.7.6-2513093+++depot+UE4-Releases+4.7-2023.1-Windows)
 * Unreal Engine (App name: UE_4.8 | Version: 4.8.3-2634408+++depot+UE4-Releases+4.8-2023.1-Windows)
 * Unreal Engine (App name: UE_4.9 | Version: 4.9.2-2707645+++depot+UE4-Releases+4.9-2023.1-Windows)
 * Unreal Engine Chaos (App name: UE_4.26Chaos | Version: 4.26.2-15903758+++UE4+Release-4.26-Chaos-2023.1-Windows)

Total: 30
```

**Comment by CommandMC** [comment]
For UE5, you have to specifically add it to your library through the website first (it's not on your account by default)

**Comment by LoganDark** [comment]
> For UE5, you have to specifically add it to your library through the website first (it's not on your account by default)

I've been searching the website all day, but the store won't show the listings for UE5, and if I click on any "unreal engine" links, it takes me to the landing page where it says the only way to obtain it is to download the launcher.

Exactly *which* website can I use to add UE5 to my library?

**Comment by LoganDark** [comment]
I just went and compiled it from source. For anyone looking to do the same thing, it took about 7 hours and used about 310 GB of disk space, at least on Windows. Definitely not for the faint of heart.
