### ISSUE TITLE
Legendary does not load old manifests after update

### ISSUE THREAD

**Issue by MinerPL** [derrod/legendary#439]
## Platform
Operating system and version: Dev Insider Windows 11 (Build 25126.1000)
Legendary version (`legendary -V`):
```
C:\Users\minerpl>legendary -V
legendary version "0.20.26", codename "Dark Energy"
```

## Expected Behavior
Legendary should update game/verify game files

## Current Behavior
Legendary throws error with information about missing old manifest

## Steps to Reproduce
1. Install/Import game using legendary 0.20.25
2. Update legendary to 0.20.26
3. Try to verify/update game
4. See error about missing old manifest

![image](https://user-images.githubusercontent.com/37021230/173827600-266ed0cb-4b9d-4eb6-90c9-8c5a98ee0ac4.png)

**Comment by derrod** [comment]
Not really, although it should only redownload the files that don't match. That is unfortunately what happens when the previous manifest is unavailable.

**Comment by MinerPL** [comment]
Well, then I have to re-download most of the games. Closing.
