### ISSUE TITLE
Game is marked as uninstalled when it shouldn't

### ISSUE THREAD

**Issue by SViN24** [derrod/legendary#44]
``C:\Users\John\legendary\SuperMeatBoy
λ legendary uninstall Buffalo
Do you wish to uninstall "Super Meat Boy"? [y/N]: y
[cli] INFO: Removing "Super Meat Boy" from "C:\Users\John/legendary\SuperMeatBoy"...
[LFS Utils] ERROR: Failed deleting files with PermissionError(13, 'Δεν ήταν δυνατή η προσπέλαση του αρχείου από τη διεργασία, επειδή χρησιμοποιείται ήδη από κάποια άλλη διεργασία')
[cli] INFO: Game has been uninstalled.

C:\Users\John\legendary\SuperMeatBoy
λ cd ..

C:\Users\John\legendary
λ legendary uninstall Buffalo
[cli] ERROR: Game Buffalo not installed, cannot uninstall!
``

Here we have an example of a game that should be uninstalled because the resource is being used(that is what it says in greek) when such an error comes up it should be marked as uninstalled

**Comment by derrod** [comment]
I'll make it show a message telling the user to manually delete the folder if it fails, not much more I can do about that. Managing partially-deleted installations just sounds like a pain.
