### ISSUE TITLE
Legendary authentication fails

### ISSUE THREAD

**Issue by SvekkeO** [derrod/legendary#448]
## Platform

Operating system and version: Linux Mint 20.3
Legendary version (`legendary -V`): 0.20.27

## Expected Behavior

Legendary should Authenticate (trying to install Fall Guys through https://www.makeuseof.com/install-and-play-fall-guys-on-linux/ and play with my friends on Windows)

## Current Behavior

Legendary fails to open Authentication process stating "Permission denied" as reason. 
![image](https://user-images.githubusercontent.com/108631877/177056351-41895d51-949e-4d99-bb43-846c523472f6.png)

## Steps to Reproduce

1.Downloaded latest Legendary program file
2. Run _./legendary auth_ in Terminal (also tried running as sudo, no different effect)
3. Process fails

## Additional information

I'm a bit of a Linux newbie, so it is very well probable I just missed an obvious step.

**Comment by derrod** [comment]
You need to mark the file as executable `chmod +x legendary`.

**Comment by CommandMC** [comment]
Sidenote but that guide is *not that great*. I'd recommend joining the Heroic Discord and following the guide there
