### ISSUE TITLE
Overlay is there but invisible

### ISSUE THREAD

**Issue by FilterUnfiltered** [derrod/legendary#452]
## Platform

Operating system and version: Manjaro Linux 5.15.46-1
Legendary version (`legendary -V`): 0.20.27

## Expected Behavior

The overlay should show up when trying to open it

## Current Behavior

The mouse goes to my default mouse (instead of the custom in-game one) but no overlay shows up. Moving the mouse to where the buttons and search bar of the overlay should be interracts with the mouse, meaning the overlay is there, just invisible.

## Steps to Reproduce

1. Set up fall guys according to following two resources: https://www.youtube.com/watch?v=j1lI9KM_H7s https://www.makeuseof.com/install-and-play-fall-guys-on-linux/
2. Open game
3. Either press invite (in the party menu) or press the add person button on the bottom (pressing shift+f3 also works)
4. Notice bug

**Comment by derrod** [comment]
The GitHub issues are not for Wine/Game issues. This sounds like you're possibly running an outdated DXVK and/or Wine version. I think you might also need additional wine patches that only exist in Proton/Wine-GE and not in upstream wine at this time.

**Comment by FilterUnfiltered** [comment]
I've been using the latest wine versions: Proton GE 7-24 and Wine GE 7-20, and neither work

**Comment by derrod** [comment]
Have you actually installed the overlay?

Unfortunately I can't really help further than that, I haven't tried it myself yet.

**Comment by FilterUnfiltered** [comment]
> Have you actually installed the overlay?
> 
> Unfortunately I can't really help further than that, I haven't tried it myself yet.

yeah I installed it using paru package manager. I made sure it is enabled for the game as well and it says already enabled, nothing to do etc. And I know the overlay is there since I can interract with it, it's just invisible. I would love to give any more info if I had it I just don't know what else to give.

**Comment by Sandelinos** [comment]
I had the same issue on Proton 7.0. Fixed by installing GloriousEggroll Proton7-26.
I posted the details of my setup here: https://sandelinos.com/nerd-stuff/Fall_Guys_on_Linux/

**Comment by FilterUnfiltered** [comment]
> I had the same issue on Proton 7.0. Fixed by installing GloriousEggroll Proton7-26. I posted the details of my setup here: https://sandelinos.com/nerd-stuff/Fall_Guys_on_Linux/

I am using proton GE 7-26.... Still, the overlay is invisible
