### ISSUE TITLE
A way to supply download exclusions from a file

### ISSUE THREAD

**Issue by intrnl** [derrod/legendary#459]
**Is your feature request related to a problem? Please describe.**

The game [Phantasy Star Online 2](https://store.epicgames.com/en-US/p/phantasy-star-online-2), is actually two games in one, which comes out to over 100 GiB total in size.

The Japanese version of the game actually lets you choose whether to download only the new game, or both, while the Global version doesn't have any way of doing so.

However, by following the patchlist from the Japanese version, we can actually replicate the same thing, so what's left is having a download method that doesn't involve the entire two games.

**Describe the solution you'd like**

A way to supply a file containing files to exclude from downloading, preferrably doesn't involve checking in lowercase and as prefix.

**Describe alternatives you've considered**

The existing `--exclude` option doesn't work well for this situation, we have many files to exclude, especially as we're working with the Japanese patchlist, where the list doesn't contain any Global-specific files, and thus requiring the exclusion filter to be fully duplicated twice resulting in an exclusion of **99,532 files** as of this writing. (which could be less if we know Global-specific files ahead of time)

The [exclusion file created](https://gist.github.com/intrnl/266ab0aabed4acd3b3c26d99b21d5e20) to only have the new game comes out to over 5.2 MiB in size. [exclude_patchlist.txt](https://github.com/derrod/legendary/files/9228235/exclude_patchlist.txt)

**Additional context**

I've tried a solution where it reads a supplied file and then appends it to `file_exclude_prefix`, but this has resulted in a very, very, slow exclusion operation that has my PC fans actually kicking in. I had to stop it because it didn't even finish after 5 minutes has passed.

Note that I have little to no experience with Python, and thus wasn't sure about what's actually causing it to slow down, it could either be from trying to lowercase the files, or from doing a prefix check. But what's certain is that not doing any of those has made the operation significantly faster.

We can also go with the assumption that anyone passing a file list very much knows what they're doing, and is specifically excluding specific files from downloads.

**Comment by derrod** [comment]
As mentioned in #460 this use case is just way too niche for the overhead it adds, maybe later after the downloader rewrite when things are a bit more cleaner.
