### ISSUE TITLE
cannot log in Eic

### ISSUE THREAD

**Issue by zhuminkun** [derrod/legendary#466]
when i type  "legendary auth" it goes to Epic website, but fail to open.
it shows "{"redirectUrl":"https://epicgames.com/account/personal","authorizationCode":null,"sid":"f9eab89a7fa0" on the website. how can i fix it. 
Tks in advacne.

**Comment by derrod** [comment]
Follow the instructions, you have to copy the "sid" value into the CLI to finish the auth process.
