### ISSUE TITLE
Authentication does not work

### ISSUE THREAD

**Issue by timiimit** [derrod/legendary#468]
## Platform

Operating system and version: Microsoft Windows 10 Pro (10.0.19044 Build 19044)
Legendary version (`legendary -V`): legendary version "0.20.27", codename "Dark Energy (hotfix)"

## Expected Behavior
Account gets added to legendary

## Current Behavior
Command: `legendary auth`
Output:
```
[cli] INFO: Testing existing login data if present...
Please login via the epic web login!
If the web page did not open automatically, please manually open the following URL: https://www.epicgames.com/id/login?redirectUrl=https://www.epicgames.com/id/api/redirect
Please enter the "sid" value from the JSON response: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[Core] ERROR: Getting exchange code failed: {'errorCode': 'errors.com.epicgames.unauthorized', 'message': 'You are not authenticated. Please authenticate.', 'correlationId': 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'}
[cli] CRITICAL: No exchange token, cannot login.
```

## Steps to Reproduce
- download & install latest legendary version
- use `legendary auth`
- copy sid from website into console
- press enter

## Additional information
i noticed this about 12 hours ago. i'm not sure if epic is temporarily playing with us or if we need another authentication method.

**Comment by imLinguin** [comment]
Try using a WebView method

**Comment by ItsAleph** [comment]
Many people have the same issue when using HGL, looks like Epic changed something on their side (EGL was updated recently, too).
[Issue on HGL's repo](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1754)

**Comment by FeyrisTan** [comment]
When can we expect a a "fix"? at least for the windows version for now.

**Comment by nutterthanos** [comment]
its failing with this 
https://www.epicgames.com/id/api/exchange/generate
could switch login via authorization_code generated from https://www.epicgames.com/id/api/redirect?clientId=34a02cf8f4414e29b15921876da36f9a&responseType=code

**Comment by derrod** [comment]
> could switch login via authorization_code generated from https://www.epicgames.com/id/api/redirect?clientId=34a02cf8f4414e29b15921876da36f9a&responseType=code

Curious, I could've sworn I've tried that at some point in the past and it didn't work, but now it does. I'll release a hotfix using that instead soon.
