### ISSUE TITLE
Unable to change wine_executable to Proton

### ISSUE THREAD

**Issue by gnouts** [derrod/legendary#47]
(Wine-noob here)
How do I change the wine_executable to proton ?

`wine_executable = proton` does not work as proton is not in my path.
I have several version of Proton installed under `~/.local/share/Steam/steamapps/common/Proton X.X/`
I tried putting this absolute path but something seems wrong with the escaping space.

Whatever I tried I always ended up with this error :
```
> legendary launch Kinglet 
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Kinglet...
Traceback (most recent call last):
  File "/usr/bin/legendary", line 11, in <module>
    load_entry_point('legendary-gl==0.0.13', 'console_scripts', 'legendary')()
  File "/usr/lib/python3.8/site-packages/legendary/cli.py", line 775, in main
    cli.launch_game(args, extra)
  File "/usr/lib/python3.8/site-packages/legendary/cli.py", line 387, in launch_game
    subprocess.Popen(params, cwd=cwd, env=env)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'proton'

```

**Comment by derrod** [comment]
You have to set a path to the `wine64`/`wine32` binary in the Proton directory, not the proton script.

**Comment by gnouts** [comment]
Ha ok thanks ! I found this wine64 exectuable to work-ish
```
[default]
wine_executable = /home/nouts/.local/share/Steam/steamapps/common/Proton 4.11/dist/bin/wine64
```

Legendary does not complain anymore but no game launch. I have a lot of this error : 
```
006c:err:module:load_so_dll failed to load .so lib "/home/nouts/.local/share/Steam/steamapps/common/Proton 5.0/dist/bin/../lib64/wine/winebus.sys.so": libudev.so.0 : No such file ...
```
Depending on the game, it's either :
* `dist/bin/../lib/wine/l3codeca.acm.so": libmpg123.so.0`
* `dist/bin/../lib/wine/mp3dmod.dll.so": libmpg123.so.0`
* `dist/bin/../lib64/wine/winebus.sys.so": libudev.so.0`

The game end with "Graphic setup has failed" or "Path not found"

**Comment by derrod** [comment]
I can't tell you why that happens, seems it's trying to load stuff from a different proton version though. Perhaps try setting the wine prefix as well.

**Comment by gnouts** [comment]
What would you set as the wine_prefix ? Should it be the Proton top directory ?
Like `/home/nouts/.local/share/Steam/steamapps/common/Proton 4.11` ?
