### ISSUE TITLE
Can't find the game I just purchased

### ISSUE THREAD

**Issue by ArriettyQAQ** [derrod/legendary#472]
## Platform

Operating system and version:Windows 11
Legendary version (`legendary -V`):0.20.28

## Current Behavior

Can't find the game I just purchased
The name of the game is: it-takes-two

## Steps to Reproduce

1.
2.
3.
4.

**Comment by derrod** [comment]
Origin games cannot be directly installed, `legendary list -T` will show you the game and instructions on how to install it.
