### ISSUE TITLE
Command for activating Uplay games on Epic fails

### ISSUE THREAD

**Issue by Doc-4** [derrod/legendary#474]
![image](https://user-images.githubusercontent.com/60247583/188304049-aa911344-6eb1-41f0-8cb4-a077e882f0f0.png)

## Platform
Operating system and version: Win10 Pro 21H2
Legendary version (`legendary -V`): legendary version "0.20.28", codename "Dark Energy (hotfix #2)" Installed as standalone binary

## Expected Behavior
Legendary would activate games or return that there are no games to activate

## Current Behavior
Legendary gives a traceback

## Steps to Reproduce
1. run "legendary activate -U" (epic account has already been linked in this case)

**Comment by derrod** [comment]
For some reason the GraphQL endpoint seems to only sporadically work for me recently, perhaps additional anti-automation measures. Will need some investigating.

Weirdly an older EGL user-agent still goes through, so I've updated it to use that for now. You can run `legendary status` to update the configuration from the Legendary API and then try again.

**Comment by Doc-4** [comment]
That was fast! That worked. I wish you luck in investigating all the things they broke with the last batch of changes
