### ISSUE TITLE
legendary 0.20.29  wont run fortnite: wine not supported 

### ISSUE THREAD

**Issue by louigi600** [derrod/legendary#482]
Operating system and version: tried both with Fedora 35 and ubuntu 22.04
Legendary version 0.20.29

## Behavior
I installed legendary (the pip way on ubuntu while on fedora I used the distribution package{ot rpmforge}) and wine64, authenticated on epic games, downloaded fortnite and verified it.
But when I go to launch it
legendary launch Fortnite
I get "wine not supported" error popup in a box after some preliminary stuff appears on the desktop.
Exact same behavior on both Ubuntu and fedora. regardless of wine or wine64.

## Expected Behavior
I expected the game to start.

## Additional information
Hardware: NUC10i3FNK
CPU: Intel i3
RAM: 16Gb

**Comment by derrod** [comment]
Fortnite doesn't work on Linhx.

**Comment by louigi600** [comment]
Yes that's why there is wine:
Wine loads and runs the given program, which can be a DOS, Windows 3.x, Win32 or Win64 executable (on 64-bit systems).
So maybe the problem is finding a way to setup wine to be able to correctly run Fortinte on linux.

What is the point of having legendary on linux if it can't launch the games ?
and what is the wine_executable config line for inside config.ini
; (linux/macOS) Wine executable and prefix
wine_executable = wine

**Comment by derrod** [comment]
I'm very well aware of what Wine is, and if you had spent 5 seconds to google "Fortnite wine" or "Fortnite linux" instead of writing a condescending reply you would've found out that Fortnite does not in fact run in Wine due to the anti-cheat not allowing it.

(And GeForce Now runs Windows Server, that's why it works)
