### ISSUE TITLE
Updates too big

### ISSUE THREAD

**Issue by gabriele2000** [derrod/legendary#484]
**Is your feature request related to a problem? Please describe.**
Missing delta updates like original EGS (i guess) https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1858

**Describe the solution you'd like**
If my friends have to download 250MB, I don't want to download 10 times the data, but 250MB

**Describe alternatives you've considered**
Looking at the logs, it seems that delta updates are done, but something's off, since it "ignores" stuff or downloads things that makes the downloads too big for, say, a simple hotfix of 200MB

**Additional context**
The Cycle: Frontier is the game that I'm seeing this problem with. If I remember correctly, even in Rocket League I had to download massive updates while my friends didn't

**Comment by WizardCM** [comment]
The download doesn't look to be 250MB on Epic launcher.

![image](https://user-images.githubusercontent.com/941350/193432602-67af5db3-9e59-43d2-9081-b874342bca29.png)

**Comment by derrod** [comment]
The last update was also ~2 GB on Steam so I imagine this is not really a Legendary issue but one with the Cycle.

**Comment by gabriele2000** [comment]
> The download doesn't look to be 250MB on Epic launcher.
> 
> ![image](https://user-images.githubusercontent.com/941350/193432602-67af5db3-9e59-43d2-9081-b874342bca29.png)

Sadness overcomes my body and my soul... So basically I really have to download 2GB every time they push a "hotfix" just because somehow the compression doesn't work?
Issue with The Cycle?
Aren't the servers supposed to compress stuff and set the delta update?

**Comment by gabriele2000** [comment]
> The last update was also ~2 GB on Steam so I imagine this is not really a Legendary issue but one with the Cycle.

That guy has Steam, I installed it with Epic (a mistake, a huge mistake)

**Comment by derrod** [comment]
They released multiple hotfixes over the last few days, plus a major update (1.7 -> 2.0), it's possible they don't have delta updates available for all of them so patches are less efficient than they could be (FWIW Steam generates Delta updates automatically).

**Comment by gabriele2000** [comment]
> They released multiple hotfixes over the last few days, plus a major update (1.7 -> 2.0), it's possible they don't have delta updates available for all of them so patches are less efficient than they could be (FWIW Steam generates Delta updates automatically).

Tomorrow I'm gonna ask on their discord server if that's the case.

**Comment by gabriele2000** [comment]
I forgot to post an update.

The problem wasn't a problem of Legendary, as you said.
The update was really that big, which is pretty stupid though.

Thanks for your patience anyway.
