### ISSUE TITLE
sync_saves throws KeyError exception on Force Download ("get_save_games" fails to get complete list?)

### ISSUE THREAD

**Issue by HavocInferno** [derrod/legendary#489]
## Platform
Operating system and version: SteamOS 3.3
Legendary version (`legendary -V`): 0.20.28 (in Heroic 2.4.3 Flatpak)

## Expected Behavior
For games A Plague Tale: Innocence or Ooblets (only those two tested; though I expect all are affected?):
Save Sync "Force Download" in Heroic Launcher should download 2 save game files from EGS Cloud

## Current Behavior
On clicking Force Download (executes legendary sync from cloud), log shows:
[cli] INFO: Got 2 remote save game(s)
[cli] INFO: Checking "A Plague Tale: Innocence" (e0fa47ae79514345823bff209ae29451)
[cli] INFO: Overriding save path with "/home/...[etc correct path to save dir]"
[cli] INFO: Downloading remote savegame...
Traceback (most recent call last):
   File "legendary/cli.py, line 3054, in <modules>
   File "legendary/cli.py, line 2981, in main
   File "legendary/cli.py, line 533, in sync_saves
KeyError: 'e0fa47ae79514345823bff209ae29451'
[pID] Failed to execute script 'cli' due to unhandled exception

-> same for Ooblets, except _e0fa47ae79514345823bff209ae29451_ appName replaced by _Ostrich_ appName and different game name and dir

## Steps to Reproduce
1. Install A Plague Tale: Innocence or Ooblets and click through to main menu once?
2. Force download/sync save files from cloud

## Additional information
Regular (non-force) Download sync log says "Cloud saves: N/A", which must be false as EGS on Windows successfully finds those cloud saves.
Looks like legendary/core.py#L787 returns an incomplete list, which means legendary/cli.py#L452-455 adds no latest_save for the game in question and sync_saves crashes on trying to download that very save.

**Comment by HavocInferno** [comment]
Not sure if this is related to the manifest fix in 0.20.29 as get_save_games also uses *some* manifest.

**Comment by derrod** [comment]
What does `list-saves` say?

**Comment by HavocInferno** [comment]
Uh, I'll have to ask: how can I call legendary manually if it's installed as part of the Heroic flatpak?

**Comment by derrod** [comment]
Just download the latest release and try it with that.

I checked the game on my machine and Legendary can see the cloud save created by the epic launcher just fine.

**Comment by HavocInferno** [comment]
Well, that's odd...it only finds savegames for two games.
But the Windows official EGS client syncs my Ooblets and Plague Tale saves just fine.
```
./legendary list-saves
[Core] INFO: Trying to re-use existing login session...
[Core] INFO: Fetching metadata for 255 app(s).
[cli] INFO: Getting list of saves...
Save games:
- Bugsnax ("Bonytail")
 + 2022.06.03-15.34.43.manifest
 + 2022.06.04-16.42.50.manifest
 + 2022.06.05-14.02.43.manifest
- Borderlands 3 ("Catnip")
 + 2022.05.20-13.29.30.manifest
 + 2022.05.20-13.46.26.manifest
 + 2022.05.20-13.53.47.manifest
```

**Comment by derrod** [comment]
Are you sure you're logged in with the same account on both 😛?

But seriously I have no idea, I'm using the latest launcher on Windows and it works fine.

**Comment by HavocInferno** [comment]
Yup, same account. 

Not sure if I should just wipe Heroic and reinstall all of it. 

Could still try with legendary on Windows...see if that one finds the missing saves.

**Comment by HavocInferno** [comment]
Huh. Legendary on Windows also doesn't find the saves for those two games, only the same two it also finds on SteamOS.
wtf...

Does legendary store the latest fetched metadata for each owned game somewhere? Then I could check what specifically it finds for the two problem games.

**Comment by derrod** [comment]
It's possible there's some A/B test going on I'm not aware of. But at least my client still seems to use the same cloud save functionality as ever.

**Comment by HavocInferno** [comment]
Well, it works again! Though I'm not sure what fixed it. 
Several attempts at playing either of the two affected games on both machines and then syncing didn't help.

Then, on a whim, I tried this:

1. - on the Windows machine with official EGL - I installed a game (Absolute Drift) I hadn't played before, played until the first checkpoint and let it sync. 
2. I ran list-saves on another machine, it now listed the Bugsnax and Borderlands saves (as before in https://github.com/derrod/legendary/issues/489#issuecomment-1289572450), but also the new savegame for Absolute Drift
3. I played Ooblets again on the EGL machine, saved and let it sync.
4. I ran list-saves on another machine again, ...and it worked again! it listed save games from 9 different games, all the ones with Cloud Sync I played via EGL before..

So I suppose the issue is fixed, in a sense? Or at least it's a workaround.

**Comment by derrod** [comment]
I guess I can close this for now. I don't know what happened there, but I guess whatever was happening is no longer the case.

**Comment by HavocInferno** [comment]
> I guess I can close this for now. I don't know what happened there, but I guess whatever was happening is no longer the case.

Bad news: the issue is back, but slightly different. 
Now list-saves doesn't return the savegame for A Plague Tale, but it lists the savegames of all my other sync-able games. 
It worked fine for the couple days since my last reply though...
