### ISSUE TITLE
Epic Games OAuth Flow

### ISSUE THREAD

**Issue by theodoretliu** [derrod/legendary#49]
Hi, this is a really cool library! Sorry if this is off-topic, but we're developing an application where we need users to sign into their Epic Games accounts so that we can verify that they truly own the usernames that they claim. We want to go through Epic Games and have a redirect URL back to our site since that's the "standard" OAuth flow. Do you know if Epic Games has a REST endpoint that performs this authentication and redirect with an OAuth token? We figured we'd ask here since you clearly have a lot of expertise on the protocols they support.

**Comment by derrod** [comment]
I have no idea how that would work, all Legendary does is login as the Epic Games Store client. But it seems like the Epic Online Services that they recently made available for free might support something like that: https://dev.epicgames.com/docs/services/en-US/EpicAccountServices/GettingStarted/index.html

**Comment by theodoretliu** [comment]
@derrod thanks for the tip, the link was actually super useful. If I could ask about the code really quickly, where did you come up with `_user_basic` and `_pw_basic` in `api/egs.py`?

**Comment by derrod** [comment]
Those are taken from the Epic Games Launcher, you will probably receive your own ones after registering for the Epic Online Services program. But I have never used that so I cannot help you with that.

**Comment by theodoretliu** [comment]
Thanks for all your help!
