### ISSUE TITLE
Webview auth does not work

### ISSUE THREAD

**Issue by Aida-Enna** [derrod/legendary#491]
## Platform

Operating system and version: Multiple versions of Windows
Legendary version (`legendary -V`): ```legendary version "0.20.29", codename "Dark Energy (hotfix #3)"```

## Expected Behavior
The JSON with the auth code should be shown

## Current Behavior
![image](https://user-images.githubusercontent.com/5483362/198070383-8b142a95-a423-431d-8d34-9f590a3be91c.png)

## Steps to Reproduce
1. ``legendary auth --delete``
2. ``legendary auth``

## Additional information
A few people I know have had this issue - The webview (the default behavior) displays this error message. Using the ``--disable-webview`` flag (``legendary auth --disable-webview``) opens the link in the default external browser and does work as expected. Clicking cancel on the webview simply shows the Epic Games logo and nothing else.

**Comment by derrod** [comment]
Seems like the little workaround I added to make sure that existing cookies wouldn't be used was broken by Epic. Should be simple enough to fix.

**Comment by derrod** [comment]
Fixed in f80ceb50f3dc3182d99130d944a402efb4f5d085
