### ISSUE TITLE
pythonnet issue: Webview does not open in Standalone Windows executable

### ISSUE THREAD

**Issue by ranv1r** [derrod/legendary#494]
## Platform

Operating system and version: Windows 10.0.19044 Build 19044
Legendary version (`legendary -V`): Legendary v0.20.30 - "Dark Energy (hotfix #4)"

## Expected Behavior
By default, the standalone exe should open webview.

## Current Behavior
It does not open webview and instead opens web browser.

```
PS C:\> legendary -v auth
[cli] INFO: Testing existing login data if present...
[LGDLFS] DEBUG: Failed to load user data: FileNotFoundError(2, 'No such file or directory')
[WebViewHelper] DEBUG: Webview unavailable, disabling webview login (Exception: WebViewException('You must have pythonnet installed in order to use pywebview.')).
Please login via the epic web login!
If the web page did not open automatically, please manually open the following URL: https://legendary.gl/epiclogin
Please enter the "authorizationCode" value from the JSON response:
```

**Comment by ranv1r** [comment]
Actually it worked once i did
`pip install pythonnet`

**Comment by CommandMC** [comment]
I don't think this is solved yet, isn't the EXE supposed to include everything to get the Webview working?

**Comment by nutterthanos** [comment]
Like wasn't everything packed in the exe?

**Comment by ranv1r** [comment]
I am not sure how everything works but I did a pip install and it worked.
Seems like exe doesn't include all the required modules.


It might be useful to do a clean install on a system that does not have
pythonnet installed on it to reproduce the problem.

**Comment by ranv1r** [comment]
Also, while we are on this topic. I did not have the `chromiumedge` web engine installed on my PC. So I had to install that manually as well.



References
https://pywebview.flowrl.com/guide/renderer.html
https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section (I downloaded the x64 version)

**Comment by derrod** [comment]
> I don't think this is solved yet, isn't the EXE supposed to include everything to get the Webview working?

It should. At least on my Windows 10 test machine that doesn't even have python3 installed it works fine.
