### ISSUE TITLE
Launch command fails when parsing env variables in the config.ini file

### ISSUE THREAD

**Issue by arielj** [derrod/legendary#495]
## Platform
Operating system and version: Linux Mint 20.3
Legendary version (`legendary -V`): "0.20.30", codename "Dark Energy (hotfix #4)"

## Expected Behavior
A `[default.env]` or an `[someAppName.env]` configuration in the config.ini file should not make the command fail.

## Current Behavior

A `[default.env]` or an `[someAppName.env`] configuration causes legendary to fail with this error:

```
legendary launch 5b60142e120c4f2d88027595c21d4a04 --json
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
Traceback (most recent call last):
  File "legendary/cli.py", line 3054, in <module>
  File "legendary/cli.py", line 2969, in main
  File "legendary/cli.py", line 603, in launch_game
  File "legendary/core.py", line 703, in get_launch_parameters
  File "legendary/core.py", line 578, in get_app_environment
TypeError: unsupported operand type(s) for |=: 'dict' and 'dict'
[888706] Failed to execute script 'cli' due to unhandled exception!
```

## Steps to Reproduce
1. Open the config.ini file
2. Add a `[default.env]` section as specified in the readme https://github.com/derrod/legendary#config-file (I used `LC_ALL = es_ES` for example)
3. Try to run a game
4. Should fail with that error
5. Remove the `[default.env]` section
6. Game should launch now

Same happens when using `[someAppName.env]`

**Comment by derrod** [comment]
This is due to the version you're running using python3.8. If you're using my release binary then this was a mistake I made when originally uploading it, and you can grab the new/fixed one from releases.

**Comment by arielj** [comment]
thanks! using the binary from the releases works fine!
