### ISSUE TITLE
Error Launching STAR WARS™ BATTLEFRONT™ II on EA Desktop

### ISSUE THREAD

**Issue by CourteousGeek** [derrod/legendary#496]
## Platform

Operating system and version: Windows 11 Pro 22H2, 22621.755
Legendary version (`legendary -V`): legendary version "0.20.30", codename "Dark Energy (hotfix #4)"

## Expected Behavior

Successfully launch STAR WARS™ BATTLEFRONT™ II
## Current Behavior

Invalid license. Reason code = Invalid Cipher (0x0006)
## Steps to Reproduce

1. legendary launch --origin MtMassive
2. launches EA Desktop
3. Invalid license. Reason code = Invalid Cipher (0x0006) occurs
4. Error shown in picture below.
![ActivationUI_kObDAcxpOV](https://user-images.githubusercontent.com/77457021/199877297-1046f7e5-b024-40f1-8973-493954615e04.png)

**Comment by derrod** [comment]
All that Legendary does is run EA Desktop with an argument to launch the game, everything past that is probably EA's fault.

**Comment by jackbingow** [comment]
@CourteousGeek easier write batch file and launch from there.
containing commands to ealink

**Comment by Bananaman** [comment]
@CourteousGeek @jackbingow If you are using Legendary via the Heroic Launcher it contains a method of linking EA and Epic.

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/How-to-install-EA-Games-on-Linux

This will let you play all "EA app/origin" games.
