### ISSUE TITLE
Save Sync Deletes game files

### ISSUE THREAD

**Issue by dhales7** [derrod/legendary#497]
## Platform
Operating system and version: SteamOS 3.3.2
Legendary version (`legendary -V`): 0.20.28
Heroic Games Launcher version: 2.4.3

## Expected Behavior
When synchronizing saves, game files should not be deleted.

## Current Behavior
- Assume game files (executable, etc.) are under foo/game and save files are under foo/game/saves.
- The savepath specified is "foo/game".
- When saves are synchronized, everything under foo/game is deleted, and then new saves are downloaded and stored under foo/game/saves.
- However, this also means all the game files are deleted.

## Steps to Reproduce
Tested with PC Building Simulator 2 and with Heroic Games Launcher on SteamDeck
1. Open file explorer and navigate to where the game is saved. For example, /home/deck/Games/Heroic/PCBuildingSimulator2/
2. In the Heroic Games Launcher, go to game settings
3. Navigate to Save-Sync under Game Settings
4. Select "Force Download" in the Manual Sync Saves section
5. Click the Sync button in the Manual Sync Saves section
6. After a few seconds, you should see everything in the game's directory be deleted, and eventually a Saves folder is created with save files inside

## Additional information
An existing ticket in the Heroic Games Launcher project details a similar issue: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1457
However, someone commented that this may be an issue with legendary, which is why this issue is reported here.
I tried looking if a similar issue was already submitted to legendary but did not see one.

**Comment by derrod** [comment]
What does `legendary info <app name>` say for that game?

**Comment by dhales7** [comment]
Output of `legendary info 0449f415f5404df093b8d67c31940024`
 [PCBS_legendary_info_output.txt](https://github.com/derrod/legendary/files/9948953/PCBS_legendary_info_output.txt)

Tested the fix derrod just commited. Verified synchronizing saves no longer deletes game files. Hope the Heroic Games Launcher releases with the update soon as that's what I was originally using.

Tested with a build of legendary using AUR package: https://aur.archlinux.org/packages/legendary
1. Opened file explorer to monitor contents of /home/deck/Games/PCBuildingSimulator2/
2. Ran `legendary sync-saves 0449f415f5404df093b8d67c31940024 --force-download`
3. Verified game files were not deleted

As an extra check:
1. Checked out commit a6b19d2a95f21c80aefff741bbde744359d8d76f (10/26/2022) of AUR package.
2. Rebuilt package
3. Repeated the steps performed above
4. Verified games files were deleted again
5. Uninstalled and reinstalled game
6. Checked out latest commit (749f9cd27f067b1edecd582bbacf86fe43c448cb (11/06/2022)) of AUR package.
7. Rebuilt package
8. Repeated the steps performed above
9. Verified game files were not deleted
