### ISSUE TITLE
Inaccurate download and disk speeds reported

### ISSUE THREAD

**Issue by dylanmtaylor** [derrod/legendary#503]
I was told that this issue should be reported against this project as Heroic uses legendary for EGS. https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2095

## Platform

Operating system and version: Arch Linux (rolling)
Legendary version (`legendary -V`): 0.20.31 Dark Energy (hotfix #5)
## Expected Behavior

Download and disk speeds reported by legendary should reflect actual activity

## Current Behavior

With nothing else downloading except a game from the Epic game store, I am seeing less than half the download speed reported in the system monitor reflected in the Heroic launcher. Additionally, regardless of download progress, the disk usage stayed at 0 MB/s the whole time.

For the log, see the linked issue, https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2095

![image](https://user-images.githubusercontent.com/277927/204426325-4fa0d28d-65a1-464d-91e9-6f9d5c469530.png)

## Steps to Reproduce

Simply download a game and observe reported disk and network speeds.

## Additional information

This is using the Heroic launcher 2.5.0-beta.3 AppImage.

**Comment by derrod** [comment]
Thsi seems more like an issue with heroic, see what happens when running an install with legendary itself.

**Comment by dylanmtaylor** [comment]
> Thsi seems more like an issue with heroic, see what happens when running an install with legendary itself.

![image](https://user-images.githubusercontent.com/277927/204433861-e273697d-e1ac-48d4-ab19-e840a06f07a3.png)

How about that... yeah, looks good. Hmm. I wonder why it is inaccurate in Heroic if they are just parsing CLI output.
