### ISSUE TITLE
"access_token" exception when attempting login.

### ISSUE THREAD

**Issue by BoredmanDA** [derrod/legendary#513]
An access_token exception is thrown on any command that requires logging in.

## Platform

Operating system and version: Windows 10 (Home)
Legendary version (`legendary -V`): legendary version "0.20.31", codename "Dark Energy (hotfix #5)"

## Expected Behavior

Using any command that requires one to log in (be it `auth`, `list`, `launch [game]`, etc) should execute said command.

## Current Behavior

Attempting any of those commands will throw the following (with the exact lines varying slightly):
```
[cli] INFO: Testing existing login data if present...
[Core] INFO: Logging in...
Traceback (most recent call last):
  File "legendary\cli.py", line 3069, in <module>
  File "legendary\cli.py", line 2978, in main
  File "legendary\cli.py", line 81, in auth
  File "legendary\core.py", line 236, in login
  File "legendary\api\egs.py", line 128, in start_session
KeyError: 'access_token'
[15172] Failed to execute script 'cli' due to unhandled exception!
```

## Steps to Reproduce

1. In your command line of preference, run any command that causes legendary to try and log in
2. The unhandled exception (and its traceback) are spit out on the CLI
![image](https://user-images.githubusercontent.com/22851046/207507744-796b1a7b-5c41-468b-a193-f403cd860629.png)

## Additional information

- As shown in the above screencap, the exact line that allegedly causes the issue changes around in `cli.py`.
- Tried redownloading the current version, doesn't seem to fix it.

**Comment by PKPenguin321** [comment]
Just reported the exact same issue a minute before you: https://github.com/derrod/legendary/issues/512

If it's not just me then maybe it's something Epic did?
