### ISSUE TITLE
i cant seem to launch any games [fixed in the dev build]

### ISSUE THREAD

**Issue by user4302** [derrod/legendary#514]
## Platform
Operating system and version:
Legendary version (`legendary -V`): legendary version "0.20.31", codename "Dark Energy (hotfix #5)"

## Expected Behavior
the game should run

## Current Behavior
the game does not launch and i get an error instead

## Steps to Reproduce
1.run `legendary launch fortnite`
2.i get the error

## Additional information
![image](https://user-images.githubusercontent.com/32593782/207508712-ed610a39-0a56-4700-afc0-02a7a605d4d1.png)

i just finished the fortnite 25 gb update,
and then had another 7gb update after that,
and complete that as well.
(took 3 days with my 2mbps internet speed)

i get the same error if i run `legendary auth` or `legendary list-saves`

i havent updated the app.
it was working last month i believe.

**Comment by PKPenguin321** [comment]
Seems to be happening to everyone

**Comment by user4302** [comment]
> Seems to be happening to everyone

oh... i didnt see in the issue list. my bad

**Comment by user4302** [comment]
can confirm, this bug is fixed in the dev build
