### ISSUE TITLE
Workaround to switch accounts by replacing user.json no longer works?

### ISSUE THREAD

**Issue by h1yoko** [derrod/legendary#518]
## Platform

Operating system and version: Windows 10 21H2
Legendary version (`legendary -V`): `Legendary v0.20.31 - "Dark Energy (hotfix #5)"`

## Expected Behavior

It is possible to switch accounts by replacing the backed up user.json of a different account than the one being authenticated.
## Current Behavior

Login fails after replacing user.json with another account's one.
```
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[EPCAPI] WARNING: Login to EGS API failed with errorCode: errors.com.epicgames.common.oauth.invalid_token
[Core] WARNING: Resuming failed due to invalid credentials: InvalidCredentialsError('errors.com.epicgames.common.oauth.invalid_token')
[Core] INFO: Falling back to using refresh token...
[Core] INFO: Logging in...
[EPCAPI] WARNING: Login to EGS API failed with errorCode: errors.com.epicgames.account.auth_token.invalid_refresh_token
[Core] ERROR: Stored credentials are no longer valid! Please login again.
[cli] ERROR: Login failed, cannot continue!
```
## Steps to Reproduce

1. `legendary auth` with account A.
2. Back up the user.json for account A.
3. `legendary auth --delete`
4. `legendary auth` with account B. (and back up for B)
5. Replace the user.json with the one for account A.
6. When I try to `legendary launch`, it fails as shown in the log above.
7. (If I revert to the user.json for B, I can log in without problems.)
8. (After that, when I `legendary auth` with A again, this time B's login fails.)
## Additional information

I learned about this method from #189 1.5 years ago and have been able to switch accounts without any problems ever since.
Are there more steps besides replacing the user.json now, or is it impossible to do at all?

**Comment by derrod** [comment]
Running webview auth will log out the previous account and thus invalidate the login info. If you want to avoid that login without using the webview (`legendary auth ----disable-webview`).

**Comment by h1yoko** [comment]
I've actually tried with that too, but it didn't change the results.
