### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by hxka** [derrod/legendary#52]
https://www.epicgames.com/id/api/exchange only returns the following:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /id/api/exchange</pre>
</body>
</html>
```

**Comment by Caronte0** [comment]
Same for me. I'm using Ubuntu 20.04, and it's the same on both Chromium and Firefox.

**Comment by derrod** [comment]
Yeah seems like Epic changed that API, unfortunately the new one requires more steps and isn't easily usable in a Browser. I'll have to look into a better way to handle that.

**Comment by hxka** [comment]
Is it possible to sync credentials with EGL?

**Comment by derrod** [comment]
On Windows it is posisble to take over the EGL login session. On Linux that is not implemented.

**Comment by derrod** [comment]
I found a newer way, I'll make a release in a bit. Session import on Linux will follow sometime later since it requires a few extra steps to get the correct data from the WINE prefix.

**Comment by derrod** [comment]
https://github.com/derrod/legendary/releases/tag/0.0.17 is now out and fixes that issue. Logging in should work again now, the process is just slightly different.

Legendary PyPI packages are already updated, third party Linux packages will probably follow soon-ish.

**Comment by hxka** [comment]
Thanks for a speedy response! Meanwhile, I managed to reuse a EGL login by removing a few `os.name == 'nt'` checks and hardcoding `appdata_path`.
