### ISSUE TITLE
Option to download without saving to disk

### ISSUE THREAD

**Issue by Joly0** [derrod/legendary#521]
**Is your feature request related to a problem? Please describe.**

It would be useful to have an option to download games, but dont save them to disk. This could be a nice feature in environments with a lancache to prefill games
**Describe the solution you'd like**

An option to download games witohut saving them to disk. Something like --no-install or --only-download but without saving the downloaded files to the disk, but rather to ram and deleting them afterwards
**Describe alternatives you've considered**

**Additional context**

**Comment by loathingKernel** [comment]
Wouldn't this use case be satisfied by using a RamDisk? For example software like https://github.com/Zero3K/ERAM or https://sourceforge.net/projects/imdisk-toolkit/

**Comment by xemulat** [comment]
Some users have less than 6GiB of RAM. Some users with memory cleaners installed will encounter issues if theoretically your request could be made into a real thing. TL;DR: it's not possible.

**Comment by Joly0** [comment]
> Some users have less than 6GiB of RAM. Some users with memory cleaners installed will encounter issues if theoretically your request could be made into a real thing. TL;DR: it's not possible.

I dont think memory cleaners will be a problem and why should 6GiB or RAM be one? Its obvious files should get deleted after download, so RAM doesnt just go ham. Ofc files could also be downloaded to disk and get deleted afterwards, though that would include unnecessary disk usage and wear. So my idea was to download files to RAM and delete them afterwards. 

And even if memory cleaners are a problem: The solution i have in mind is for usage in a container or on a linux server, and i could bet noone would use a memory cleaner there. I dont think a typical user would want to save files to RAM (why should they?). Its a specific purpose targeted to be used in a Server environment to prefill a lancache.

Similar tools for other services already exist that do the same like steam-lancache-prefill oder battle-lancache-prefill. Those files download games from steam or battle.net, safe them to RAM and delete them afterwards

**Comment by CordBlaster** [comment]
If I understand this, this feature would just allow you to download a game without saving it anywhere on the local machine (not even in RAM) if possible. Am I right?

**Comment by Joly0** [comment]
> If I understand this, this feature would just allow you to download a game without saving it anywhere on the local machine (not even in RAM) if possible. Am I right?

Yes, exactly

**Comment by derrod** [comment]
With the way legendary is currently built making it just throw away data is actually not that easy to implement. Perhaps you could have it write to a fake (FUSE) filesystem that doesn't actually store anything but acknowledges writes as if it would? For example https://github.com/onedata/nullfuse

**Comment by Joly0** [comment]
> With the way legendary is currently built making it just throw away data is actually not that easy to implement. Perhaps you could have it write to a fake (FUSE) filesystem that doesn't actually store anything but acknowledges writes as if it would? For example [nullfuse](https://github.com/raphrfg/nullfuse), [nullfs](https://github.com/xrgtn/nullfs), [nullfs](https://github.com/yt1967/nullfs) (but a different one), or [NullcatFS](https://github.com/Asmageddon/NullcatFS) (I have not tested any of these)

Could it be possible to "write" files to os.devnull or something similar? My idea of using a container image for this purpose and then over complicating it with a fuse filesystem would negate the usefulness in my opinion, additionally, i dont think it would be possible then under windows.

**Comment by tpill90** [comment]
The functionality being requested in this issue should be now be covered by [tpill90/epic-lancache-prefill](https://github.com/tpill90/epic-lancache-prefill), which will **only** ever save downloaded data in ram, and won't ever write anything to disk.

@derrod  or @Joly0 Please feel free to close this issue when you have time.  Thank you
