### ISSUE TITLE
I am trying to port\run python code to 3.8

### ISSUE THREAD

**Issue by jackbingow** [derrod/legendary#526]
## Platform

Operating system and version:
Legendary version (`legendary -V`):
lastest

## Current Behavior
I am trying to port\run python code to 3.8 for Windows 7
got multiprocess spawn error
  File "<string>", line 1, in <module>
  File "C:\.....\AppData\Local\Programs\Python\Python38\lib\multiproces
sing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\,,,,\AppData\Local\Programs\Python\Python38\lib\multiproces
sing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\,,,,\AppData\Local\Programs\Python\Python38\lib\multiproces
sing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\,,,,\AppData\Local\Programs\Python\Python38\lib\site-packag
es\legendary\downloader\mp\manager.py", line 588, in run
    self.run_real()
  File "C:\.............\AppData\Local\Programs\Python\Python38\lib\site-packag
es\legendary\downloader\mp\manager.py", line 730, in run_real
    self.log.info(f' + Download\t- {dl_speed / 1024 / 1024:.02f} MiB/s (raw) '
Message: ' + Download\t- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)'

also tried Python 3.9 running using VxKex(search on github). 

log:
[cli] WARNING: The following exception occurred while waiting for the downloader
 to finish: OSError(9, 'Bad File descriptor', None, 6, None). Try restarting the
 process, the resume file will be used to start where it failed. If it continues
 to fail please open an issue on GitHub.
L:\legendary>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "....\lib\multiproces
sing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File \lib\multiproces
sing\reduction.py", line 84, in steal_handle
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] access denied

exe gives me FormatW error

**Comment by derrod** [comment]
Windows 7 and Python 3.8 are not supported.

**Comment by jackbingow** [comment]
@derrod I have source code for pre-3.9 build and trying to port url changes which url need to replaced to not get error 403 forbidden?
In future i maybe add fork to this repo.

**Comment by CommandMC** [comment]
Python 3.9 is already over 2 years old. Any OS lacking basic updates like this (be it Windows or Linux) cannot be supported

**Comment by jackbingow** [comment]
https://github.com/adang1345/PythonWin7/blob/master/3.9.0/python-3.9.0-amd64-full.exe using not
download anything just loops
these
  File "C:\Users\..............\AppData\Local\Programs\Python\Python39a\lib\site-packa
ges\legendary\downloader\mp\workers.py", line 50, in run
    job: DownloaderTask = self.q.get(timeout=10.0)
Traceback (most recent call last):
KeyboardInterrupt
  File "C:\Users\Dell5770\AppData\Local\Programs\Python\Python39a\lib\multiproce
ssing\queues.py", line 108, in get
    if not self._rlock.acquire(block, timeout):
  File "C:\Users\Dell5770\AppData\Local\Programs\Python\Python39a\lib\logging\ha
ndlers.py", line 1431, in emit
    self.enqueue(self.prepare(record))
KeyboardInterrupt
  File "C:\Users\...........\AppData\Local\Programs\Python\Python39a\lib\logging\ha
ndlers.py", line 1393, in enqueue
    self.queue.put_nowait(record)
  File "C:\Users\Dell5770\AppData\Local\Programs\Python\Python39a\lib\multiproce
ssing\queues.py", line 138, in put_nowait
    return self.put(obj, False)
@CommandMC   File "C:\Users.....\AppData\Local\Programs\Python\Python39a\lib\multiproce
ssing\queues.py", line 90, in put
    raise Full
    self.log.info(f' - Cache usage: {total_used:.02f} MiB, active tasks: {self.a
ctive_tasks}')
Message: ' - Cache usage: 32.00 MiB, active tasks: 32'

**Comment by derrod** [comment]
It's not supported, we won't help you.

**Comment by K4sum1** [comment]
This might help
http://board.eclipse.cx/viewtopic.php?t=445
