### ISSUE TITLE
Rocket league with BakkesMod on linux

### ISSUE THREAD

**Issue by NEsanya** [derrod/legendary#527]
**Is your feature request related to a problem? Please describe.**

I launched with wine `BakkesMod.exe` and `lengedary launch Sugar` and this is not works. 

**Describe the solution you'd like**

BakkesMod native support in lengedary. 

**Describe alternatives you've considered**

Support BakkesMod in Linux.

**Additional context**

Maybe it's my fault. I also tried `legendary launch Sugar --wallpaper ~/Games/bakkesmod/BakkesMod.exe` with `chmod +x BakkesMod.exe` and this is not working too

**Comment by derrod** [comment]
Issues are not to be used for game issues. I believe there's an entry on this wiki or the [EpicLinux](https://github.com/CommandMC/EpicLinux/wiki) one about this.
