### ISSUE TITLE
Installed size 0  verify files before install.

### ISSUE THREAD

**Issue by jackbingow** [derrod/legendary#528]
**Is your feature request related to a problem? Please describe.**

Installed size 0

**Describe the solution you'd like**

option/argument to verify files on install without present manifest from egs launcher.
checking file integrity before ask to install or not.
Then continue to redownload corrupted files.
if this present how to?
**Describe alternatives you've considered**

**Additional context**

**Comment by derrod** [comment]
Import, then repair.
