### ISSUE TITLE
Ability to export hashlist to .sha1 file feature request(3 line of code)

### ISSUE THREAD

**Issue by jackbingow** [derrod/legendary#529]
**Is your feature request related to a problem? Please describe.**

legendary list-files --hashlist just outputs to screen
**Describe the solution you'd like**

in for loop where it lists hash add 3 lines of code
modify existing
 if args.hashlist:
            for fm in files:
            with open(game.app_title+".sha1", "a") as f:#first line
               print(f'{fm.hash.hex()} *{fm.filename}', file=f)#second line
Or add these lines
if args.hashlistfile:
            for fm in files:
            with open(game.app_title+".sha1", "a") as f:#first line
               print(f'{fm.hash.hex()} *{fm.filename}', file=f)#second line

**Describe alternatives you've considered**

**Additional context**

**Comment by derrod** [comment]
Just pipe it to a file.

**Comment by jackbingow** [comment]
would be  convenient for novice who read  only program help

list_files_parser.add_argument('--hashlistfile', dest='hashlistfile', action='store', metavar='<path>',
                                   help='Output file hash list in hashcheck/sha1sum -c compatible format in file')
.....
   if args.hashlistfile:
for fm in files:
with open(args.hashlistfile+".sha1", "a") as f:#first line
print(f'{fm.hash.hex()} *{fm.filename}', file=f)#second line

I changed cli.py and
it works.
cli.py list-files  <appid> --hashlistfile <filename>
