### ISSUE TITLE
Executable search should be case-insensitive

### ISSUE THREAD

**Issue by CommandMC** [derrod/legendary#531]
## Platform
Operating system and version: Arch Linux
Legendary version (`legendary -V`): 0.20.31

## Expected Behavior
Legendary should import the game, searching for the executable case-insensitively. Note that this should probably only happen when on Windows / running a Windows game through Wine

## Current Behavior
When importing a game, Legendary makes sure that the main game executable exists. This is currently done using a simple `os.path.exists`. A problem manifests itself if the executable name set in the manifest does not match the actual executable's case. I've encountered this with Witcher 3, where the executable is named "redprelauncher.exe" in the manifest & "REDprelauncher.exe" on disk

## Steps to Reproduce
1. Install game with this issue (a combination of `legendary info` and `legendary list-files` can probably be used to find more affected games)
2. Uninstall it with `--keep-files`
3. Try to import it again

**Comment by derrod** [comment]
Does the game even launch in the first place if it has a case-mismatch in the executable name? Or does wine just kind of figure it out?

**Comment by CommandMC** [comment]
Wine searches for executables case-insensitively (just like Windows does)

**Comment by CommandMC** [comment]
Another fun thing I just thought about: No-one's going to do this, but it is technically possible to omit the file extension of an executable. Windows CMD (and Wine) will then look at the `PATHEXT` environment variable to find the file extension
So specifying `redprelauncher` when the file is named `REDprelauncher.exe` is technically also possible
