### ISSUE TITLE
How to download games into another drive or change the installation path into another drive.

### ISSUE THREAD

**Issue by SuperScorch** [derrod/legendary#539]
## Platform

Operating system and version:
Legendary version (`legendary -V`):

## Steps to Reproduce

1.
2.
3.
4.

**Comment by SuperScorch** [comment]
Please help me with this problem *read title*

**Comment by derrod** [comment]
Read the README or the help text.

**Comment by SuperScorch** [comment]
Where is that

**Comment by toxicrecker** [comment]
Use `legendary install --base-path="your_path" ...`

**Comment by SuperScorch** [comment]
thanks

**Comment by SuperScorch** [comment]
also can we enter the drive name or what do we have to add in you path

**Comment by SuperScorch** [comment]
Thanks so much i found that you have to just enter D:/filename/filename
