### ISSUE TITLE
Uninstalling a game while another game is being installed is "reverted" after installation ends

### ISSUE THREAD

**Issue by arielj** [derrod/legendary#544]
## Platform
Operating system and version: Linux Mint 21
Legendary version (`legendary -V`): `0.20.32 Dark Energy (hotfix #6)`

## Expected Behavior

If I uninstall a game while another game is installing, I expect the uninstalled game to not show up as installed after the installation of the other game completes.

## Current Behavior

When I uninstall a game while another game is being installed, the game is uninstalled correctly but then, when the other games finishes installing, the game I uninstalled shows up again as installed (though with a message saying it does not appear to be installed)

## Steps to Reproduce

Check the installed games:
```
$ legendary list-installed

Installed games:
 * Bad North Jotunn Edition (App name: Chives | Version: 2.00.5 | Platform: Windows | 0.21 GiB)
 * Rayman Legends (App name: Anchovy | Version: 1.00 | Platform: Windows | 5.68 GiB)

Total: 2
```

Start installing a new game:
```
$ legendary install 19927295d6e3467887d4e830d8c85963
...
```

In another window, uninstall one of the games that was installed:
```
$ legendary uninstall Chives
Do you wish to uninstall "Bad North Jotunn Edition"? [y/N]: y
[cli] INFO: Removing "Bad North Jotunn Edition" from "/home/ariel/Games/BadNorth"...
[cli] INFO: Game has been uninstalled.
```

Check installed games, the game was uninstalled correctly:
```
legendary list-installed

Installed games:
 * Rayman Legends (App name: Anchovy | Version: 1.00 | Platform: Windows | 5.68 GiB)

Total: 1
```

After the game installing in the other window ends, check the list of installed games:
```
legendary list-installed

Installed games:
 * Absolute Drift (App name: 19927295d6e3467887d4e830d8c85963 | Version: Win_202205111132 | Platform: Windows | 0.34 GiB)
 * Bad North Jotunn Edition (App name: Chives | Version: 2.00.5 | Platform: Windows | 0.21 GiB)
  ! Game does no longer appear to be installed (directory "/home/ariel/Games/BadNorth" missing)!
 * Rayman Legends (App name: Anchovy | Version: 1.00 | Platform: Windows | 5.68 GiB)

Total: 3
```

you can see Bad North is back, though legendary detected the folder is missing, but it should be there since the `list-installed` command that ran before didn't show the game

## Additional information

It looks like the current installed games file is cached when an installation starts and restored with the new game added instead of updating the actual current installed games file.

**Comment by derrod** [comment]
Running multiple instances of legendary at the same time is not supported, in the future I'll add a lock file to prevent it.
