### ISSUE TITLE
Fortnite installs wrong (as of may2023)

### ISSUE THREAD

**Issue by Spike1377** [derrod/legendary#557]
I reinstalled the Fortnite after not having the Fortnite folder/game for awile.
so this is completely unrelated to what happened in my last bug report #553

## General info

Operating system and version:
i5 6200u HD520
this happend on legendary version "0.20.32", codename "Dark Energy (hotfix #6)"
<a href="https://youtu.be/YTL0i5XzS7k?t=60">windows 10 ame</a>
see the vid? i used premade iso but now the website is diffrent, so i had to put a video link.
in seting it says:
Edition	Windows 10 Pro
Version	21H1
Installed on	‎27/‎07/‎2021 wow ive almost been using this installation of windows for 2 years
OS build	19043.1110
Experience	Windows Feature Experience Pack 120.2212.3530.0
but my coppy of windows isent the problem to this problem (i think(probably not))

## Expected Behavior

Fortnite installes properly with legendary
## Current Behavior
Fortnite looks like it installed properly but it installs wrong
when I would try to start the game it would chrach right before this screen:
![connecting screen](https://github.com/derrod/legendary/assets/113913612/1ea8ffd2-fe96-49fe-acfd-9fa7c8e1a619)
it would be black for a sec then chrach
## Steps to Reproduce
Install Fortnite with legendary and it seems to happen.
I fully reinstalled the game with legendary twice and it still happened.

## log
looks like it installs fine with no errors (use your imagination i didn't take a photo)

## pointless information that might be helpfull (that makes sense)
i ended up fixing it with the offishal epicgames client
i renamed D:\Games\Fortnite to D:\Games\Fortniteh and then used the epic games client to install fortnite at Fortnite at D:\Games\Fortnite for a min. then I closed the epic games client with task manager and deleted D:\Games\Fortnite and renamed D:\Games\Fortniteh back to D:\Games\Fortnite and opened the epic games client again and it started verifying. the reason i didn't fully reinstall the game with epic is because i wasn't bothered to wait another hour and a half for the game to install from scratch with the epicgames client so I used this workaround I made up on the spot.

why didn't i do legendery repeair on fortnite? you may ask
I didn't think to do so and I don't think It would of helped because as far as legendary was concerned Fortnite installed fine.

### this might be impotent:
after it verified it downloaded 8 gigs and i was able to launch it from epic games and even legendary (and then i spent an hour or 2 making this bug report)

nice now i can play fortnite on my core i5 6200u HD520 its definitely not gonna studer because of shader compiler times.

I have a ps4 but like pc is better, thats personal computer so a laptop technically counts as pc because it's a computer that I use for personal use.

**Comment by derrod** [comment]
This entire issue is incoherent at best, but you're also using some modified Windows which is unsupported. I've not heard of anybody else having issues like that either so I'm gonna close this.

**Comment by Spike1377** [comment]
ok nextime i will test it on somone elses computer before making a report.

**Comment by Spike1377** [comment]
test

**Comment by Spike1377** [comment]
wait do you tell people with random linux distros there os is not suported, becouse I dont think its ame falt the os works fine, but I might just haft to reinstall fortnite in linux to see if its Legendarys falt or ame
