### ISSUE TITLE
Adding Legendary games as Non-Steam game

### ISSUE THREAD

**Issue by Vthyarilops** [derrod/legendary#56]
Hi firstly thanks for the amazing project, as a Linux user this tool is amazing. Anyways the issue I'm having is adding Legendary games as a non-steam game (yes, i've manually corrected the path/launch options, tried using a bash script, even tried just adding a terminal emulator as a non-steam game and launching it manually from there) regardless of the method I use the game flashes "running" for 1 second but never actually opens, I have almost every other app added as non-steam game without issues (Lutris/POL/GOG games/Humble Games/etc). I've tried setting LD_LIBRARY_PATH without luck, I need to add to steam so I can stream the game to my TV, Sorry if this isn't the right spot for this issue, I post here because legendary is the only app behaving like this, thanks.

**Comment by rezzafr33** [comment]
I add samurai shodown neogeo collection as non steam game and it works.
![image](https://user-images.githubusercontent.com/275062/85097271-3b7e0180-b221-11ea-8ea9-87f5ea0317a3.png)
sometimes it won't launch because the game need an update.
![image](https://user-images.githubusercontent.com/275062/85097334-66685580-b221-11ea-8324-9fb2f90e8a4e.png)

**Comment by derrod** [comment]
Adding Legendary should work fine. It has to be run like a native app, so no Proton/SteamPlay. If you want to launch the game with Steam managing WINE/Proton you will have to add the game itself to Steam. For most games that is not an issue as long as they don't require online authentication.

**Comment by Vthyarilops** [comment]
This still doesn't work for me (at least on Ubuntu 18.04), it just flashes running for 1 second. Here is my non-steam launcher, and I've tried with multiple games, they launch outside steam no problem.
![Screenshot from 2020-06-19 13-39-44](https://user-images.githubusercontent.com/32111041/85164534-805e6400-b232-11ea-968b-8d5e48de1743.png)

**Comment by Vthyarilops** [comment]
I found the error I'm getting in ~/.steam/error.log the important lines are as follows:

[cli] INFO: Launching Moa...
Traceback (most recent call last):
  File "legendary/cli.py", line 1207, in <module>
  File "legendary/cli.py", line 1177, in main
  File "legendary/cli.py", line 464, in launch_game
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1637, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode character '\xe1' in position 17: ordinal not in range(128)
[13372] Failed to execute script cli
Game removed: AppID 0 "Sundered Eldritch Edition", ProcID 12843 
Uploaded AppInterfaceStats to Steam

**Comment by Vthyarilops** [comment]
The generic Linux binary doesn't seem to work through Steam, but using systems python3.8 and building from the repo fixed it, thanks
