### ISSUE TITLE
Allow selective downloads/tags modification after install

### ISSUE THREAD

**Issue by LuisMayo** [derrod/legendary#569]
**Is your feature request related to a problem? Please describe.**
Currently, once you've installed a game you can no longer install/uninstall components of the game without uninstalling and re-installing the whole game.

**Describe the solution you'd like**
A method to modify the installed components without re-installing everything

**Describe alternatives you've considered**
Uninstalling and re-installing the games. Which isn't really optimal
**Additional context**
Just for the sake of explanation, I'll give an example.

Imagine you install Fortnite free. And later you decide to buy "Save The World". However you didn't install it to save disk space. You can't add it to your existing installation and you have to uninstall and re-install instead.

Thanks a lot!

**Comment by CommandMC** [comment]
You can already do this with `legendary repair --reset-sdl`

**Comment by flavioislima** [comment]
> You can already do this with `legendary repair <AppName> --reset-sdl`

I think what he means is something like the DLCs, that you would have a command to remove and add new SDLs.

Something like:
`legendary install Fortnite --sdl tag1, tag2`
OR
`legendary uninstall Fortnite --sdl tag1, tag2`

This would make it simpler to implement on Heroic as well, that is the source of this request.

**Comment by derrod** [comment]
The former is now possible with 96b155800a63be9cd30254eb6091194c5f9c5c35 (though you'll have to use `--install-tag <tag>` as previously). The latter has been possible for a while, though somewhat counterintuitively you have to run `legendary install` still. But it will automatically clean up files that are no longer needed once it exits.

**Comment by flavioislima** [comment]
That's great, thanks @derrod 👍
