### ISSUE TITLE
Legendary can only be launched using `/usr/bin/python3`

### ISSUE THREAD

**Issue by Ahmed-E-86** [derrod/legendary#572]
## Platform
Operating system and version: Linux Mint 21.1 (Ubuntu 22.04)
Legendary version: legendary version "0.20.33", codename "Undue Alarm"

## Details
I installed the application using the latest .deb file. After launching the application, it gave me an error message, and I figured out from the error message that the application is launched using **python** not **python3**, so I opened `/usr/local/bin/legendary `, and edited the first line:
```
#!/usr/bin/python3
```
And it launched successfully.

**Comment by mirao** [comment]
I hit the same issue on Ubuntu 23.04, after upgrade of Legendary from 20.32-1 to [0.20.33](https://github.com/derrod/legendary/releases/download/0.20.33/python3-legendary-gl_0.20.33_all.deb)
``` bash
$ legendary
bash: /usr/local/bin/legendary: cannot execute: required file not found
```

I modified the shell in `/usr/local/bin/legendary` to `#!/usr/bin/python3`.

But I'm getting this error:
```
$ legendary
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/legendary", line 33, in <module>
    sys.exit(load_entry_point('legendary-gl==0.20.33', 'console_scripts', 'legendary')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/legendary", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for legendary-gl
``` 

Any idea?

I downgraded to Legendary 20.32-1 and it works well.

**Comment by CommandMC** [comment]
If your `python` isn't already `python3`, you have bigger issues. Python 2 has been dead for years, don't use it.

@mirao Your issue here is that you've installed Legendary for python2 (or some version other than python311), but you're now telling py311 to run Legendary. You can usually resolve this by re-installing Legendary (if you *are* running Python3 alongside Python2, you might have to use `pip3` instead of `pip`)

**Comment by mirao** [comment]
I did this:
```bash
$ sudo apt install python-is-python3
$ sudo apt purge python3-legendary-gl
$ sudo dpkg -i ~/Downloads/python3-legendary-gl_0.20.33_all.deb 
```
but still no success. Legendary fails to start.
Python2 isn't installed in my system.

**Comment by baryluk** [comment]
The cli.py should be updated to

```
#!/usr/bin/env python3
```


This is a common practice, and correct thing to do.

On many (almost all) distros, `python` simply does not exist, and when it existed it was python 2  (to allow coexistence).

> If your `python` isn't already `python3`, you have bigger issues.

That is not the case here.

`python` should never be `python3`.

Only broken software assumes so.

If you read details of PEP-394 you will find that in fact using `python3` is the best and most bullet proof option:

> Even as the Python 2 interpreter becomes less common, it remains reasonable for scripts to continue to use the `python3` convention, rather than just `python`.
