### ISSUE TITLE
Upgrade to v0.20.33 Failed Using Scoop Due to Hash Mismatch

### ISSUE THREAD

**Issue by Kosette** [derrod/legendary#573]
The `Scoop upgrade` to v0.20.33 has failed due to a hash mismatch. 

It appears that `legendary.exe` has been updated since the initial release, causing its `sha256sum` to change to `a64ba3d2a8b71ac8fc396320e7514e3b526e930bc2cc26c05967c3e31c46b130`. However, the Scoop manifest still shows the old hash as `96660fd24660362b99c877b798250ca8c82bb06576614e2e16ede7827484eb41`. 

It is unclear whether this issue will be resolved, as Scoop is currently using the github-action-bot to update its buckets. The upgrade will not be successful until the hash is corrected.

**Comment by derrod** [comment]
Wwll that sounds like a scoop priblem, not mine.
