### ISSUE TITLE
Update game metadata only (i.e., assume game files are up to date)

### ISSUE THREAD

**Issue by guihkx** [derrod/legendary#579]
**Is your feature request related to a problem? Please describe.**

When sharing a game folder between Windows and Linux on the same machine, you often encounter the annoying problem of having to update the game in one OS, and then later having to recheck the same game files in the other OS. For example:

- https://github.com/derrod/legendary/discussions/453

Besides the time wasting problem that is having to wait for legendary to check every file, this could also negatively impact the lifespan of disks.

**Describe the solution you'd like**

I'd like to have an option to only update the metadata files for a specific games, meaning that legendary wouldn't touch game files at all.

**Describe alternatives you've considered**
I've been manually editing some files, just so I don't have to recheck everything when I switch OSes. Here are the rough steps:

1. Copy the updated `*.manifest` file from OS 1, located in `~/.config/legendary/manifests` and paste it into the same folder from OS 2
2. Copy the updated `*.json` file from OS 1, located in `~/.config/legendary/metadata` and paste it into the same folder from OS 2
3. Copy the updated `~/.config/assets.json` file from OS 1 into the same folder from OS 2
4. Open the `~/.config/installed.json` file in both OSes with a text editor
5. Based on the `installed.json` file from OS 1, modify the following JSON keys in `installed.json` from OS 2:
    - `install_size`
    - `version`
6. Save the file

**Comment by derrod** [comment]
This is simply not a supported use-case. And not one I care to support either.
