### ISSUE TITLE
Ubuntu 22.04 download fails with file-locking exception using  python3-legendary-gl_0.20.33_all.deb 

### ISSUE THREAD

**Issue by heckert-gamedev** [derrod/legendary#585]
## Platform
Operating system and version:
(K)ubuntu Linux 22.04.2
(Very recent installation from scratch)

Legendary version (`legendary -V`):
legendary version "0.20.33", codename "Undue Alarm"

Installation via provided release `.deb` package, with the package dependencies as lists and also (this dependency is missing) `python-is-python3`.

```
ii  python3-requests                                            2.25.1+dfsg-2ubuntu0.1 
ii  python3-setuptools                                          59.6.0-1.2ubuntu0.22.04.1
ii  python3-wheel                                               0.37.1-2ubuntu0.22.04.1 
ii  python3-filelock                                            3.6.0-1
ii  python-is-python3                                           3.9.2-2
ii  python3                                                     3.10.6-1~22.04 
```

## Expected Behavior
Issuing a `legendary download GAMENAME` installs the game.

## Current Behavior
Login worked. Listing my library and showing info works.
Downloading fails:

```
bash$ legendary download 'Game name'
Traceback (most recent call last):
  File "/usr/local/bin/legendary", line 33, in <module>
    sys.exit(load_entry_point('legendary-gl==0.20.33', 'console_scripts', 'legendary')())
  File "/usr/local/lib/python3.10/dist-packages/legendary/cli.py", line 3054, in main
    cli.install_game(args)
  File "/usr/local/lib/python3.10/dist-packages/legendary/cli.py", line 802, in install_game
    if not self.core.lgd.lock_installed():
  File "/usr/local/lib/python3.10/dist-packages/legendary/lfs/lgndry.py", line 310, in lock_installed
    self._installed_lock.acquire(blocking=False)
TypeError: BaseFileLock.acquire() got an unexpected keyword argument 'blocking'
```

## Steps to Reproduce
1. Install Ubuntu
2. Install prerequisite Python-packages (as listed above)
3. Install `legendary` with `dpkg -i`
4. Login to EPIC
5. Ty to download game

**Comment by derrod** [comment]
Seems like the OS package is outdated (because of course it is). I'll probably discontinue the .deb files at this point because it's just too much of a hassle and pip is a saner way of dealing with this anyway.

**Comment by heckert-gamedev** [comment]
I tried to install it on another machine which has an older installation with Ubuntu 20.04.
In theory this should be possible but in practice it fails on the dependency to `python3` as being 3.9 at least.
The default package for `python3` on that machine is `python3.8.2` and additionally installing the package `python3.9` didn't help the dependency...

```
 Depends: python3-requests (<< 3.0), python3-setuptools, python3-wheel, python3-filelock, python3 (>= 3.9)
 ```

**Comment by heckert-gamedev** [comment]
> Seems like the OS package is outdated (because of course it is).

The packaging issue is probably caused by not doing it in a clean sandbox and thus directly installed libraries that would be missing (or as in this case incompatible versions) are thus not detected as would be needed...

I usually prefer `.deb` packages since they prevent me from having to add libraries outside of the OS' management (for stuff I just want to use, not develop)...

**Comment by heckert-gamedev** [comment]
What did work is the release download `legendary` which apparently is a standalone packaged version. (like an AppImage).
I didn't really realize at first that this articat is whaat I needed :)

**Comment by heckert-gamedev** [comment]
Not exactly a solution for the `.deb` package, but a suitable mitigation.
