### ISSUE TITLE
Can't authenticate: Login to EGS API failed

### ISSUE THREAD

**Issue by Tooniis** [derrod/legendary#588]
## Platform

Operating system and version: Arch Linux
Legendary version (`legendary -V`): 0.20.23
Using AUR package: https://aur.archlinux.org/packages/legendary

## Expected Behavior

`legendary auth` opens a login browser tab then asks for the authentication token

## Current Behavior

It doesn't, saying this instead:
```
[cli] INFO: Testing existing login data if present...
[Core] INFO: Logging in...
[EPCAPI] ERROR: Login to EGS API failed with errorCode: errors.com.epicgames.account.auth_token.invalid_refresh_token
[Core] ERROR: Stored credentials are no longer valid! Please login again.
```
It hangs here afterwards.

## Steps to Reproduce

1. `legendary auth`

**Comment by derrod** [comment]
Should be fixed by b759d9dbb19c7bc88e87b74c93c95fe0d590feeb, for now run `legendary auth --delete` to manually clear the expired login data and login anew.
