### ISSUE TITLE
assassins creed: Valhalla not launching

### ISSUE THREAD

**Issue by leder11011** [derrod/legendary#592]
## Platform

Operating system and version: 6.3.6-060306-generic #202306050836 SMP PREEMPT_DYNAMIC Mon Jun  5 08:46:35 UTC 2023
Legendary version (`legendary -V`): legendary version "0.20.33", codename "Undue Alarm"

## Expected Behavior
Game launches without error

## Current Behavior
```
leder@home-ryzen:~$ assassins_creed 
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching 965ccf8b2eba4f9381ef43183c08e205...
leder@home-ryzen:~$ 0054:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\nsiproxy": c0000003
```

## Steps to Reproduce

1. legendary auth
2. legendary list-installed
3. legendary launch
4.

**Comment by derrod** [comment]
That seems to be a wine or configuration issue, not a legendary one. For help getting games running ask for help on our Discord or other wine related forums.
