### ISSUE TITLE
cannot login because im not logged in

### ISSUE THREAD

**Issue by aquakenzie** [derrod/legendary#594]
## Platform

Operating system and version: Ubuntu 22.04.2
Legendary version (`legendary -V`): 0.20.33

## Expected Behavior
`legendary auth` prompts you to login

## Current Behavior

`legendary auth` says it cannot log in because im not logged in

## Steps to Reproduce

1. be logged in
2. wait for login to expire
3. `legendary auth`

## Additional information

picrel 
![image](https://github.com/derrod/legendary/assets/138723298/ba00ddb9-10d9-4647-996d-3850685a18af)

**Comment by derrod** [comment]
This bug is fixed in master (b759d9dbb19c7bc88e87b74c93c95fe0d590feeb), for now just manually delete the existing data using `legendary auth --delete`.
