### ISSUE TITLE
Updating IdleChampions with this breaks the game

### ISSUE THREAD

**Issue by THDigi** [derrod/legendary#597]
`legendary.exe install "idlechampions" --update-only`

It downloaded stuff and then a bunch of errors that it can't delete files, no idea what that was about.
Then when I launched it with legendary it started but it had black screen.

I suspect this game might require some special post-update things to run or delete (the game uses a sort of downloadable definition system so they can update stats without pushing an actual game update).

I then launched EGS and it proceeded to download updates itself.
Then launched it from legendary again and it was fine.

## Platform
Operating system: Win10 22H2
Legendary version: v0.20.33

## Expected Behavior
It should update the game so that it works just like the EGS launcher would.

## Current Behavior
It updates in a way that makes the game launch in a weird state, stays black screen.
I've no idea where this program's logs are.

## Steps to Reproduce
1. Get an older version of IdleChampions game (it's a free game, and you probably know a way to change the manifest to think it's got an older version).
2. Update using `legendary.exe install "idlechampions" --update-only`
3. Launch game from legendary too (I used `legendary.exe launch 40cb42e38c0b4a14a1bb133eb3291572 --skip-version-check`)

**Comment by ajvaughan** [comment]
I use legendary to update and launch Idle Champions regularly and have never had an issue, so I'm not sure what caused Digi's problems.

**Comment by THDigi** [comment]
I tried it again just now and still blank screen when starting game after update.

Here's the command line I used and what happened:
[console.txt](https://github.com/derrod/legendary/files/14870533/console.txt)

I tried the non-update-only command after I launched it and it failed (using a .bat that I've used for a long time and is unlikely to be an issue but I can post that too if needed)

Then the game itself (with console open, hold click and rotate mouse in a circle): 
![image](https://github.com/derrod/legendary/assets/844339/3595fc53-557c-4b44-8d8e-359fe6700c2f)

Now I've renamed that folder and told legendary to download it fresh: `legendary.exe install idle --base-path C:\Games`

And it works fine. So only updating breaks for some reason 🤷

**Comment by THDigi** [comment]
Another update came and I first unset readonly from that file and updated, and it updated fine.
Pretty weird that a readonly file can break other files (resources.assets) from being updated.

**Comment by derrod** [comment]
Closing as per above, this is not an issue with Legendary.

**Comment by THDigi** [comment]
It doesn't happen with EGS client though.
Even if the issue is in the API would still be nice for users to be aware of it by checking readonly files and telling them to un-readonly to avoid problems.
