### ISSUE TITLE
[Suggestion] csv / tsv friendly output of `list-games` command

### ISSUE THREAD

**Issue by murlakatamenka** [derrod/legendary#6]
That'd make trivial to pick the right game to download by its `AppName` with a fuzzy finder like `skim` or `fzf`:

Current:

```
  * Inside (App name: Marigold, version: 1.0.0)
  * Into The Breach (App name: Blobfish, version: 1.2.22)
```

Sample alternative (tab-separated in this case):

```
 Marigold	Inside	1.0.0
 Blobfish	Into The Breach	1.2.22
```

To pick AppName(s) one can run:

```sh
legendary list-games | sk --multi --nth 2 | cut -f 1
```

and pipe output to download / install commands. Humans surely aren't great in reading dozens of lines of text and parsing them for `AppName` :)

Using fuzzy finder with current output is still recommended to anybody.

**Comment by derrod** [comment]
Fair point though keep in mind that app names can be anything from `Jay` to `0afb9d54dd3743a582b48b506466d3f8`. That's the main reason I decided to have a simple alphabetical sorted list of titles to find the game first and then the app name. I suppose I could adjust the tab width based on the longest name in the list of available titles but that still feels like it could get messy.

Alternatively a native search (e.g. `legendary search Minesweeper`) might make more sense than adjusting the output to be compatible with other tools.

**Comment by murlakatamenka** [comment]
Thanks.

As long as app name doesn't have a separator in it it should be fine, it'd be used to pipe into anything else anyway. Surely `Jay` is easier for humans to memorize/use than some hash.

I don't know how much effort will go into CLI since GUI is planned, but there is pythonic interface to `fzf` that you may find useful for the project:

https://github.com/dahlia/iterfzf

**Comment by mynamewastaken** [comment]
I have a PR coming in for CSV format sometime today.

**Comment by murlakatamenka** [comment]
Awesome, thanks! :+1:
