### ISSUE TITLE
Downloaded files are lost when restarting installation

### ISSUE THREAD

**Issue by loremed** [derrod/legendary#60]
I tried installing a couple games worth 50 GIB or so. When i restart the download after stopping it with Ctrl+C each game has a different "maximum already downloaded size". For example when resuming Kingdom Come: Deiiverance if I have already downloaded less than 121.23 MiB the reusable size shown before resuming it shows the correct downloaded amount; anything more than that is capped at 121.23 MiB. The installation folder might be several GiBs but when I resume the installation everything gets deleted apart from 121.23 MiB and the download goes on from there.
For example, for Just Cause 4 this threshold is 8.31 MiB.
I have already installed smaller games (max 2 GiB) without any issue even when stopping them multiple times but this threshold for these games might even be bigger than the total download size.
I'm sorry if this is a bit confusing, first time writing an issue report of this kind

**Comment by derrod** [comment]
This is not a bug. What you're seeing is that the current basic resume system cannot resume incomplete files and has to start from the last completed file. In the case of Kingdom Come the file downloaded after the first 121 MiB is about 1.8 Gigabytes in size, if you wait until it has been downloaded completely and then abort, the reusable size will read 1975.30 MiB.

**Comment by loremed** [comment]
Okay, I didn't see that it was the same file. Sorry! :D
I should have checked :see_no_evil:
