### ISSUE TITLE
[cli] logs go to stderr

### ISSUE THREAD

**Issue by blackxfiied** [derrod/legendary#606]
is this intentional? if so, why?
I'm making a games launcher in swiftUI (should be privated as of now, but should be up soon at https://github.com/blackxfiied/Mythic) and making use of legendary. Of course, I need to be able to interface with legendary, so I made a parser to do so. It splits stderr and stdout from each other, but errors and [cli] logs go to stderr, not just actual errors

I've confirmed that it's not the code's fault by running `legendary list 1>/dev/null` and I get this as output:

```
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Getting game list... (this may take a while)
```

**Comment by derrod** [comment]
Writing log output to `stderr` is pretty standard in most logging frameworks and application. That way you can still pipe data out of the application without having to filter it. For instance, if you use legendary's `--json` flag for commands you can simply read the `stdout` for that, while all the logging information remains in `stderr`.

**Comment by blackxfiied** [comment]
okay thanks
sorry, i'm a little new to all of this stuff
apologies if I inconvenienced you
