### ISSUE TITLE
is there a way to get games for all platforms using legendary on macOS?

### ISSUE THREAD

**Issue by blackxfiied** [derrod/legendary#607]
Because unless you specify `--platform`, it returns the games for the default platform.
However, creating a games launcher that uses crossover means that you ideally want to get both platforms and games with both platforms so you can have some native games, and some crossover games.

is there a way to say `--platform both` or will I just have to compare the json outputs?

**Comment by loathingKernel** [comment]
The default platform is Windows, de-facto all games will be present in that platform. After you have the games list you can do `legendary info <app_id> (--json)` to get information for any specific game, which includes the available platforms for that game.

I think this kind of questions are a better fit for GitHub Discussions, these are not issues with legendary but rather questions, I would say Issues is not the right place for them.

I don't know if you are aware of them, but there are already two quite mature UIs for legednary, Heroic being the more well known and developed, and Rare which focuses solely on Epic games and they have already addresses these kind of issues and either of these could use the help.
