### ISSUE TITLE
Relative paths should be saved as absolute paths

### ISSUE THREAD

**Issue by turtlewit** [derrod/legendary#61]
When importing a game (and I assume also when installing one), if you pass a relative path to a folder such as:
```
legendary import-game SomeGame path/to/MyGame
```
the path to the game seems to be saved as a relative path. When launching or otherwise interacting with this game later on, you have to be in the same folder as you were when initially importing the game, otherwise it will fail to find the folder. 

Edit: It appears wine complains about the relative path anyway, so the game can't be launched at all if you give it a relative path. Fixed by editing the given path in `installed.json`.

(PS: Thank you for making such a great launcher!)

**Comment by PrzemekSkw** [comment]
Hello @turtlewit I have problem in launching games with legendary I describe in [https://github.com/derrod/legendary/issues/81](url). I don't understand how to change path in `installed.json` and don't understand my problem is related to this.
Regards.
