### ISSUE TITLE
Cannot install Kerbal Space Program

### ISSUE THREAD

**Issue by gxapplications** [derrod/legendary#611]
## Platform

Operating system and version:
CPU: 2x Intel(R) Pentium(R) CPU        G6950  @ 2.80GHz
Memory: 3.96 GB (used: 1.75 GB)
GPUs:
    Name: NVIDIA Corporation GM107 [GeForce GTX 750 Ti]
    IDs: D=1380 V=10de SD=362d SV=1458
OS: Kubuntu

Legendary version (`legendary -V`): 0.20.33

## Expected Behavior

KSP game can be installed:
` legendary install a1e2ce30defe4a9187ebc14fc9d2bd8b `

## Current Behavior
```
Traceback (most recent call last):
  File "/usr/local/bin/legendary", line 33, in <module>
    sys.exit(load_entry_point('legendary-gl==0.20.33', 'console_scripts', 'legendary')())
  File "/usr/local/lib/python3.10/dist-packages/legendary/cli.py", line 3054, in main
    cli.install_game(args)
  File "/usr/local/lib/python3.10/dist-packages/legendary/cli.py", line 802, in install_game
    if not self.core.lgd.lock_installed():
  File "/usr/local/lib/python3.10/dist-packages/legendary/lfs/lgndry.py", line 310, in lock_installed
    self._installed_lock.acquire(blocking=False)
TypeError: BaseFileLock.acquire() got an unexpected keyword argument 'blocking'
```

## Steps to Reproduce

` legendary auth ` then auth process, working well
` legendary list ` giving the list :
```
Available games:
 * Kerbal Space Program (App name: a1e2ce30defe4a9187ebc14fc9d2bd8b | Version: KSP.1.12.5.win64.full)
Total: 1
```
` legendary install a1e2ce30defe4a9187ebc14fc9d2bd8b ` that fails

**Comment by derrod** [comment]
Seems like the `filelock` python library on your system is out of date. Needs to be at least 3.7.0.

**Comment by gxapplications** [comment]
`python -V` gives me 3.10.12

**Comment by gxapplications** [comment]
To test rights, also tested in sudo mode, same result
