### ISSUE TITLE
Easy Anti Cheat is not downloaded

### ISSUE THREAD

**Issue by JoeTheGuy2008** [derrod/legendary#624]
The problem with this whole shebang is that it works up until the game is finished installing. It proceeds to ask me to install the Easy Anti Cheat that comes with a number of games that I have played before, in this case good old Fortnite. I of course don't want to (and can't) skip this crucial part of the process, so is there a command I can run to download said anti cheat program? A response would be greatly appreciated.

Sincerely,

JoeTheGuy2008.

**Comment by derrod** [comment]
EAC is part of the game install, legendary will ask you if you want to install the redistributables that come with the game. But you can also just manually run the installer (see `legendary info <app name>` for the paths/commands).

**Comment by JoeTheGuy2008** [comment]
Thanks, I’ll give it a shot.
