### ISSUE TITLE
Don't fork in background

### ISSUE THREAD

**Issue by DocMAX** [derrod/legendary#637]
I have this line in my script.

legendary launch --wine /usr/bin/wine "$epic_id"

Problem is it doesn't stay in foreground so i can't wait for the process and get the return code.
Is it possible to let it run in foreground with a switch or so?

legendary launch --dont-fork --wine /usr/bin/wine "$epic_id"

Thanks.

**Comment by loathingKernel** [comment]
Reasoning why it is not implemented: https://github.com/derrod/legendary/pull/524

Alternative: https://github.com/derrod/legendary/issues/601

**Comment by DocMAX** [comment]
oh sorry, asked this question months ago myself. stupid me. reaper. very cool tool. i saw it in the steam processes allready.
