### ISSUE TITLE
URL Handlers for com.EpicGamesLauncher links (like from Discord)

### ISSUE THREAD

**Issue by badlydrawnface** [derrod/legendary#64]
that would be nice to see these so I can join a friend in Fortnite from discord.

**Comment by derrod** [comment]
I'm not sure if that is possible. Legendary doesn't and probably never will support the social features of the EGS app. Depending on how those join links work (if they basically just launch the game with a certain command line) that might at least be possible however.

**Comment by badlydrawnface** [comment]
yeah like that, its a url handler (xdg-open esque)
