### ISSUE TITLE
fortnite keep uninstalling

### ISSUE THREAD

**Issue by impastamogus** [derrod/legendary#640]
i have a problem with legendary 
the problem is that like 1 day after i installed fortnite, it uninstall on his own and it keep doing it
i don't know why that happens so please help me i am tired of reinstallin ghte game every day

**Comment by derrod** [comment]
It's just preventing you from making a mistake.

(Also the issue template isn't filled out so I'm closing this)

**Comment by impastamogus** [comment]
i dont know what the mistake is tho i still have the problem
