### ISSUE TITLE
Epic friends/lobbies not working properly

### ISSUE THREAD

**Issue by rKsanu2MMYvypWePtQWM** [derrod/legendary#65]
Game: Killing Floor 2
While legendary user sees online friends in the lobby invitation list and is able to successfully invite them, others see the legendary user as "offline". Other lobby items like player perks don't sync (legendary user does not see other players perk, and other players cannot see perks of the legendary user), and lobby chat does not function either.

**Comment by derrod** [comment]
Legendary won't support Epic's social features, at least not for a long time. In most games they're entirely integrated into the game via the Epic Online Services SDK, but it seems Killing Floor 2 doesn't do that for some reason.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
RIP. Well, thanks for quick heads-up - I guess I'll have to try running real epic launcher in wine/proton.

**Comment by derrod** [comment]
Killing Floor 2 also appears to use the EGS Overlay, which obviously isn't part of Legendary (and probably will never be). Interestingly on Windows this still works when the game is launched via Legendary, so perhaps running it in a WINE prefix that has the Epic Games Launcher installed is sufficient to get it working properly.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
Unfortunately I've already uninstalled KF2, so I can't test it further. I'm sure this free promo will bring talented people who'll find a way for it work and/or make a lutris config in the next few days.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
Just a quick update, might be relevant - the Steam version of the game (running with proton 5 by default in steam) also does not show other players perk. The chat doesn't work too. It seems it's not related to this issue. Same happened when I was running the epic version through epic launcher via Lutris.
