### ISSUE TITLE
Logging in failed with JSONDecodeError

### ISSUE THREAD

**Issue by lepz0r** [derrod/legendary#662]
## Platform

Operating system and version: Arch Linux
Legendary version (`legendary -V`): legendary version "0.20.34", codename "Direct Intervention"

## Expected Behavior

Logged in successfully

## Current Behavior

Got JSONDecodeError
```
[Core] ERROR: Logging in failed with JSONDecodeError('Expecting value: line 1 column 1 (char 0)'), please try again.
[cli] ERROR: Login attempt failed, please see log for details.
```

## Steps to Reproduce

1. Just login using `legendary auth`

**Comment by henrebotha** [comment]
@lepz0r Why is this closed?
