### ISSUE TITLE
Download Unreal Engine partially with "Core Components"

### ISSUE THREAD

**Issue by BorMor** [derrod/legendary#664]
Hello, I want to download Unreal Engine 5 partially, only **Engine** and **Source Code** for example. 

I use `legendary.exe list-files UE_5.4` and it produces
```
*** billion files here ***
[cli] INFO: Install tags: editor_symbols, engine_source, platform_Android, platform_IOS, platform_Linux, platform_TVOS, starter_content, templates
```
But **Engine** itself isn't present there. So when I try `legendary install --install-tag engine_source UE_5.4`
```
[DLM] INFO: Found 0 missing files.
[DLM] INFO: Found 232666 files to skip based on install tag.
[DLM] INFO: Remaining files after filtering: 25941
[cli] INFO: Install size: 336.88 MiB
[cli] INFO: Download size: 63.90 MiB (Compression savings: 81.2%)
```
Looks like that's only a `engine_source ` without **Engine**

How it looks inside EGS
![image](https://github.com/user-attachments/assets/1101f513-6786-456e-b627-063230c13e2e)

**Describe the solution you'd like**
I don't know how exactly EGS works,  but maybe "Core Components" are all files which not included in any install tags?

May be legendary needs option "--exclude-install-tag" where I may list all not interesting tags?

**Describe alternatives you've considered**

Or maybe there are files that not present in any tags, make "meta" install tag `excluded` for example, which will download files not listed in any tags?

**Additional context**

Or maybe I just wrong how it works, and maybe there are already working solution but I didn't read the legendary's docs carefully enough.

**Comment by derrod** [comment]
What you want is to install the "empty" install tag via `--install-tag ""`

**Comment by BorMor** [comment]
Ohhh, I tried `--install-tag ""`, but powershell needs to escape quotes ``--install-tag `"`"``, now it works. Thank you
