### ISSUE TITLE
Lan sharing 

### ISSUE THREAD

**Issue by Koriebonx98** [derrod/legendary#671]
**Is your feature request related to a problem? Please describe.**
 add lan sharing to save data

**Describe the solution you'd like**
 add lan sharing so then if multiple PC’s on same network can share files, this will save data from being re-downloaded when it’s available locally like steam does.

**Describe alternatives you've considered**

**Additional context**

**Comment by CommandMC** [comment]
Legendary is not running in the background, so this would be impossible

You can alternatively just copy game files from one PC to the other (Windows has this built-in for example), and then use `legendary import` to add them into your installed game list

**Comment by Koriebonx98** [comment]
I use playnites addon so in theory this would then be running in the background while playnite is open. 

This would benefit this on local networks saving bandwidth. 

Copy and pasting would be a bit longer where as it would more effective if had support for this.

please consider

**Comment by CommandMC** [comment]
> I use playnites addon so in theory this would then be running in the background while playnite is open.

You'd have to talk to the Playnite add-on's developers then. It is not maintained here.

> Copy and pasting would be a bit longer where as it would more effective if had support for this.

In terms of implementation, copy-pasting files manually vs LAN sharing is the same thing, so I don't see why one would take longer than the other. In terms of workflow, I do see your point.
The problem there is: If LAN caching were to be implemented into Legendary itself, I'd argue the workflow would be *more* complicated. You'd have to (1) start a server (e.g. `legendary lan-share start-server`) on the device you wish to copy files from, (2) instruct the client device to use the server (`legendary lan-share connect <local IP address of server device>`) and finally (3) install the game like normal (`legendary install <AppName>`).
I don't see how that'd be more convenient than just copying over files manually and running one `legendary import` command.

This is of course discounting actually implementing this feature into Legendary, which I assume will have its challenges as well.
