### ISSUE TITLE
`-h` argument causes conflict in legendary launch <App Name> command, preventing game launch

### ISSUE THREAD

**Issue by blackxfiied** [derrod/legendary#672]
## Platform

Operating system and version: macOS Sequoia 15.1 (24B83)
Legendary version (`legendary -V`): "0.20.34", codename "Direct Intervention"

## Expected Behavior

Legendary launches the game with the arguments irrespective of whether they begin with `-h`.

## Current Behavior

running  `legendary launch <App Name> [options] [arguments]` will not work if any of the `arguments` supplied begin with `-h` (for example, `-high`) -- otherwise, this output is shown:
```
usage: cli launch <App Name> [options]
cli launch: error: argument -h/--help: ignored explicit argument 'igh'
```
*('igh' being because i used `high` as an example.)*

<br>

presumably, this means that this will work for any of the single-letter `options`:
```
-h, --help            show this help message and exit
-H, --full-help       Show full help (including individual command help)
-v, --debug           Set loglevel to debug
-y, --yes             Default to yes for all prompts
-V, --version         Print version and exit
-J, --pretty-json     Pretty-print JSON
-A <seconds>, --api-timeout <seconds>
                      API HTTP request timeout (default: 10 seconds)
```

but this actually *isn't* the case -- this issue is only isolated to `-h`.
please fix this issue, otherwise this CLI is actually flawless, i use it in my game launcher:
https://getmythic.app/

## Steps to Reproduce

previous information is comprehensive enough
here's a screenshot anyway ig
<img width="585" alt="image" src="https://github.com/user-attachments/assets/7c0b7291-a210-4041-a2b9-459bb80d113c">

**Comment by arielj** [comment]
Try using `legendary launch <App Name> -- -high`.
