### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by tOPMOM2011** [derrod/legendary#675]
Platform
Operating system and version: windows 11 education version 23H2 (OS build 22631. 4460)
Legendary version: n/a
After getting steam on my computer I aimed for epic games and found you guys. I am pretty sure I have done somthing wrong but if you guys could tell me step by step of how to get legendary on here that would be amazing.

Current Behavior
lengendary won't install

C:\Users\________\Downloads\legendary-master\legendary-master>py setup.py
Traceback (most recent call last):
  File "C:\Users\_______\Downloads\legendary-master\legendary-master\setup.py", line 7, in <module>
    from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'

C:\Users\_______\Downloads\legendary-master\legendary-master>

Steps to Reproduce

I don't think y'all have windows education but all I tryed to do was download the zip file then set the cd to the extracted file and run
 py setup.py

thank you for reading my issue and please help me get your program running for me

**Comment by derrod** [comment]
Just install it via pip or download the exe. See the README/wiki for instructions
