### ISSUE TITLE
fortnite download getting stuck for hours

### ISSUE THREAD

**Issue by hallalujeh** [derrod/legendary#680]
## Platform

Operating system and version: Edition	Windows 11 Pro 24H2
Legendary version (`legendary -V`): legendary version "0.20.34", codename "Direct Intervention"

## Expected Behavior
Fortnite continues downloading normally.

## Current Behavior
Note: i have been for the past few  days pausing and resuming downloads that's why there's not much files left to download. currently around 14gb is left and the download is stuck 2048mb
fortnite's download is stuck when i have resumed it at a certain point. logs are in the screenshot below (the screenshot demonstrates me keyboard interrupting and exiting program after seeing that for the past 2 hours its been stuck at 2048mb):
![image](https://github.com/user-attachments/assets/c34f453b-26a1-41ce-ad13-c9d098458358)

## Steps to Reproduce

1. Start download for fortnite with `legendary install fortnite`
2. Confirm all prompts and let the download start
3. At a point (here 2048mb) the download is stuck.

**Comment by CommandMC** [comment]
The screenshot you've posted isn't enough to identify the issue. Looks like the download queue's empty for some reason. Most of the time this is caused by a slow connection.
Ideally send in a full download log (as a file though)

**Comment by hallalujeh** [comment]
> The screenshot you've posted isn't enough to identify the issue. Looks like the download queue's empty for some reason. Most of the time this is caused by a slow connection. Ideally send in a full download log (as a file though)

nvm i fixed it by using less workers (3) and inc shared mem to 8000 like mentioned in #574
