### ISSUE TITLE
[Feature Request] Downloading the linux versions of Unreal Engine

### ISSUE THREAD

**Issue by DeficientNull** [derrod/legendary#681]
Currently the Unreal Engine on Linux website only hosts ue5 versions. I believe the launcher itself has access to older ones but it would be nice to not have to use wine.

**Comment by derrod** [comment]
The linux version is not part of the EGS system because EGS doesn't exist on Linux.

**Comment by DeficientNull** [comment]
sad, epic forcing people to use 5. Anyway thanks regardless
