### ISSUE TITLE
Doesn't attempt to link Uplay titles to Uplay service first

### ISSUE THREAD

**Issue by kode54** [derrod/legendary#69]
I was wondering why my (months ago) free title of Watch Dogs was not launching after I'd installed it. So I rebooted to Windows and installed EGS, and EGS wouldn't install the game first without launching an OAuth link against Uplay, after which it allowed me to start downloading the game.

**Comment by derrod** [comment]
Yeah that's a known issue. Ultimately I think I'll just make that a warning/error + opening the OAuth site since many UPlay games on EGS are also out of date so you'll have to update/install them via UPlay anyway.

**Comment by tralph3** [comment]
So how would one install an EGS + Uplay game? They recently gave away Watch Dogs 2. I tried to download it (on linux) with legendary and it launched an uplay window which was borked. I installed Uplay with lutris and the game wasn't there, so I booted into Windows, downloaded the game again with legendary and it told me that EGS services were not available. I would need to download it with the actual EGS first and launch it once to have it link to Uplay and then download it via Uplay?

**Comment by kode54** [comment]
Same way I installed the Watch_Dogs giveaway. Install EGS, link your uplay account with your Epic account, and then you'll have the game in your Uplay library, so you can install and run it with Uplay directly.

**Comment by LinoBigatti** [comment]
This is kinda a big issue for me since the EGL doesnt run correctly on my machine (for some reason). I could code it if someone could provide an oauth link template.

**Comment by derrod** [comment]
Alright looking into this it's unfortunately rather annoying to do, and not something I'm likely to implement anytime soon. I will however add a warning and critical failure for games that require a uplay link/only ship a uplay installer and otherwise useless packed files.

**Comment by derrod** [comment]
Uplay linking is supported as of 0.20.19.
