### ISSUE TITLE
[Feature Request] Get General Game Information

### ISSUE THREAD

**Issue by Lightosk** [derrod/legendary#71]
Sometimes because of parsing/debugging purposes I want to look up on which version the game currently is. In the EGS I can do this by clicking on the 3 dots. In legendary I found no way of doing this. This could be a new command like `info`, the syntax could be 
```
Command: info
usage: legendary info [-h] [-v] <App Name>

positional arguments:
    <App Name>                      Name of the App info should be viewed

optional arguments:
    -h                              Shows this help message
    -v                              Show verbose output
```
As manifest is already in code, it shouldn't be that hard to implement.

**Comment by derrod** [comment]
Both `list-installed` and `list-games` show the version of the game (installed/latest respectively).
