### ISSUE TITLE
How can I change the location of wine?

### ISSUE THREAD

**Issue by Ahmed-E-86** [derrod/legendary#72]
First, thank you for this amazing project. It is mostly needed, and it does the job pretty well.

Second, I have a question about Legendary if you dont' mind:
How can I change **wine** used by Legendary?

I tried using `export WINE=/location/of/wine`, but that didn't help.

Is there any way of changing the default wine installed on my machine with a different wine, because sometimes some games need a different version of wine to run, and the latest wine versions have some issues, and it is advisable to run an older version of wine that I have on my machine, but I can't point to its location with Legendary.

**Comment by CommandMC** [comment]
You can change the location of the wine binary either with the `--wine` parameter or the "wine_executable" config option.

Both are mentioned in the readme file.

**Comment by Ahmed-E-86** [comment]
Oh! I am sorry. I just skimmed over the basic commands. Thanks for your reply.
