### ISSUE TITLE
Keyboard Issue 

### ISSUE THREAD

**Issue by Tornadocholo** [derrod/legendary#74]
Everything worked just fine but by the time i get to actually play the game i press any key on my keyboard and game freezes for a few seconds, im getting this error on the terminal:
 04c4:fixme:keyboard:X11DRV_ActivateKeyboardLayout flags 40000000 not supported
04f0:fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x4090409, 40000000: semi-stub
My default is Eng (US)
Im on latest Ubuntu btw. Any help will be appreciated, thank you so much for this project!

**Comment by CommandMC** [comment]
Unrelated to legendary

Try different wine versions and see if your game is listed on [protondb](https://www.protondb.com)

**Comment by CommandMC** [comment]
You can also join the [legendary discord](https://discord.gg/UJKBwPw) if you haven't already, there are some great people there that know a bunch of tricks to get stuff working

**Comment by Tornadocholo** [comment]
Thank you for your answer! the game is GtaV, I'll try to change the wine version, next time i'll post on the discord, thanks for the help:)

**Comment by CommandMC** [comment]
I have a tutorial on GTAV on the discord (in the help chat)

**Comment by Tornadocholo** [comment]
I'll go check it right now :+1:
