### ISSUE TITLE
crash on launch

### ISSUE THREAD

**Issue by synthggg** [derrod/legendary#75]
It opens for a few seconds then it crashes on me. i have the latest version of python installed and i have checked everything else. thanks

**Comment by CommandMC** [comment]
Legendary isn't a GUI program. It's ment to be ran from the terminal with arguments to do various things.

**Comment by synthggg** [comment]
i understand that, however when i go to open the terminal from the .exe file, it opens and a few seconds later it crashes on me

**Comment by CommandMC** [comment]
You're ment to open a terminal in the directory the .exe is in (or anywhere if you installed it from PyPI) and then type in `legendary`

**Comment by synthggg** [comment]
i have done this however i am still having the same problem. do i need anything else other than python and the standalone exe installed or within the dictionary?

**Comment by CommandMC** [comment]
Found the issue?
If so, it would be good if you can write your steps here so just in case other people have a similar issue, they can try what you did.
