### ISSUE TITLE
How to run proton with legendary games

### ISSUE THREAD

**Issue by Ohio2** [derrod/legendary#76]
**Hi i wanted to play some GTA V using legendary, and it uses default wine... i was wondering if i could get proton running.**

**Comment by CommandMC** [comment]
You have to put two things into your `config.ini` file:
```
[9d2d0eb64d5c44529cece33fe2a46482]
wrapper = /path/to//Steam/steamapps/common/Proton 5.0/proton run
no_wine = true
``` (assuming you want to use Proton 5.0)
and
```
[9d2d0eb64d5c44529cece33fe2a46482.env]
STEAM_COMPAT_DATA_PATH = /path/to/prefix/folder
```

**Comment by derrod** [comment]
Note that you might have to put the path to the Proton binary in quotes like so:
```
[9d2d0eb64d5c44529cece33fe2a46482]
wrapper = "/path/to/Steam/steamapps/common/Proton 5.0/proton" run
no_wine = true
```

**Comment by CommandMC** [comment]
Dang, I always forget the quotes. Thanks @derrod, I edited my comment

**Comment by Toorero** [comment]
Would this method also enable me to open all games with Proton, or does it only work with GTA?

**Comment by CommandMC** [comment]
You'd have to add that for every game, since the `wrapper` and `no_wine` arguments aren't supported in [Default] (yet)

**Comment by Ohio2** [comment]
Where is my config.ini and does proton typically locate in my home/.steam?

**Comment by CommandMC** [comment]
See the "Config file" portion in the readme for the location.

Your default steam install folder is in your home folder, yes.

**Comment by Ohio2** [comment]
Yeah about that, GTA V doesen't launch now.

**Comment by Ohio2** [comment]
ah it launches.
