### ISSUE TITLE
Installation Issue (_ctypes)

### ISSUE THREAD

**Issue by DionJoel** [derrod/legendary#77]
I have a problem with the installing it under Linux Mint 19.3

![Bildschirmfoto vom 2020-08-16 17-25-49](https://user-images.githubusercontent.com/68860957/90337978-a14ef580-dfe6-11ea-9d05-125401ad7179.png)

**Comment by derrod** [comment]
This is an issue with your python installation, I can't tell you what exactly is wrong, try googling the error. You'll find threads like these: https://stackoverflow.com/questions/27022373/python3-importerror-no-module-named-ctypes-when-using-value-from-module-mul
