### ISSUE TITLE
Failed locale - too many values to unpack

### ISSUE THREAD

**Issue by torstenchr** [derrod/legendary#79]
I cannot start any of my EpiC games using the legendary launcher. Whenever I try to launch a game i get the following error:

```
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[Core] WARNING: Getting locale failed: ValueError('too many values to unpack (expected 2)'), falling back to using en-US.
[cli] INFO: Launching Sage...
[cli] DEBUG: Launch parameters: **<redacted>**
[cli] DEBUG: Working directory: /home/torsten/mnt/Steam/Legendary/Overcooked
[cli] DEBUG: Environment overrides:

```
above is with OverCooked, but it happens with Phoenix Point as well.

I am running on an Arch System but since I'm a non-native english speaking my default locale is set to en_DK.UTF-8, but I have to following locales installed:

```
C
da_DK
da_DK.iso88591
da_DK.utf8
danish
dansk
en_DK
en_DK.iso88591
en_DK.utf8
en_US
en_US.iso88591
en_US.utf8
POSIX
```

Using the legendary prefixed with LANG=en_US.UTF-8 does unfortunately not help.

**Comment by derrod** [comment]
If you open up a python shell (`python3.8` probably) what do you get if you execute the following?
```python
from locale import getdefaultlocale
print(getdefaultlocale())
```

**Comment by torstenchr** [comment]
I get the following: 
```
[torsten@Rainier ~]$ python
Python 3.8.5 (default, Jul 27 2020, 08:42:51) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from locale import getdefaultlocale
>>> print(getdefaultlocale())
('en_DK', 'UTF-8')
>>> 

```

**Comment by derrod** [comment]
Mh `en_DK` should work fine, so I wonder why that's not what's happening. Have you overriden the locale in the config? Otherwise I cannot really explain this.

**Comment by torstenchr** [comment]
:facepalm: I completely forgot i wrote a custom config.ini a while back and for other reasons did not use Legendary for a while. Apparently the "locale" key was mistyped. This one is 100% on me...

This does lead to one question though - can the executable do a sanity check on the config file when loading it?

**Comment by derrod** [comment]
To some extent, yes. Though in this case the warning just needs to be more clear that the locale was taken from the config rather than the environment.
