### ISSUE TITLE
[Suggestion] Add DXVK support

### ISSUE THREAD

**Issue by Captn138** [derrod/legendary#80]
Title says everything. I'm trying to play This War Of Mine on my school laptop (Nvidia GTX940MX) and it's very laggy with legendary (20 FPS). Game requirements GTX260.
Problem is quite the same on every game. It would be a lot better if we could use DXVK.
Nice job anyways

**Comment by CommandMC** [comment]
If you want to use dxvk, just install it in the wine prefix you're using.

ProtonDB says that proton 4 might run this game better than 5, so you might wanna try that first
