### ISSUE TITLE
How to add Legendary as a executable to Lutrtis.

### ISSUE THREAD

**Issue by Ohio2** [derrod/legendary#82]
**Sorry if this is repetitive. But i want to add Legendary as a executable**

**Comment by derrod** [comment]
You can add it as a Linux game. See the Lutris documentation.

**Comment by Ohio2** [comment]
Problem is in my usr/bin legendary does not exist.

**Comment by derrod** [comment]
If you installed legendary run `which legendary` to get the path to the binary.  If you used the standalone version just use its path.
