### ISSUE TITLE
Download Legendary with my script

### ISSUE THREAD

**Issue by dpertierra** [derrod/legendary#85]
I'm writing a powershell script that set up windows for gaming and I would like to offer the user to install Legendary with it.
I'll be downloading Legendary from the latest release in your github repository.
I'll give Legendary's project link in the Write-Output in the script and in the github readme,

You can check the github project at https://github.com/dpertierra/win10script 

Let me know if there's any problem with me doing this.

**Comment by derrod** [comment]
Sure, as long as the license is disclosed somewhere that's fine.
