### ISSUE TITLE
Sync saves and performance in Ashen issues 

### ISSUE THREAD

**Issue by PrzemekSkw** [derrod/legendary#86]
Hi, I have two problems with Ashen game and legendary. Game works great with Lutris>Epic Games Launcher. I import game with legendary launcher and sync saved games:
```
[mariank@marian-dell ~]$ legendary sync-saves
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Got 4 remote save game(s)
[mariank@marian-dell ~]$ legendary -y egl-sync
[cli] INFO: Reading EGL game manifests...

Checking for importable games...
Nothing to import.

Checking for exportable games...
Nothing to export.

Checking automatic sync...
```
When I launch game I don't have saved games and I wasn't asked for saved games folder.
Second problem is that game works very slow with legendary. I see in config of Epic Launcher in lutris there's argument `-opengl` but when I try to launch game with this it wont start:
```
[mariank@marian-dell ~]$ legendary launch Wren -opengl
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Wren...
[mariank@marian-dell ~]$ 002c:fixme:winediag:__wine_start_process Wine Staging 5.15 is a testing version containing experimental patches.
002c:fixme:winediag:__wine_start_process Please mention your exact version when filing bug reports on winehq.org.
0034:err:menubuilder:init_xdg error looking up the desktop directory
00c0:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
00c0:fixme:gameux:GameExplorerImpl_VerifyAccess (0000000000FE1ED0, L"Z:\\home\\mariank\\Games\\epic-games-store\\drive_c\\Program Files\\Epic Games\\Ashen\\Ashen\\Binaries\\Win64\\Ashen-Win64-Shipping.exe", 00000000005EE3B8)
00c0:fixme:win:DisableProcessWindowsGhosting : stub
00c0:fixme:msctf:InputProcessorProfileMgr_GetActiveProfile (0000000000FF03A0)->({34745c63-b2f0-4784-8b67-5e12c8701a31} 00000000005EE990)
00c0:fixme:system:SystemParametersInfoW Unimplemented action: 59 (SPI_SETSTICKYKEYS)
00c0:fixme:system:SystemParametersInfoW Unimplemented action: 53 (SPI_SETTOGGLEKEYS)
00c0:fixme:system:SystemParametersInfoW Unimplemented action: 51 (SPI_SETFILTERKEYS)
00c0:fixme:msctf:ThreadMgr_Destructor Left Over ITfDocumentMgr.  Should we do something with it?
00b8:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 00000000005EFBB0
```
Can I make it work as good as in lutris?

**Comment by derrod** [comment]
You need to run the game in the same wineroot as you do via Lutris (i.e. the `epic-games-store` one), the saves are likely stored within it. As for performance that might also just may be a matter of using the correct wine prefix, also check that you're using all the same options as the Lutris install script is.

**Comment by PrzemekSkw** [comment]
@derrod Hi, I find in Lutris in Epic Launcher have wine prefix:
![Zrzut ekranu z 2020-08-27 09-05-52](https://user-images.githubusercontent.com/25219988/91427254-e9c7a800-e85d-11ea-96b7-dbdc3a19c1dc.png)
 so I try to start Ashen like this:
`legendary launch Wren --wine-prefix WINEPREFIX=/home/mariank/Games/epic-games-store`
but still have black screen.
Can You help me?
