### ISSUE TITLE
Xbox one S controller doesn't work in game when using Proton-GE as wine executable

### ISSUE THREAD

**Issue by samxl001** [derrod/legendary#87]
I am on Manjaro KDE with xpad-neo installed. I tried launching Abzu & Mortal Shell using Proton-5.9-GE-5-ST on legendary. The games launch but the controller doesn't work in game. I ran some other games on steam using Proton-5.9-GE-5-ST. The controller works perfectly there. Also I ran Abzu & Mortal Shell on Lutris using Epic Games Store. The controller also works there

**Comment by derrod** [comment]
I don't really think that this issue is my responsibility since it sounds like a wine/configuration issue, but I'll keep it open until I've checked if Lutris does anything special to configure wine.

**Comment by samxl001** [comment]
Thanks. Let me know if you need to see any logs

**Comment by Ahmed-E-86** [comment]
All patches for controllers are stripped from Proton, and Proton-GE. They do not provide controller support away from the Steam client. There is nothing to be done. The only solution that I know of is to use AntiMicro, and use your controller as a keyboard + mouse.
