### ISSUE TITLE
Downloading stuck at 5.33%

### ISSUE THREAD

**Issue by BoomWortel** [derrod/legendary#92]
I wanted to try Legendary but every game i install gets stuck at 5.33%. 
i get the error: {FileWorker}} WARNIGNG: Writer queue empty!

can someone help me? that wil be amazing.

running:
OS: Pop!_os 20.04
Kernel: 5.4.0-7642-generi

**Comment by derrod** [comment]
What game are you installing?

Try running `legendary -v install <your app name> --dlm-debug` and then share that log on pastebin/github gists or whatever. That will include debug information to help me figure this out. Also make sure you're on the latest version.

**Comment by BoomWortel** [comment]
On Mon, Sep 07, 2020 at 05:21:29PM -0700, Rodney wrote:
> What game are you installing?
> 
> Try running `legendary -v install <your app name> --dlm-debug` and then share that log on pastebin/github gists or whatever. That will include debug information to help me figure this out. Also make sure you're on the latest version.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/derrod/legendary/issues/92#issuecomment-688551508


The game im installing is Just cause 4 (Kakopo).
I used legendary -v install kakopo --dlm-debug.


this is the output: 
[LGDLFS] DEBUG: Failed to load installed game data: FileNotFoundError(2, 'No such file or directory')
[Core] INFO: Trying to re-use existing login session...
[Core] DEBUG: Set locale to en-US
[cli] INFO: Preparing download...
[LGDLFS] DEBUG: Failed to load installed game data: FileNotFoundError(2, 'No such file or directory')
[Core] DEBUG: Downloading manifest from https://download.epicgames.com/Builds/Org/o-7petn7mrlk8g86ktqm7uglcr7lfaja/64943f5c28484fcaa462c4c134f81b61/default/YVSFhrTIwcpAbOGpJ0irAt1fqimZXw.manifest?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6IipCdWlsZHMvT3JnL28tN3BldG43bXJsazhnODZrdHFtN3VnbGNyN2xmYWphLzY0OTQzZjVjMjg0ODRmY2FhNDYyYzRjMTM0ZjgxYjYxL2RlZmF1bHQvWVZTRmhyVEl3Y3BBYk9HcEowaXJBdDFmcWltWlh3Lm1hbmlmZXN0IiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNTk5NTU3MDkzfSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=H4uSd7x1dGfjt2uqpwyDPqnSEYyCkP3Qixc9Cs8ep8wfIEa1sbjdnt4Ie6HTYES50cyPrJgtcheIjoBJha8oYboXJ3J1jaaln1fcPUgVmJ09YanY--5CaZBEmdLEJVES50atBmXK-0TZgzhEOnOAjmmlOL3pxWWprCVRu90sM4WG07UXKuNqO4-bwAYxfTRJvHIo3rgfSwaPOeme9MJeqd7vldZgN4eeEyqOUVbb6jU9~ulvaQqLR-f9SX-mFMu2fOnRKeYic6EOivIe6clMyTSvSm-Ofa8KbVwUXTovhX9pn2Kd2B4nTPtrKcQUyfhOpDpCNGFH92-nUZaehn9ang__&Key-Pair-Id=APKAI5CNFPJPTPYZISXQ ...
[Core] INFO: Parsing game manifest...
[Core] DEBUG: Base urls: ['https://download.epicgames.com/Builds/Org/o-7petn7mrlk8g86ktqm7uglcr7lfaja/64943f5c28484fcaa462c4c134f81b61/default', 'https://download2.epicgames.com/Builds/Org/o-7petn7mrlk8g86ktqm7uglcr7lfaja/64943f5c28484fcaa462c4c134f81b61/default', 'https://download3.epicgames.com/Builds/Org/o-7petn7mrlk8g86ktqm7uglcr7lfaja/64943f5c28484fcaa462c4c134f81b61/default', 'https://download4.epicgames.com/Builds/Org/o-7petn7mrlk8g86ktqm7uglcr7lfaja/64943f5c28484fcaa462c4c134f81b61/default', 'https://epicgames-download1.akamaized.net/Builds/Org/o-7petn7mrlk8g86ktqm7uglcr7lfaja/64943f5c28484fcaa462c4c134f81b61/default']

I hope this is enough information.

Thanks.

**Comment by derrod** [comment]
No, please post the *full* output.
