### ISSUE TITLE
Unable to launch game / Wine not found

### ISSUE THREAD

**Issue by Ugyuu** [derrod/legendary#95]
Hello! Before I start, thank you for making Legendary a thing. I very much like it.

I've been attempting to get Legendary going with my limited Linux experience, but ran into some roadblocks on the way.
I had to make a config file for legendary, since it wasn't created automatically when I manually installed version 19. I've used the config example on the main page for this.
Everything works, except games won't launch. At first, it was because it tried to launch a 64-bit game with a 32-bit wine exec, which obviously won't work, but now it can't find my wine, which does exist.

I'm trying to launch Totally Reliable Delivery Service as a test (Codename **Hoatzin**).
My config file for Legendary, as well as the output when trying to launch, are in this pastebin: [Pastebin](https://pastebin.com/HPya393k)

I'm running **Manjaro Linux, Kernel 5.7.19-2-MANJARO.**
I have **Proton 5.0, 4.11,** but also **Lutris 5.7.8** and **5.6.5** installed.
Furthermore, I've re-installed the latest version of Legendary through yay before trying this. Version **0.20.1.**
I tried to give as much information as possible right away.
What should I set differently to make it launchable? Did I do something wrong?

**Comment by CommandMC** [comment]
You've used a relative path to your wine exec. Not sure if that works, but I would try using an absolute path (path to your home folder is `/home/YourUserNameHere/` (you can get your exact username by running `whoami`)

Also, as far as I know, lutris' wine (and proton, but that's a whole 'nother story) store their wine builds in `.../lutris-X.X-X-x86_64/bin/`, not `/lib64/`

**Comment by Ugyuu** [comment]
Thank you for reminding me of absolute paths!
I've updated my config that way.
Now it seems that something is wrong with my wine configuration. I've got an older, Windows XP game (which needs 32-bit) running on Lutris. Though, even after setting Winecfg back to Windows 10 and checking my runner settings, it outputs the following through launching Hoatzin again:

> [Core] WARNING: Game is not approved for offline use and may not work correctly.
> [Core] DEBUG: Set locale to en-US
> [cli] INFO: Launching Hoatzin... 
> [cli] DEBUG: Launch parameters: /home/konqifan/.local/share/lutris/runners/wine/lutris-5.7-8-x86_64/bin/wine '/home/konqifan/legendarygames/TRDeliveryServ>
> [cli] DEBUG: Working directory: /home/konqifan/legendarygames/TRDeliveryService 
> [cli] DEBUG: Environment overrides:
> 000b:fixme:winediag:start_process Wine TkG 5.7 is a testing version containing experimental patches.
> 000b:fixme:winediag:start_process Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
> 000d:err:module:__wine_process_init L"C:\\windows\\system32\\winemenubuilder.exe" not found
> 000b:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
> 001b:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
> 000f:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
> 0009:err:module:__wine_process_init L"Z:\\home\\konqifan\\legendarygames\\TRDeliveryService\\Totally Reliable Delivery Service.exe" 64-bit application not supported in 32-bit prefix

**Comment by derrod** [comment]
This is an issue with your wine prefix, just google how you can set upa 32 bit prefix or how to switch a prefix to 32 bit.
