### ISSUE TITLE
Boarderlands 2 is installed in the legendary folder but is not being detected by legendery. 

### ISSUE THREAD

**Issue by C3R3S1** [derrod/legendary#97]

**Comment by CommandMC** [comment]
What do you mean by "the legendary folder"? How did you install it?

@derrod Maybe add an issue template so we don't get these issues with 0 context

**Comment by C3R3S1** [comment]
Yes the legendary folder

**Comment by CommandMC** [comment]
There are:
- the legendary config folder at ~/.config/legendary
- your game installation folder which is set in the config
Which one of those do you mean?
And how did you install it? Using legendary? Or something else?

**Comment by derrod** [comment]
You should explain what you actually did, and what you mean by "it's not being detected". Otherwise I'll just close this issue.

**Comment by CommandMC** [comment]
I'd assume it's safe to close this for now. If need be, OP can still reopen the issue.
