### ISSUE TITLE
Game Art, Description, etc api

### ISSUE THREAD

**Issue by TecCheck** [derrod/legendary#98]
Hey there,
I guess it's already on the roadmap as _Better interfaces_, but if not:
It would be cool to have an api for getting the description, image urls, rating and other media for displaying them in a gui as part of the `Game` Interface.

**Comment by CommandMC** [comment]
Although an API for it would indeed be good, reading out the .json files in the "metadata" folder in the config dir works just fine.

In case you need an example, my GUI project called Rare reads out the image download URLs from there.

**Comment by derrod** [comment]
`Game` and `GameAsset` both have a `metadata` property that contains Epic's metadata for that game, including URLs for images etc. (Though I should really redo that, there's no reason for both of those to exist, it should just be a single class for all apps). That does not contain most store metadata such as description though.
